### ISSUE TITLE
Large images aren't scaled to viewport

### ISSUE THREAD

**Issue by MDWolinski** [brentsimmons/NetNewsWire#1010]
When previewing news articles, large images are not scaled to the viewport which requires a horizontal scroll to view the full image.  Would be nice if images were responsive to the available view.

<img width="1070" alt="Web____Design__107_" src="https://user-images.githubusercontent.com/22196395/64710295-b1c92880-d485-11e9-8eab-e8016f25700a.png">

**Comment by hyakugei** [comment]
Pretty sure there is a fix for this in the next build...

**Comment by MDWolinski** [comment]
This is not fixed in 5.0.2 as of this moment.

**Comment by brentsimmons** [comment]
What’s the URL of the feed?

**Comment by MDWolinski** [comment]
https://www.thisiscolossal.com/

Look at a Sept 11, 2019 Article that starts Murderous Hippos

**Comment by brentsimmons** [comment]
Reproducible using https://www.thisiscolossal.com/feed/

**Comment by vincode-io** [comment]
I updated the article css to handle the https://www.thisiscolossal.com/ scenario.  Should be out in the upcoming 5.0.3 release.
