### ISSUE TITLE
BUG: Incorrect Article Link

### ISSUE THREAD

**Issue by pjain02** [brentsimmons/NetNewsWire#1012]
For the feed: https://www.livemint.com/rss/Lounge, clicking on the article link takes to an incorrect page.

For example for the following item in the feed:

```xml
<item>
    <title>
        <![CDATA[ Adding a natural touch to skincare products ]]>
    </title>
    <link>
        <![CDATA[
        https://www.livemint.com/mint-lounge/business-of-life/adding-a-natural-touch-to-skincare-products-1568222173893.html
        ]]>
    </link>
    <description>
        <![CDATA[
        Founded seven years ago, SkinYoga offers all-natural products for body, foot, face and hair in 29 countries.Some of their products have been inspired by their grandmother’s “recipes” like the sandalwood and saffron face mask; some have been created after consultations with and studies by dermatologists in a laboratory in Massachusetts
        ]]>
    </description>
    <author>
        <![CDATA[ Pooja Singh ]]>
    </author>
    <pubDate>
        <![CDATA[ Wed, 11 Sep 2019 22:52:30+5:30 ]]>
    </pubDate>
    <guid>
        <![CDATA[ 1568222173893 ]]>
    </guid>
    <thumbnail>
        https://images.livemint.com/img/2019/09/11/90x90/9CIYGDNZ_1568222337766_1568222338102.jpg
    </thumbnail>
    <smallimage>
        https://images.livemint.com/img/2019/09/11/250x250/9CIYGDNZ_1568222337766_1568222338102.jpg
    </smallimage>
    <bigimage>
        https://images.livemint.com/img/2019/09/11/600x338/9CIYGDNZ_1568222337766.jpg
    </bigimage>
    <image>
        https://images.livemint.com/img/2019/09/11/250x250/9CIYGDNZ_1568222337766_1568222338102.jpg
    </image>
</item>
```

Clicking on the item header takes to this link: https://www.livemint.com/rss/1568222173893 which does not exists. The correct link is https://www.livemint.com/mint-lounge/business-of-life/adding-a-natural-touch-to-skincare-products-1568222173893.html which is present in the item xml.

**Comment by brentsimmons** [comment]
There’s a bug in the feed. The guid should be a permalink, but it’s not.

NetNewsWire 5.0.1 has a fix for this.

**Comment by martinlindhe** [comment]
I was just going to report the same.

> The guid should be a permalink, but it’s not.

This is not correct. 

A GUID is a unique identifier, not a URL.

The <link> tag is used in RSS to supply article links.

Many feeds use the same, but it is by no means a requirement.

The idea of the GUID is to be able for the RSS client to realize that an item that has an updated Title, and thus an updated url slug is still the same item, so it can be tracked as read.

GUID is not supposed to be treated as links.

Here's what the standard is saying:

> <guid> sub-element of <item> *
> <guid> is an optional sub-element of <item>.
> guid stands for globally unique identifier. It's a string that uniquely identifies the item. When present, an aggregator may choose to use this string to determine if an item is new. [1]

**I would like to see this issue reopened and re-evaluated.**


1: https://www.rssboard.org/rss-specification#ltguidgtSubelementOfLtitemgt

**Comment by brentsimmons** [comment]
Also from the spec:

`If the guid element has an attribute named isPermaLink with a value of true, the reader may assume that it is a permalink to the item, that is, a url that can be opened in a Web browser, that points to the full item described by the <item> element.`

…and…

`isPermaLink is optional, its default value is true.`

In other words: any `guid` that does not include `isPermaLink=false` can be assumed to be a permalink.

**Comment by martinlindhe** [comment]
> Also from the spec:
> 
> `If the guid element has an attribute named isPermaLink with a value of true, the reader may assume that it is a permalink to the item, that is, a url that can be opened in a Web browser, that points to the full item described by the <item> element.`
> 
> …and…
> 
> `isPermaLink is optional, its default value is true.`
> 
> In other words: any `guid` that does not include `isPermaLink=false` can be assumed to be a permalink.

Fine. That's one interpretation I guess.

But if we read the full spec and don't just nit-pick to prove a point, we will learn that `<link>` is the field intended to hold the URL.

**Comment by martinlindhe** [comment]
Fine. Nevermind.

**Comment by brentsimmons** [comment]
Writing up an explanation for anyone who runs across this issue later.

We learned early on in NetNewsWire development — 2003, I think, give or take a year — that when users want to open an article’s web page, they want to open the permalink for any given article.

That is, if they open it in their browser, they want to go to the actual post on the blog.

We get that permalink from the `guid` tag (unless `isPermaLink=false` or the permalink doesn’t appear to be a URL).

The `link` tag is often a permalink too — but that’s no guarantee, and it’s often _not_ a permalink. It’s often a link to something else — the subject of the article. This is especially true with linkblogs or blogs that typically write about something written up elsewhere. For those blogs, the `link` often links to that elsewhere URL.

We parse and store both, of course, since both are useful.

When you go to open article in your browser, NetNewsWire prefers the permalink (from the `guid`) if there is one — otherwise it uses the `link`.
