### ISSUE TITLE
Content Extraction

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1013]
We want to use a parser or service (almost certainly Feedbin’s service) that provides content extraction for feeds that don’t provide full content.

More about this: https://inessential.com/2019/09/04/on_the_many_netnewswire_feature_requests

The user interface for this needs design. How should this work?

There are a bunch of questions to answer, in no particular order…

What do we call the content-extraction view?

I’m reading an article, and it’s not full-text — what do I do to get the content-extracted view?

Can I click on any link in an article and get a content-extracted view of the target URL? How do I do that instead of just having the link open in a web page?

Or… is this modal somehow? As in: I’m in content-extraction mode, and so every article loads with the content-extraction view until I switch out of this mode? If so, how do I switch modes?

When I click a link in a content-extraction view, does it open in browser or does it do another content-extraction view of the target?

When the user is looking at a content-extraction view, do we need a browser toolbar at the top of the pane — with URL field, back/forward, etc.?

What do we do when the content extraction service fails to parse a page? (Which happens some percentage of the time.)

Should we have a per-feed setting, so that, for a given feed, articles are always opened in content-extraction view? If so, where does that setting go and how is it worded? (It probably goes in the Inspector.)

How do we make it visible to the user that it’s a content-extracted view and not the article as it appears in the feed?

How do I get back from content-extraction to the article as it appears in the feed?

**Comment by vincode-io** [comment]
> What do we call the content-extraction view?

Reader

> I’m reading an article, and it’s not full-text — what do I do to get the content-extracted view?

Click on the Reader toolbar button

> Can I click on any link in an article and get a content-extracted view of the target URL? How do I do that instead of just having the link open in a web page?

Article links should not trigger the Reader

> Or… is this modal somehow? As in: I’m in content-extraction mode, and so every article loads with the content-extraction view until I switch out of this mode? If so, how do I switch modes?

The Reader toolbar button should toggle

> When I click a link in a content-extraction view, does it open in browser or does it do another content-extraction view of the target?

The Reader view replaces the article in the Detail view

> When the user is looking at a content-extraction view, do we need a browser toolbar at the top of the pane — with URL field, back/forward, etc.?

None of that junk I hope.  Clicking a link should open a browser.

> What do we do when the content extraction service fails to parse a page? (Which happens some percentage of the time.)

The Reader button should indicate a failed state.  Put a red exclamation point in it or something.

> Should we have a per-feed setting, so that, for a given feed, articles are always opened in content-extraction view? If so, where does that setting go and how is it worded? (It probably goes in the Inspector.)

I wouldn't do this until we have other per feed settings.

> How do we make it visible to the user that it’s a content-extracted view and not the article as it appears in the feed?

The toolbar button will be in a toggled state.

> How do I get back from content-extraction to the article as it appears in the feed?

Push the Reader button again.

Attached is a video of how I think it should work.

[Screen Recording 2019-09-11 at 3.40.23 PM.mov.zip](https://github.com/brentsimmons/NetNewsWire/files/3602684/Screen.Recording.2019-09-11.at.3.40.23.PM.mov.zip)

**Comment by nickgravelyn** [comment]
As a recent user to NetNewsWire and Feedbin (previously using News Explorer), this would be great. It's one of the main reasons I started using Feedbin. The design above reflects  very much sounds like how I would expect this feature to work.

I would advocate for some mechanism for automatically enabling the reader mode. I have certain RSS feeds that always show snippets where I'm always going to click on that button. This means if I get 10 articles from a feed, each new article I have to get my mouse and click a button (or perhaps use a keyboard shortcut which would be better). If the app has some setting (per feed or global) to always use this service that would definitely improve the experience for me as it has using Feedbin's web interface (where Feedbin has an option to always try loading content from the source page).
