### ISSUE TITLE
Keyboard focus lost when moving right into content view (rightmost view)

### ISSUE THREAD

**Issue by DrTacoMD** [brentsimmons/NetNewsWire#1014]
If I press right to move from the middle articles list to the rightmost content view, I can no longer navigate by keyboard. Pressing left no longer returns me to the articles list, and up/down/spacebar don't move the content view. If I click in the content view everything is restored, unless I navigate left and back right into it, at which point the bug comes back.

Running macOS 10.14.6, NetNewsWire Version 5.0.1b1 (2613).

**Comment by vincode-io** [comment]
Thanks for catching this!  It is resolved and the fix will be in the next beta release.
