### ISSUE TITLE
iOS: Re-selecting the currently selected feed on iPad causes it to reload

### ISSUE THREAD

**Issue by philviso** [brentsimmons/NetNewsWire#1017]
Steps to reproduce:

1. On iPad, rotate to three column view
2. Select a feed or smart feed from the master feeds list
3. Within that feed, scroll the articles timeline a little bit and select an article
4. Tap on that feed / smart again from the master feeds list

#### Expected result

This should work the same way the Mac version works where if you re-select the currently selected feed / smart feed, that selection is ignored.

#### Actual result

The articles timeline reloads, scroll position is lost, and whatever article you had selected is no longer selected.

**Comment by vincode-io** [comment]
Thanks for finding this @philviso.  The fix is now in the repo.
