### ISSUE TITLE
5.0.1b1 - Using arrow keys to move from article to feed item list causes selected feed item to lose focus

### ISSUE THREAD

**Issue by akarnid** [brentsimmons/NetNewsWire#1018]
In v5.0 you could move from feed list to feed item list by clicking right arrow,  scroll up or down with up/down keys and hit Left arrow to go back to the feed item list.  This is not possible anymore in the new beta.  While on a feed item, clicking left does nothing and neither does hitting Up or Down to scroll.

**Comment by vincode-io** [comment]
Thanks for the bug report!  We have already identified this issue and it will be fixed in the upcoming 5.0.1 bug fix release.
