### ISSUE TITLE
Integrate fixed RSAppMovementMonitor

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1020]
See bug report here: https://github.com/redsweater/RSAppMovementMonitor/issues/4

**Comment by danielpunkass** [comment]
The fix is in https://github.com/brentsimmons/RSCore/pull/16

This turns out to be both a more critical bug than I thought, and slightly more complex in its fix. I am kind of rushing this fix because the behavior is so bad, so a couple extra eyes on that patch would be helpful!
