### ISSUE TITLE
Request: Space to enter folders instead of viewing them

### ISSUE THREAD

**Issue by mrvacbob** [brentsimmons/NetNewsWire#1024]
I have a mix of top-level feeds and feeds in folders. In NNW 3 I'd check them by pressing space to advance - if I got to a feed where nothing was interesting I could mark all as read.

In 5, hitting space selects the next folder instead of going to the specific unread feed inside it. So if I mark all as read, I lose everything in the folder.

**Comment by jamadden** [comment]
Looks like a dup of #567

**Comment by vincode-io** [comment]
Closing.  We'll track this issue using #567.
