### ISSUE TITLE
Add "Enable Web Inspector" menu item to the Debug menu

### ISSUE THREAD

**Issue by Wevah** [brentsimmons/NetNewsWire#1025]
Tracking issue. (Currently just enables the "Inspect Element" contextual menu item in the WKWebView.)

I'm almost done with this, but I have one question: As it's a hidden API on `WKPreferences`, should I use `setValue(_,forKey:)`, or add a bridging header?

(Current WIP at https://github.com/Wevah/NetNewsWire/tree/enable-inspector.)

**Comment by Wevah** [comment]
Decided to go the bridging header route.

**Comment by RobFog** [comment]
This should be marked as "fixed" with #1026 merged.
