### ISSUE TITLE
Youtube embedded videos are very small

### ISSUE THREAD

**Issue by pcora** [brentsimmons/NetNewsWire#1034]
Youtube videos are rendering very small on the desktop app:

<img width="667" alt="Screen Shot 2019-09-19 at 10 45 47" src="https://user-images.githubusercontent.com/312661/65249679-c8493280-daca-11e9-8b10-73cb222a8e3b.png">

I tried fiddling with settings, but could not find anything to change that. And if I recall right, this was not happening a few days ago.

**Comment by vincode-io** [comment]
This has been fixed and will be in 5.0.3.
