### ISSUE TITLE
iOS Feeds Screen: use arrows on left to expand/collapse folders

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1063]
Let’s go back to how earlier versions of NetNewsWire did it — expandos on the left. The Feedbin iOS app does it the same way.

I’m not saying we need to match the appearance of the below, obviously. Just for reference.

![FeedsScreen](https://user-images.githubusercontent.com/1297121/65659056-f6ed6e80-dfde-11e9-8a62-fc17eda93735.png)

**Comment by brentsimmons** [comment]
Don’t worry about indentation too much yet. Let’s just do it first, then sweat the pixels later.

**Comment by vincode-io** [comment]
Here is a version with indentation and Folders.  I'm not very happy with it.  I'm going to redo it without folders where the chevron takes the place of the folder icon.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-26 at 19 34 47](https://user-images.githubusercontent.com/16448027/65734313-f2d15780-e097-11e9-85fe-e9dc348dbec5.png)

**Comment by vincode-io** [comment]
This is much better.  I'm assuming this was what you had in mind originally.  It is much closer to the Feedbin interface you referenced.

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-09-26 at 20 37 38](https://user-images.githubusercontent.com/16448027/65735646-bd2f6d00-e09d-11e9-9b67-9fabae3b6624.png)
