### ISSUE TITLE
iOS set up account screens: password should have a Show/Hide Password button on right

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1066]
This should be true for each of the various accounts that require a password. The button title should be “Show” or “Hide,” depending on state.

**Comment by brentsimmons** [comment]
Word on the street is that 13.2 beta is coming out this week.

**Comment by vincode-io** [comment]
This crasher never did get resolved.  I had to work around it by bridging into UIKit.  Sigh...
