### ISSUE TITLE
Slack invite no longer valid

### ISSUE THREAD

**Issue by oliikit** [brentsimmons/NetNewsWire#1084]
The slack invite (https://join.slack.com/t/netnewswire/shared_invite/enQtNjM4MDA1MjQzMDkzLTNlNjBhOWVhYzdhYjA4ZWFhMzQ1MTUxYjU0NTE5ZGY0YzYwZWJhNjYwNTNmNTg2NjIwYWY4YzhlYzk5NmU3ZTc) is no longer valid. 😢 Unsure if you all still use this for communication, but if you are, I'd like to join.

**Comment by brentsimmons** [comment]
Thanks for the heads-up! I had no idea these could expire.

I’ll get a new invitation URL.

**Comment by brentsimmons** [comment]
I created a new URL. I also created a shorter version that will redirect.

https://ranchero.com/netnewswire/slack

**Comment by brentsimmons** [comment]
@oliikit If you go to https://ranchero.com/netnewswire/slack you’ll be able to join the Slack.

**Comment by oliikit** [comment]
🥳 woo! thank you!
