### ISSUE TITLE
Article code samples are difficult to read

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#1089]
I'd like to make it easier to read inline code samples.  Right now they wrap, but I would like to box them so that the line breaks don't change and you may have to scroll to see the full line.

Before:

![Screen Shot 2019-09-30 at 9 27 53 PM](https://user-images.githubusercontent.com/16448027/65929941-9a68c580-e3c9-11e9-9b9a-ba139b23b97f.png)

After:

![Screen Shot 2019-09-30 at 9 26 38 PM](https://user-images.githubusercontent.com/16448027/65929957-a05ea680-e3c9-11e9-9b9c-5cfda7df71df.png)

**Comment by vincode-io** [comment]
Is this something we don't want to do to the default CSS?  If so, we can close this with a comment to wait until article styles are implemented.

**Comment by brentsimmons** [comment]
Is there way to put a box around the whole thing instead of each individual line?

**Comment by vincode-io** [comment]
That wasn't the best example.  There are three different `pre` tags in that one.  Here's what it looks like when you only use one pre tag per block.

![Screen Shot 2019-10-03 at 4 14 08 PM](https://user-images.githubusercontent.com/16448027/66164756-fd8c6f00-e5f8-11e9-869a-46034bce4c59.png)

**Comment by brentsimmons** [comment]
That seems reasonable. Let’s do it.

**Comment by vincode-io** [comment]
Thanks for approving this one.  The horizontal scrolling isn't idea, but line breaks can make indented code unreadable.  I read a lot of programming blogs with sample code and this makes those blogs much easier to read.
