### ISSUE TITLE
iOS: Context Menu previews opened from links do not open when tapped

### ISSUE THREAD

**Issue by sh4338** [brentsimmons/NetNewsWire#1090]
When a link is tapped in the app, it is opened in an SFSafariViewController.  When the link is 3D touched, it shows a context menu with a preview of the page on top.  When the preview is tapped, it should open in an SFSafariViewController, or in Safari.  Instead, it closes the context menu and does nothing.

**Comment by vincode-io** [comment]
Thanks for the bug report.  This is fixed in the repo.
