### ISSUE TITLE
Feature Request: Display feeds by right clicking on the app in Dock

### ISSUE THREAD

**Issue by Dajinni** [brentsimmons/NetNewsWire#1096]
Please add the previous capability of just right clicking on the app in the dock to display the One of the key features was the ability to quickly glance at my feeds by just right clicking the app in the dock and selecting the article I want to read.  

Unfortunately 3.3.2 which still had this capability and I have been using daily no longer works with Catalina.

**Comment by vincode-io** [comment]
Thanks for the feature request.  We are already tracking this under Issue #83 so I'm going to close this request.
