### ISSUE TITLE
Suggestion: Rename "New Feed" Label

### ISSUE THREAD

**Issue by majouji** [brentsimmons/NetNewsWire#1097]
Currently, the command label for adding a feed subscription reads as "New Feed". The "new" prefix is usually used when creating a new item inside of the app you are using (creating a new file, document, photo album, etc).

Would suggest renaming it to "Subscribe to Feed".

**Comment by brentsimmons** [comment]
Using “New Feed” for this allows us to use cmd-N and File -> New Feed.

This is slightly unconventional, I grant, but it’s also a lesson learned from years of NetNewsWire development — it’s actually the best of no-perfect-options.
