### ISSUE TITLE
Double-clicking a feed should open its home page

### ISSUE THREAD

**Issue by guyharris** [brentsimmons/NetNewsWire#1099]
If you double-click on a feed in the feeds sidebar, NetNewsWire 4 will open the feed's home page; this is a convenient way to open that page.

It'd be nice if NetNewsWire 5 did the same.

**Comment by vincode-io** [comment]
@brentsimmons We have a pull request that implements this item.  Is this ok to add to the 5.1 release or did you have some other use planned for the feed double click.

**Comment by brentsimmons** [comment]
Yup. Added it to the 5.1 milestone.
