### ISSUE TITLE
Put Debug menu behind hidden preference

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1108]
The pref should be named ShowDebugMenu. It should be available in the release build, even the MAS build, and not just when running from Xcode.

The web inspector, however, should not be available in the MAS build.

**Comment by correia** [comment]
I can take care of this.

**Comment by jamadden** [comment]
> The web inspector, however, should not be available in the MAS build.

That seems unfortunate. I’m not familiar with the sandbox restrictions these days; I guess that’s one of the limitations?

**Comment by brentsimmons** [comment]
The web inspector requires the use of private API. Apple would reject the app if we tried to include it.

**Comment by Wevah** [comment]
FWIW, you should still be able to enable it (or at least the "Inspect Element" context menu item) manually by setting the appropriate user default.

**Comment by Wevah** [comment]
This seems to have never made it over to `master`.

**Comment by vincode-io** [comment]
Would you be good enough to submit pull request to get master caught up?

**Comment by Wevah** [comment]
Sure.
