### ISSUE TITLE
It would be useful to have a toolbar item to mark all items in a feed as read

### ISSUE THREAD

**Issue by guyharris** [brentsimmons/NetNewsWire#1109]
In NetNewsWire 4, the check mark toolbar icon acts as "Mark all as {read, unread}".

In NetNewsWire 5, it acts on the currently-selected item, marking it as read or unread.

One of my feeds is my Wikipedia watched pages; if I want to check the changes, from NNW 4, I'd mark them all read and double-click the feed to go to my watchlist.  From NNW 5, I have to pop up a context menu, mark all read, pop up another context menu, and go to the home page for the feed.  My previous issue, now fixed, will mean I can double-click the feed to go to my watchlist; it'd also be nice to be able to clear all the items in the feed before that without having to pop up a context menu.

**Comment by brentsimmons** [comment]
There is a Mark All as Read button in the toolbar — it operates on the articles currently in the timeline. Does this not do the trick for you for some reason?

**Comment by guyharris** [comment]
OK, that's a little confusing, with two checkmark buttons.  If there were other toolbar functions corresponding to per-feed operations, or the buttons looked different even if you don't hover over them and see the toolbar, it might be a bit more discoverable.

Thanks - that button does the job.
