### ISSUE TITLE
Superscript impacts line height

### ISSUE THREAD

**Issue by krschmidt** [brentsimmons/NetNewsWire#1115]
Desktop app on Mac, Version 5.0.2 (2615). Superscript increases the space between that line and the one above it. I imagine, but haven't verified, that subscript causes a similar issue for the line below. 

<img width="302" alt="image" src="https://user-images.githubusercontent.com/605794/66439507-be895f80-e9e4-11e9-9e51-a2a40c5ebf68.png">

**Comment by brentsimmons** [comment]
Is this in the article pane? (I assume it is — just double-checking.)

**Comment by krschmidt** [comment]
I'm assuming yes - it's the far right side of this screenshot:
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/605794/66440989-e3cc9c80-e9e9-11e9-81cb-1044309687da.png">

**Comment by brentsimmons** [comment]
Got it.

Here’s the thing: that’s a web view, and the rendering is entirely handled by Apple’s WebKit. There isn’t anything we can do about this issue, unfortunately.

**Comment by brentsimmons** [comment]
I hear there might be a CSS solution, so I’m re-opening this. :)
