### ISSUE TITLE
Import directly from older versions

### ISSUE THREAD

**Issue by iandunn** [brentsimmons/NetNewsWire#1128]
I've used NNW 3 for I don't know how many years -- thanks! -- but today I upgraded to Catalina and can't open it anymore.

I installed v5, but I can't import the hundred or so subscriptions I have, because I can't open v3 to export an OPML.

This might be too much of an edge case to warrant fixing, but if there's a sizable group of users in the same situation, it might be worth building a way to import directly from the `Subscriptions.plist` file, or provide some docs on how to manually convert that to OPML, or something?

**Comment by iandunn** [comment]
The subscriptions binary can be converted to XML like this:

```sh
> cd ~/Library/Application Support/NetNewsWire
> cp Subscriptions.plist Subscriptions.plist.bak # necessary because the next command will overwrite the file
> plutil -convert xml1 Subscriptions.plist
> mv Subscriptions.plist Subscriptions.xml
> mv Subscriptions.plist.bak Subscriptions.plist
```

I haven't found a good way to convert that XML file to OPML, though.

**Comment by mhart** [comment]
I just ran into this yesterday! Hacked up a quick and dirty way to do it here: https://gist.github.com/mhart/96dad3689cccc04a088522249d27c03e

**Comment by brentsimmons** [comment]
Done in 5.0.3b2. It does it automatically on first run. Or you can choose File > Import NNW3 Subscriptions.

**Comment by iandunn** [comment]
Thanks!
