### ISSUE TITLE
Add network progress bar to Feeds toolbar.

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#1165]

**Comment by vincode-io** [comment]
When we remove the blue navigation progress there won't be any indication that a pull to refresh worked or not when triggered from the Timeline.  I recommend we only allow pull to refresh on the Feeds scene where there will be visual indication that the pull did indeed trigger the refresh.

**Comment by brentsimmons** [comment]
Agreed.
