### ISSUE TITLE
iPad Timeline: search box appears after rotating device 

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1171]
1. Open NetNewsWire with device in portrait orientation
2. Select a feed from the feed list
3. Turn device to landscape orientation

The timeline’s search box becomes visible, but should not.

**Comment by vincode-io** [comment]
Reopening this again because the cure was worse than the disease.

**Comment by vincode-io** [comment]
Ok, I'm not seeing this anymore in iOS 13.2.

@nostodnayr could you verify for me that this is no longer an issue?

**Comment by nostodnayr** [comment]
I'm not seeing it build 5; good news 🙂
