### ISSUE TITLE
iOS: timeline can take up full right column after rotating 

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1172]
This is the state I’m describing: ![F07136FA-714A-4E0B-9AA5-CA08ABF94BC3](https://user-images.githubusercontent.com/2190735/67440547-9a5c8e00-f634-11e9-9af2-9fd6815b8766.png)

Steps:

1. Open NetNewsWire with device held in portrait orientation
2. Lock the device and rotate it to landscape orientation whilst locked
3. Return the device to portrait orientation and unlock the device

The application should be in the state shown in the screenshot. There maybe a certain amount of speed needed for this to work.

**Comment by vincode-io** [comment]
I'm not sure I understand. Is this a bug you are describing or is it a feature request?

**Comment by nostodnayr** [comment]
Bug. Sorry.

**Comment by vincode-io** [comment]
Ok.  I was able to recreate the issue.  I'm not sure how I'm going to debug it yet since it happens while the device is locked...

**Comment by vincode-io** [comment]
I just made a change that I think makes this impossible now.  At least I haven't been able to recreate it again.  Could you please validate this in build 6 when it comes out next weekend?  Thanks!
