### ISSUE TITLE
iOS: Detail view - on next unread, if we need to switch to a different feed/folder/account, don’t animate

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1174]
Even though we have to change the nav controller structure behind the detail view, the detail screen should appear to the user as if the only thing that’s happening is that a new article has appeared in the detail view.

**Comment by vincode-io** [comment]
Is it still bouncing out to the timeline and back into the detail view?  I thought I had that fixed in the latest build.

**Comment by brentsimmons** [comment]
Ryan seemed to imply that it was still. I’ll double-check.

**Comment by brentsimmons** [comment]
I’m on the TestFlight build, and it appears to be working as expected. I’ll check with Ryan.

**Comment by nostodnayr** [comment]
This is the title appearing above the timeline. On iPad in portrait orientation. It animated when switching between feeds, when using the next unread button.
