### ISSUE TITLE
Rotation on plus sized phones is inconsistent.

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#1177]
rotation seems a bit buggy on iPhone 8+ too; if i'm in a feed i'd expect it to show the feed in the right panel and the feeds list in the left, but it only shows the feeds list left. then when i rotate back to portrait, it's a the feeds list instead of the articles list

**Comment by vincode-io** [comment]
@Wevah I think I took care of your rotation bugginess.  If you could validate this, I would appreciate it.

**Comment by Wevah** [comment]
I can confirm that this is fixed.
