### ISSUE TITLE
iOS: Feeds list - use 32 x 32 pts icon for feeds

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1208]
Use the feed icon, instead of the favicon, when available. This way the icons on the feeds list and timeline match.

This is also fixes a problem where we have a 16 x 16 pixels favicon, which looks blurry on retina screens, but we have a feed icon, which will look great.

(This doesn’t fix the problem where all we have is a 16 x 16 pixels favicon. Not much we can do there.)

**Comment by brentsimmons** [comment]
It’s possible that, after seeing this, we’ll want to bump it down to 28 x 28 or 24 x 24. If so, we might want to exactly match that on the timeline, too.

**Comment by vincode-io** [comment]
32x32 looks big to me for the regular font size.

![Screen Shot 2019-10-28 at 8 40 51 PM](https://user-images.githubusercontent.com/16448027/67731157-4996bd80-f9c5-11e9-9233-c4ab31ec2f67.png)

Here is 24x24.

![Screen Shot 2019-10-28 at 8 44 33 PM](https://user-images.githubusercontent.com/16448027/67731173-54515280-f9c5-11e9-950f-bd2de094cb1b.png)

**Comment by brentsimmons** [comment]
Let’s stick with 24 x 24 for now. We’ll try it, and adjust later if it feels wrong.
