### ISSUE TITLE
iOS Feeds list: favicons are blurry

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1215]
A number of my feeds’ favicons appear blurry in NetNewsWire. Two examples:

* https://onefoottsunami.com/feed/atom/
* http://www.macdrifter.com/feeds/all.atom.xml

Both of these are Feedbin-synced feeds. 

I tried adding the Macdrifter feed to a local account which, perhaps predictably, resulted in a slightly different version of ugly.

In both cases, and perhaps all of my feeds, in other apps like Reeder the favicon appears as expected. 
<img width="163" alt="md-local" src="https://user-images.githubusercontent.com/2190735/67722884-bd64b480-fa1d-11e9-9ff8-f618b99c73bd.png">
<img width="173" alt="md-feedbin" src="https://user-images.githubusercontent.com/2190735/67722893-c2296880-fa1d-11e9-9df4-03d802c79963.png">

**Comment by brentsimmons** [comment]
Good catch — see https://github.com/brentsimmons/NetNewsWire/issues/1208 for the potential solution.
