### ISSUE TITLE
iOS: grid lines are visible in contextual menu/drag previews 

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1221]
Not sure if there’s anything that can be done about this, but it’s much more noticeable when using dark mode. 
<img width="437" alt="See articles in  “RadioToday”" src="https://user-images.githubusercontent.com/2190735/67905178-e159fe80-fbb3-11e9-8d66-9fd22ead32f2.png">

**Comment by vincode-io** [comment]
Those separators are annoying and now that you've pointed them out, I can't unsee them.  You can customize that preview to crop off the separators, but it is a bit of work.  This will have to wait until the more serious bugs have been resolved.

For future reference: https://kylebashour.com/posts/context-menu-guide
