### ISSUE TITLE
iOS: Feeds animations stutter on slower devices

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#1234]

**Comment by brentsimmons** [comment]
I’ve seen this with expand/collapse on the Feeds list on my iPhone X.

**Comment by vincode-io** [comment]
I tried a number of things today to try to fix this.  I profiled the app while doing the expand collapse animations and couldn't see anything we could improve.  Regardless, I tried a number of optimizations to see if they made an impact.

1. I cached the results of our layout so that it got processed less.  I didn't get a speed up, but I did start getting layout problems.
2. I removed everything except the disclosure triangle from the views.  Since there isn't a disclosure triangle on the feeds rows, I was basically expanding and collapsing empty rows.  I even made sure the row's opacity was false.  The animation didn't get any better.
3. I tried various layer speeds to if lowering it improved things.  Even at 1.1 it still stuttered.

What has me thinking we've hit some kind of cosmic speed limit for these older devices is how the swipe animations on the timeline were impacted.  These were operating on a single row and still stuttered at 1.1 layer speed.  Just to be clear, all animations were impacted by the layer speed changes, not just our expand and collapse.

I like the faster animations.  One thing we could do is check the device.  If you are an older device, you get 1.0 speed animations.  Otherwise, you get 1.5 or 2.0 animations depending on where we put the cutoff line at.

**Comment by brentsimmons** [comment]
Even if we checked the device, there might be other factors that could cause stuttering. (Something else could be using CPU, or not, at any given moment.)

Let’s keep it simple and go with the same speed on every device.

**Comment by vincode-io** [comment]
Should we leave it at 1.0 then?

**Comment by brentsimmons** [comment]
Yes.
