### ISSUE TITLE
iOS: Feed info sheet — context menu to copy home page and feed URL

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1239]
We need a way to copy the home page and feed URL from the feed info sheet.

I’m thinking a context menu on each of these fields, with command names “Copy Home Page URL” and “Copy Feed URL” in their respective spots.

But maybe there’s a better way to make it possible to copy these? I’m open to suggestions.

**Comment by vincode-io** [comment]
You now get the standard Copy menu item when you long press these labels.
