### ISSUE TITLE
iOS Import: No apparent result after import is complete

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1243]
After importing subscriptions, there's no confirmation that the operation was completed successfully. I'm not sure it's strictly necessary, but having nothing feels a bit cold. (I'd expect a dialog with 'n subscriptions imported' or perhaps a label placed to the right of the menu entry with a tick mark and Done, for example.)

**Comment by vincode-io** [comment]
This works the same as on the Mac app.  We utilize the progress bar to show the import progress and hide it when done.  You could file another feature request for this for both the Mac and iOS apps, but we won't be doing anything specifically in the scope of the iOS app.
