### ISSUE TITLE
iOS Detail view: iPad full screen button sticks around too long after transition

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1249]
When the full screen button is tapped, the view adjusts immediately, but the full screen button isn’t replaced with the Feeds back button until about a second later.

**Comment by vincode-io** [comment]
That's clunky, but I don't think there is anything I can do about this one.  It is an iOS thing.  If you notice in Notes, you have the same lag in that control when switching between fullscreen and split view.
