### ISSUE TITLE
iOS Detail View: navigation bar goes to dark mode after leaving app

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1250]
The navigation bar can slip into its dark mode state when the detail view is full-screen.

1. Tap an article to view it in the detail view
2. Tap the full screen button
3. Close the app
4. Reopen the app

**Comment by vincode-io** [comment]
I changed how the theming works earlier this week and it seems to have prevented this from happening.  You should be able to verify it in Build 6 coming this weekend.
