### ISSUE TITLE
Account column spacing for longer account names

### ISSUE THREAD

**Issue by Thomas-U** [brentsimmons/NetNewsWire#1253]
Account-column: Although Ecology...etc... is abridget, it takes 2 lines of space.

![6893ABEB-88AD-4119-A7DB-5AED7EAEB0E5](https://user-images.githubusercontent.com/171936/68167890-6e5fd780-ff67-11e9-927d-81ec7d33cf1c.png)

**Comment by vincode-io** [comment]
@Thomas-U What is that third word in the name of the Folder you are having problems with?  I can't tell because it is truncated.  

Is your text size set to XXXL?

**Comment by Thomas-U** [comment]
@vincode-io full name of account: Ecology - Nature - Garden

I see no option for text size in the NNW-settings. I iPadOS settings: see screenshot.

![Thomas_U iPad text size](https://user-images.githubusercontent.com/171936/68207817-14472c80-ffd0-11e9-9199-e76033e5d77e.jpeg)

I'll test now if things change with lower setting.

**Comment by Thomas-U** [comment]
iPad Pro 2018 11"

**Comment by Thomas-U** [comment]
Yes, slider one nudge lower gains full visibility and no second line.

**Comment by Thomas-U** [comment]
I had not touched system text size settings since iPadOS 13 upgrade.

**Comment by vincode-io** [comment]
I made a change to get rid of the extra blank line.  You should see the fix come through in Build 6 coming this weekend.  Thanks for your help on this @Thomas-U.
