### ISSUE TITLE
Emoji can be much larger than normal text

### ISSUE THREAD

**Issue by ardenott** [brentsimmons/NetNewsWire#1263]
In some articles with emoji, the emoji render quite large relative to the rest of the text. Example:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/56449717/68335409-a0715680-0099-11ea-8d33-2a1e93831392.png">

**Comment by brentsimmons** [comment]
It’s actually an image, in this case.

The img tag contains an inline style specifying height and width — but we strip out inline styles because they often interfere with Dark Mode. (Because they often specify a text color, which, if it’s dark, is unreadable in Dark Mode.)

This is a pickle!

**Comment by ardenott** [comment]
That’s fascinating. Is the website’s RSS feed serving images in this case? Because on the website itself it is definitely an emoji.

**Comment by brentsimmons** [comment]
In the feed, it looks like this:

`<img src="https://s.w.org/images/core/emoji/12.0.0-1/72x72/1f40d.png" alt=":snake:" class="wp-smiley" style="height: 1em; max-height: 1em;" />`

This looks like a Wordpress thing (note the class name). Ben Ubois has a good idea for how to deal with this: we could add, to NetNewsWire’s style sheet, a rule for `wp-smiley` sets the height.

**Comment by brentsimmons** [comment]
This should also go in iOS 5.0, of course.

**Comment by vincode-io** [comment]
Adding `.wp-smiley {height: 1em; max-height: 1em;}` to the stylesheet resolves this issue.

**Comment by Wevah** [comment]
I wonder if whitelisting a handful of attributes for inline styles might not be a terrible idea.

**Comment by Wevah** [comment]
I wonder if whitelisting some attributes might not be a bad idea. Might be more work than it's worth if the stripping isn't happening in JS, though.
