### ISSUE TITLE
iOS dark mode unlocking leaves top bar light

### ISSUE THREAD

**Issue by kenrachynski** [brentsimmons/NetNewsWire#1267]
I’ve have an iPad Pro and am using dark mode on iOS 13. 

I have a few instances now where I have an article full screen and the iPad locks up on idle. When I unlock the iPad, the article is still on screen, but NNWs top bar is light instead of dark. I can close NNW and on reopen, the top bar gets redrawn back to dark. Well, sometimes. I just went through the remainder of my current session with a light top bar. I had to go back to my feeds for the bar to reset.

**Comment by vincode-io** [comment]
Thanks for the bug report.  This has been fixed.  You should be able to validate this in the upcoming Build 6.
