### ISSUE TITLE
Missing favicons

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#1276]
https://www.jessesquires.com/feed.xml
https://geek-is-stupid.github.io/feed.xml
https://kayathomas.info/feed/
https://matteomanferdini.com/feed/
https://netsplit.com/feed/
https://lapcatsoftware.com/articles/atom.xml
https://www.youtube.com/feeds/videos.xml?channel_id=UCs-vWZu3t2ky3oImX83S_2Q
http://www.asymco.com/feed/

**Comment by Wevah** [comment]
Some of these appear to be fixed, but the jessesquires one is still busted. It looks like we need to either use the last `rel="icon"` or keep checking in order if we try to load one that doesn't exist.

**Comment by Wevah** [comment]
Safari's behavior seems to be:

Choose the first link with `icon` in the `rel` (rel is whitespace-delimited) that actually returns a valid image.

It also most likely follows the spec and uses the `types`, `media`, and `sizes` attributes, though we probably don't need to use all or any of those.

Note that `shortcut` appearing in the `rel` doesn't matter.

**Comment by Wevah** [comment]
If we're preferring `apple-touch-icon`s, I guess that'd need to be accounted for, too.

**Comment by Wevah** [comment]
Hm, Safari seems to actually download multiple sizes; maybe it creates a multi-representation image out of them?

**Comment by Wevah** [comment]
Working on this.

**Comment by Wevah** [comment]
https://lapcatsoftware.com/articles/atom.xml doesn't specify an icon and there's no `/favicon.ico` on the site, so that one still doesn't work.
