### ISSUE TITLE
iOS: Apostrophe Incorrectly Coded

### ISSUE THREAD

**Issue by finnito** [brentsimmons/NetNewsWire#1279]
Hi! I’m using the iOS beta 5.0 (6) and am seeing issues from the Daring Fireball feed with apostrophes not being encoded/decoded correctly.

It happens both in the article title and the body content.

![69F52D2B-B6A7-490A-B4D0-6F9469A02FD6](https://user-images.githubusercontent.com/6530078/68521991-4f689900-030b-11ea-9924-8479d0618c67.png)

![C5E0BB50-B223-420D-B5B6-F0BBFEC3ACAA](https://user-images.githubusercontent.com/6530078/68522011-79ba5680-030b-11ea-9aa3-9ce36212d769.png)

**Comment by brentsimmons** [comment]
It’s an issue with feed. I’m sure it’ll get fixed pretty quickly.
