### ISSUE TITLE
Option to not display unread items badge

### ISSUE THREAD

**Issue by Elzonor** [brentsimmons/NetNewsWire#1284]
It would be great if the badge could be hidden. People might want to hide the badge to be less distracted and less "forced" to open the app because of something new to read. 
<img width="207" alt="Schermata 2019-11-11 alle 13 04 01" src="https://user-images.githubusercontent.com/13104359/68585935-d771ae80-0483-11ea-9d31-3771919ac78b.png">

**Comment by nostodnayr** [comment]
There’s a setting in preferences for this. 🙂

**Comment by Elzonor** [comment]
OMG... it's true (of course)... thanks!
I swear that I have looked for it more than once! Has it been added recently? Just curious :)

**Comment by nostodnayr** [comment]
5.0.1, as I recall. So…a little while ago 😁

**Comment by Elzonor** [comment]
🤦‍♂️

**Comment by codemonkey85** [comment]
It looks like this feature isn't present on the iOS version. Is it planned for later?

**Comment by brentsimmons** [comment]
If you have NetNewsWire 5.0.3 for Mac, you should see an option for this in the Preferences.

**Comment by codemonkey85** [comment]
@brentsimmons I'm looking for this feature in the iOS version, not the macOS version. :-)

**Comment by brentsimmons** [comment]
Ah! Got it. You should be able to turn this off in system settings. In notifications for NetNewsWire, you can turn off Badges.

**Comment by codemonkey85** [comment]
@brentsimmons Gotcha. I was kind of hoping I wouldn't have to do that, in case the notification badges are used for other types of notifications (like how I can get notifications about new articles from certain feeds). But if that's not the case, then I might as well turn badges off at the system level.

Thank you!
