### ISSUE TITLE
Feedly: Missing articles when Feed added via web interface

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#1288]
I added some new feeds using the Feedly web interface.  After syncing, the new feeds appeared, but they didn't have any unread articles in them.  The web interface showed unread articles and the total unread article counts didn't match between NNW and the web interface.

After deleting and then adding the Feedly account again, the new feeds showed that they did have unread articles now in NNW.

**Comment by kielgillard** [comment]
The issue here is the last successful sync date is probably greater than the date of any of the articles in the added feeds. Since the Feedly API is only just giving us what we asked for, it isn't returning them to NNW, and the articles are never ingested.

**Comment by vincode-io** [comment]
It looks like this impacts any feed added from a source external to the device.  For example, I added an OPML file using iOS then synced on an older Mac Feedly account and got wildly mismatched unread counts on the Mac account.

**Comment by vincode-io** [comment]
Now that I've gotten some sleep, I realize this is the same way that Feedbin works too!

It might be nicer to retroactively go after articles when added from an external source, but it hasn't seem to be a problem thus far with Feedbin.  I'm closing this issue and if we get bug reports about it, we'll open tickets for both Feedbin and Feedly.
