### ISSUE TITLE
iOS: Expand view button missing on articles

### ISSUE THREAD

**Issue by kenrachynski** [brentsimmons/NetNewsWire#1291]
When starting up build 7 on my iPad, I selected my All Unread smart feed and went through a bunch of old messages. I got to one that I actually wanted to read without distractions and realized that I couldn't find the expand view button.

![UNADJUSTEDNONRAW_thumb_21a4](https://user-images.githubusercontent.com/867597/68703857-a1e2c900-0548-11ea-8da3-d59be49856ee.jpg)

The fix for this is simply to rotate the device and the button returns.

**Comment by vincode-io** [comment]
Thanks for the bug report.  The fix for this will be in Build 7.
