### ISSUE TITLE
iOS: unknown client error adding Feedly account

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1314]
When authorising a feedly account, this is returned:

{"errorCode":400,"errorId":"ap13int-sv2.2019111800.733678","errorMessage":"unknown client id"}

(Apologies if it’s not meant to be working yet.)

**Comment by kielgillard** [comment]
@brentsimmons I can send you the client id and secret for the next release. @vincode-io has them, too.

**Comment by brentsimmons** [comment]
@kielgillard Please do send them to me, along with instructions for where I need to put them so that they get properly added to the app.

**Comment by davidsomen** [comment]
Is it possible to get this information for my own testing?

**Comment by brentsimmons** [comment]
@davidsomen We need to keep the Feedly info very closely held. I have it only because I need to have to it in order to build the app.

Sorry about that! Obviously, in an ideal world, Feedly wouldn’t have this kind of restriction, but we respect them and their reasoning.

**Comment by davidsomen** [comment]
@brentsimmons Thank you for your response. I completely understand. I look forward to Feedly integration in the Mac app :)
