### ISSUE TITLE
macOS - macOS defaults to using Apple.News instead of NNW

### ISSUE THREAD

**Issue by georgesnow** [brentsimmons/NetNewsWire#1315]
I just recently had a peculiar issue happen. macOS refuses to let NNW handle RSS schemes anymore. Meaning this issue manifested itself and NNW use to handle RSS schemes. So this is strange to me. The only difference is I have had NNW open for a few days uninterrupted. 

I even checked SwiftDefault to confirm that NNW should be handling RSS schemes.
 Not saying this is a bug, but does anyone else have this issue? (and hopefully knows how to fix it)

NNW:5.0.3
macOS:10.15.1
and incase in mattes Apple.News: 5.2

![image](https://user-images.githubusercontent.com/12751441/69052335-c9b4af80-09d4-11ea-888c-2a3964b373f1.png)

**Comment by georgesnow** [comment]
update never mind...didn't realize the URL schemes is "feed" and "feeds". found that out by looking the plist.

**Comment by brentsimmons** [comment]
You should be able to set your default aggregator in NetNewsWire itself, in preferences.

If that doesn’t work, please let us know so we can reopen this bug. :)

**Comment by georgesnow** [comment]
Thanks. Still not sure why it switched, but it was an easy fix
