### ISSUE TITLE
iOS: Add Web Feed button disabled

### ISSUE THREAD

**Issue by boctor** [brentsimmons/NetNewsWire#1322]
1. Copy a feed URL to the clipboard.
2. Tap + to bring up Add Web Feed UI.

Expected:
Since the URL field is pre-populated, the Add button in the top right is enabled.

Actual:
Add button is disabled.

Workaround:
Any typing in the URL text field enables the text field

Notes:
Build 9

![netnewswire](https://user-images.githubusercontent.com/218705/69213744-dc84cc80-0b19-11ea-9187-b1713b2c41c0.jpeg)

**Comment by boctor** [comment]
In `AddFeedViewController`'s `viewDidLoad`, `delegate` hasn't been set yet, so `readyToAdd(state: true)` isn't invoked

**Comment by vincode-io** [comment]
Thanks for finding this bug and many thanks for debugging it!  This fix is in and will be in the next TestFlight release.
