### ISSUE TITLE
iOS: Today view shows items from previous day(s)

### ISSUE THREAD

**Issue by finnito** [brentsimmons/NetNewsWire#1323]
Items from the previous day are being shown in the today view.

![83C62887-D705-4F48-BA58-B6896D12A8C3](https://user-images.githubusercontent.com/6530078/69280834-0807d400-0c4c-11ea-9ce8-615192c28a2f.png)

iOS version 5.0 (9)

**Comment by brentsimmons** [comment]
The Today view is really the 24-hour view, by design. Sure, it might be weird that we call it Today. But we like it that way. :)
