### ISSUE TITLE
iOS: Feed images/labels aren't vertically centered for small text sizes

### ISSUE THREAD

**Issue by Wevah** [brentsimmons/NetNewsWire#1329]
The top margin is visibly smaller than the bottom margin at low text sizes. Probably a center-alignment constraint should be added?

![Simulator Screen Shot - iPhone 8 Plus - 2019-11-22 at 21 02 33](https://user-images.githubusercontent.com/130825/69472064-6ecfdf00-0d6b-11ea-8657-0aa841ac3273.png)

**Comment by Wevah** [comment]
The feed icons are properly aligned with the feed labels, but both aren't vertically centered in the table cells.

Disclosure triangle alignment seems correct related to the cell.

**Comment by vincode-io** [comment]
Fixed.
