### ISSUE TITLE
iOS/iPhone Detail View: bottom of view has untappable area

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1331]
(https://netnewswire.slack.com/archives/CPNED2D7Y/p1574482629304600)

Something is interfering with the tappable area at the bottom of the detail view, making links there untappable. 

See some of the link posts in `https://daringfireball.net/feeds/json` for an example:

![df-tappable](https://user-images.githubusercontent.com/2190735/69473300-a33cad00-0df6-11ea-8e19-8169d48f465b.png)

iPhone X, iOS 13.3

**Comment by happycollision** [comment]
I noted this earlier (by mistake in the Slack channel). I have also noticed that small links (few characters) seem to be rendered completely unusable.

**Comment by vincode-io** [comment]
The tap zones only appear when in fullscreen mode now.  This fix will be in the next TestFlight release.

@happycollision if you have another bug you would like to report, please open an issue for it.  An example feed and article would be considered very helpful.
