### ISSUE TITLE
iOS: Not all timeline previews are truncated by an ellipsis

### ISSUE THREAD

**Issue by nostodnayr** [brentsimmons/NetNewsWire#1333]
There’s something causing inconsistency in the truncating ellipses in the timeline. Hunting for a pattern again today, I discovered the Daring Fireball feed demonstrated this, and differently between screen sizes.

Note that the item titled *Cook: ‘China Really Hasn’t Pressured Us’* has an ellipsis on iPad, but not iPhone.

Both of these are using the default local subscription list, subscribed to `https://daringfireball.net/feeds/json`.

iPad – iOS 13.2.3
![IMG_13EECB0B9C62-1](https://user-images.githubusercontent.com/2190735/69486859-f153be00-0e93-11ea-8401-0e847737e021.jpeg)

iPhone – iOS 13.3
![IMG_F68B14421D47-1](https://user-images.githubusercontent.com/2190735/69486863-fa448f80-0e93-11ea-89a4-ffc90da8735c.jpeg)

**Comment by vincode-io** [comment]
This has been fixed and will be resolved in the next TestFlight build.
