### ISSUE TITLE
iOS: Deactivating account from context menu causes collapsed toggle states to be lost

### ISSUE THREAD

**Issue by philviso** [brentsimmons/NetNewsWire#1346]
The rules for what trigger this seem to be a bit tricky, but here's a case I found that always reproduces it.

1. Create two local accounts and make sure each account has some feeds
2. Collapse account 1, and expand account 2 - something like this...

![Simulator Screen Shot - iPhone 8 - 2019-11-24 at 09 29 51](https://user-images.githubusercontent.com/347423/69496918-fa955880-0e9c-11ea-9b57-347323f04346.png)

3. Deactivate account 2 (favorites) via the context menu

After account 2 is deactivated, account 1 ends up getting re-expanded

**Comment by vincode-io** [comment]
Thanks for the bug report. This is a side effect of storing view state with the Nodes in the TreeController.  I will come up with a better strategy for storing view state.

**Comment by vincode-io** [comment]
Fixed in the repo.
