### ISSUE TITLE
Feedly: Dragging a feed to a collapsed folder results in error

### ISSUE THREAD

**Issue by good** [brentsimmons/NetNewsWire#1356]
Dragging a feed from one folder to another will often result in an error if the destination folder is collapsed. If it's expanded, this never errors. 

The error says "**Error** Please choose a folder to contain the feed."

This happens most of the time I try it, but not every single time. I'm still trying to determine a pattern.

![Screenshot](https://user-images.githubusercontent.com/6645/69661670-ab375f80-1037-11ea-8a0d-9b9e577219f2.png)

**Comment by vincode-io** [comment]
I fixed this problem, but it exposed another one in Feedly.  I'll write up a separate issue for it.
