### ISSUE TITLE
Support IPv6 literal URLs

### ISSUE THREAD

**Issue by aredridel** [brentsimmons/NetNewsWire#1382]
Trying to add `http://[303:60d4:3d32:a2b9::4]/rss` to NNW and the Add button doesn't light up.

**Comment by Wevah** [comment]
Looks like we're only checking for `.` in the string and not `:`.

**Comment by Wevah** [comment]
Adding `:` to the check works, but then of course it also allows `http://nothing`. Still better than not allowing an IPv6 address, though!
