### ISSUE TITLE
iOS: bottom toolbar says "Updated just now" with no internet connection

### ISSUE THREAD

**Issue by sh4338** [brentsimmons/NetNewsWire#1383]
When refreshed without an internet connection, the toolbar will still say the refresh was the last refresh -- even though it could not load new articles.

**Comment by vincode-io** [comment]
@brentsimmons Right now this field is just checking a field that specifies when the last attempt was made and doesn't contain any useful information about success or failure.

We do have a per account field that specifies the last successful attempt server time.  We don't currently use it for local accounts, but that could be changed.  To use it we would need to decide which account date to use.  The most current successful attempt seems the best solution to me.

Thoughts?

**Comment by brentsimmons** [comment]
Agreed — we should use the most current successful attempt.

**Comment by vincode-io** [comment]
I had to add another field to the account metadata.  The field I referenced earlier was the last fetch start time which isn't what users would have expected.  We now have both article fetch start and article fetch end times as account metadata.
