### ISSUE TITLE
iOS: Make sure extensions are utilizing database resources correctly

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#1427]
See this tweet https://twitter.com/groue/status/1203893850386976774?s=20 that references this document https://github.com/groue/GRDB.swift/blob/dev/dead10cc/Documentation/AppGroupContainers.md#use-a-database-pool

**Comment by groue** [comment]
Hello,

This search for proper use of SQLite databases shared in an App Group container is part of a work-in-progress, which is not completed yet. The document above is part of the draft pull request https://github.com/groue/GRDB.swift/pull/663. This PR is part of a "plan" roughly described in https://github.com/groue/GRDB.swift/issues/643#issuecomment-560014034.

So far, GRDB is able to avoid crashes in *applications*. In extensions, nothing is quite settled yet.
