### ISSUE TITLE
Links and images not rendered with feed.xml

### ISSUE THREAD

**Issue by adamprocter** [brentsimmons/NetNewsWire#1445]
When I subscribe to this feed https://discursive.adamprocter.co.uk/categories/phd/feed.xml then I get no links or images but the main link https://discursive.adamprocter.co.uk works fine links and images are clickable and appear but is then not filtered to the category. Not sure if this is NNW or MB

**Comment by brentsimmons** [comment]
NetNewsWire is showing what’s in the feed — the description elements are short, and all the ones I checked contain no HTML.

**Comment by adamprocter** [comment]
What I mean is that one displays links and photos and the other doesn’t. But it’s the same post. 

When subscribing to feed.xml
![670B6056-7CBC-494E-B330-C3856E698A0F](https://user-images.githubusercontent.com/123951/71319012-5ea53f80-2490-11ea-9961-e44c79b16a5d.png)

When subscribing to main link
![A5FDC51F-E492-47FD-BA90-5AE14615B359](https://user-images.githubusercontent.com/123951/71319022-72e93c80-2490-11ea-8489-bdc25b5ad4e2.png)

**Comment by Wevah** [comment]
The main link provides different a different feed links than the one in your first post: The `categories/phd` feed doesn't have the entire post content, but the main feed does, so it's an issue with whatever's creating the feeds (Micro.blog AIUI).

**Comment by adamprocter** [comment]
Cool thought it might be have made @mantonreece aware
