### ISSUE TITLE
iOS some images on the rss screen are smaller then they should

### ISSUE THREAD

**Issue by iAmericanBoy** [brentsimmons/NetNewsWire#1447]
Edit: this is on the TestFlight build 5.0(23)

On the unread articles screen. It looks like the points guy rss image is much smaller then the other rss images. 
![CD89D146-DF11-49D3-BB57-AE20F929C640](https://user-images.githubusercontent.com/32912858/71328184-e9ae2600-24e0-11ea-9cc2-3532c9c2595d.png)

**Comment by Wevah** [comment]
Looks like whatever icon we're grabbing from the site has a ton of empty space.

(For others' reference, site URL is https://thepointsguy.com/)

**Comment by Wevah** [comment]
Which build of NNW are you running? I could reproduce this until I installed the latest build.

**Comment by Wevah** [comment]
Hm, I got it to show the correct Icon when I rebuilt and reinstalled, but now it's showing the bad one when I re-add the feed.

**Comment by Wevah** [comment]
The favicon downloader is finding and downloading the correct icon as far as I can tell, but it's not being propagated to the UI for some reason.

**Comment by Wevah** [comment]
Ah, here's the issue: The iOS version prioritizes `apple-touch-icon`s, and somewhere the site is specifying this one: https://i2.wp.com/thepointsguy.com/wp-content/uploads/2019/10/fallback_image-new-ui-logo.jpg?fit=1280%2C1280px&ssl=1

**Comment by brentsimmons** [comment]
`og:image` is usually a good choice for a larger icon. Just not in this case.

**Comment by brentsimmons** [comment]
What we should probably do is check that the feed icon is actually larger than the favicon. If not, then use the favicon.

**Comment by Wevah** [comment]
The feed icon is larger in this case, it's just got a ton of whitespace in the image and so looks bad.

**Comment by brentsimmons** [comment]
Ah. Good point.

We shouldn’t be spending cycles on checking for whitespace. At some point, it’s just a bug that the publisher is responsible for.
