### ISSUE TITLE
iOS: Article view — tap on disabled arrow triggers fullscreen mode

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1450]
If you go through your feeds by tapping the down arrow till you get to the end, eventually you tap on a disabled down arrow — which has the effect of going fullscreen instead of going to the next article.

This could come as a surprise, especially to someone who doesn’t know about the fullscreen feature.

Instead, tapping on a disabled arrow should do nothing.

**Comment by vincode-io** [comment]
The tap zone is now the center of the navigation bar instead of the whole bar.
