### ISSUE TITLE
iOS: Article list remains empty after adding web feed

### ISSUE THREAD

**Issue by NorbertLindenberg** [brentsimmons/NetNewsWire#1451]
NetNewsWire 5.0 (23) on iOS 13.3 on iPad mini 5:

I’m getting an empty article list after adding the web feed
https://lindenbergsoftware.com/all.atom

NetNewsWire 4.1.0 shows 7 articles for the same feed.

**Comment by brentsimmons** [comment]
Using Feedbin, Feedly, or no syncing?

**Comment by brentsimmons** [comment]
Superseded by #1458.
