### ISSUE TITLE
iOS: "Export Subscriptions" doesn't do anythings unless "Import Subscriptions" is selected first

### ISSUE THREAD

**Issue by idunno101** [brentsimmons/NetNewsWire#1457]
[Screen recording of issue](https://streamable.com/xqn92)
Steps
1. Go into settings
2. Tap "Export Subscriptions" --> no response
3. Tap "Import Subscriptions" then tap cancel
4. Tap "Export Subscriptions" again --> show the file menu
iPhone SE iOS 13.3

**Comment by vincode-io** [comment]
Thanks for the bug report!  The fix for this will be in the next release.
