### ISSUE TITLE
Fix layout of code with some feeds

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#1459]
https://blog.emberjs.com/feed.xml

![Image from iOS](https://user-images.githubusercontent.com/1297121/71387146-47a54100-25a7-11ea-9225-911f99c88a3b.png)

**Comment by Wevah** [comment]
The code blocks are rendering super-huge.

**Comment by vincode-io** [comment]
This one has me stumped for now.  The problem seems to be that the `pre` tags are embedded in a `table`.  It looks like all the CSS attributes in the `pre` tag that exceeds the width of the page are ignored, including font.

The closest thing I could come up with for a fix is this:

`td > pre {
	white-space: pre-line;
}`

This forces offending `pre` block to wrap when in a `td`.  The styling no longer seems to be lost in this case, but we then have line wrapping which isn't  a desired behavior.

**Comment by Wevah** [comment]
Does adding `overflow: scroll` anywhere help?

**Comment by vincode-io** [comment]
We are already using `overflow: auto` on the `pre` elements.

**Comment by Wevah** [comment]
Gotcha. FWIW, the font is the correct size and wraps on `mac-release`.

**Comment by vincode-io** [comment]
Yeah, the CSS to do the `overflow: auto` behavior was added to the Mac 5.1 version.  Looking at `master` for the Mac, the `pre` block isn't correct, but at least the line numbers line up and the font is correct.

**Comment by Wevah** [comment]
I've got a partial fix that does 2 things:

1. Adds `initial-scale=1` to the `meta name="viewport` tag (fixes initial zoom).
2. Adds `-webkit-text-size-adjust: none;` to the iOS style sheet (fixes the huge font size).

Another option would be to use JS to add a wrapper `div` with `overflow-x: auto` around any `table`s.

**Comment by Wevah** [comment]
Of course, this fix means the whole feed scrolls horizontally instead of just the code table; test it out and let me know what you'd prefer.

**Comment by Wevah** [comment]
Actually, I think this PR should probably go in (if it doesn't break other stuff) whether we end up wrapping `table`s or not.

**Comment by vincode-io** [comment]
@Wevah That PR helped immensely.  Do you want to try the JS wrapped `DIV` with overflow to see how that works.  I think it would probably help in other situations where we have large tables as well.

**Comment by vincode-io** [comment]
@Wevah Nice work!
