### ISSUE TITLE
iOS: full screen article view -- unable to navigate 

### ISSUE THREAD

**Issue by sashkab** [brentsimmons/NetNewsWire#1460]
I've enabled full screen view for article and.. unable to figure out how to get to the next/previous article: 

* swipe right/left doesn't work;
* press on right/left edge -- doesn't work;
* swipe up/down doesn't work either. 

I would say having navigation icons in top right corner isn't very friendly either when used without full screen article view. some kind of swipe/press on screen should help

**Comment by vincode-io** [comment]
In full screen you can get a context menu that has navigation buttons by long pressing anywhere there isn’t a link in the article. We are investigating adding navigation gestures. We are trying to figure out what best matches the current design.

**Comment by sashkab** [comment]
> long pressing anywhere there isn’t a link in the article

this is too long, imho. plus animation feels too annoying after the first couple times. 

I understand that gestures somewhat hard -- you already use swipe from left edge for going back to previous screen.  But something is needed. I love full screen, but navigation issues kills it.

**Comment by curtismchale** [comment]
How about a keyboard command to toggle full screen on/off as well. Using this on 12.9” iPad Pro in split with a writing app and the reading column by default is crazy small but it’s okay for skimming the feeds to see what I actually want to read. Then being able to jump into full screen on the article of choice would make the whole process easier.

**Comment by paulpalinkas** [comment]
I’d like a gesture for toggling full screen preview on/off. Pinch out is what I tried first, double tap also seems logical. I’m on a larger iPad, reaching to the top is not pleasant. I seem to want to toggle this view frequently, for what it’s worth.

**Comment by vincode-io** [comment]
We've implemented left and right swiping to navigate articles.  We are still testing this feature, but it will be available in a future release.  (It won't be available in the upcoming release)

**Comment by vincode-io** [comment]
@curtismchale and @paulpalinkas, please open separate feature requests for the things you want to see.  This ticket has been resolved and isn't related to the features mentioned above.  Thanks for your help!
