### ISSUE TITLE
iOS: issue with Indiepaper feed

### ISSUE THREAD

**Issue by roelwillems** [brentsimmons/NetNewsWire#1461]
I'm using Indiepaper as an alternative to Instapaper and have the Indiepaper feed within Feedbin.

Currently I do see 53 items in my Indiepaper feed within the web environment of Feedbin (and within Unread RSS reader on iOS). 

![image](https://user-images.githubusercontent.com/1217719/71416076-3ddf1480-265f-11ea-860d-7bf0188da543.png)

But within NetNewsWire iOS I only see 1 feed item shown.

![IMG_0055](https://user-images.githubusercontent.com/1217719/71416148-94e4e980-265f-11ea-8ffb-9e1255294f2b.PNG)

**Comment by vincode-io** [comment]
@brentsimmons I think we have an unread count mismatch here because `fetchArticleIDsForStatusesWithoutArticlesNewerThanCutoffDate` has a cutoff date.

**Comment by vincode-io** [comment]
@roelwillems Do you have this problem with the latest release?

**Comment by roelwillems** [comment]
Hi @vincode-io I've just updated to Version 5.0 (24) and the feed count is showing the correct number of unread items. So all is working and I guess this topic can be closed.

Thanks for the support!

**Comment by vincode-io** [comment]
Thank you for getting back to us. I’m glad we got it working for you.
