### ISSUE TITLE
iOS: Missing unread articles when syncing with Feedbin

### ISSUE THREAD

**Issue by paulrobertlloyd** [brentsimmons/NetNewsWire#1469]
Been using the iOS beta for a couple of days, and unread counts have been consistently incorrect. The macOS app remains in sync with Feedbin, however. 

## Feedbin

Unread: 21
‘Links’ tag: 18
‘People’ tag: 3 

<img width="278" src="https://user-images.githubusercontent.com/813383/71447959-b3b1b180-272d-11ea-81df-e7bb8540c83f.png">

## NetNewsWire 5.0.3 (macOS)

Unread: 21
‘Links’ tag: 18
‘People’ tag: 3 

<img width="210" src="https://user-images.githubusercontent.com/813383/71447964-c0360a00-272d-11ea-9700-02ddfaca633a.png">

## NewNewsWire 5 Public Beta (iOS)

Unread: 8
‘Links’ tag: 8

<img width="320" src="https://user-images.githubusercontent.com/813383/71447978-d3e17080-272d-11ea-8117-5c95903bf084.PNG">

**Comment by paulrobertlloyd** [comment]
Possibly a duplicate of #1461.

**Comment by vincode-io** [comment]
@paulrobertlloyd Did the latest release resolve this issue for you?

**Comment by paulrobertlloyd** [comment]
@vincode-io I suspect so. With the new version installed, the items that previously weren’t appearing showed up in the app (even though they had since been marked as read in FeedBin). Does that sound right? Happy to close and reopen this issue if I see this occur again.

**Comment by vincode-io** [comment]
Thanks. I’m closing this issue. Let us know if it comes back.
