### ISSUE TITLE
iPad: content pane horizontal scroll-bounce

### ISSUE THREAD

**Issue by gerwitz** [brentsimmons/NetNewsWire#1472]
On iPad, the content pane allows horizontal scrolling despite a layout that fits the view. So when scrolling vertically, it is very easy to also “bounce” left and right.

(I will collect my award for most pedantic issue later, thanks.)

**Comment by vincode-io** [comment]
We recently changed article viewer implementation to change articles when swiping left or right.  This means if you are swiping diagonally, you are going to begin to pull the next or previous article into view.

I'm sorry, but I don't think we will be able to eliminate the horizontal bounce.

**Comment by Wevah** [comment]
I'm not sure if it's actually trying to go to the next/previous article. I don't have a new enough iPad to test, but on iPhone trying to scroll diagonally just scrolls vertically and doesn't start the next/previous action.

**Comment by gerwitz** [comment]
Indeed, the iPhone and iPad 3-pane behavior is perfect, it’s only the iPad 2-pane view that allows horizontal and diagonal scrolling.

If left/right swipes navigate through the list, that’d be preferable as well. This thread has helped clarify: what bothers me is that vertical scrolls with even a little diagonal movement cause this bounce.
