### ISSUE TITLE
importing OPML files results in duplicate feeds

### ISSUE THREAD

**Issue by heckj** [brentsimmons/NetNewsWire#1479]
With the recent beta of IOS, I've repeatedly imported my OPML feeds. The result is that some feeds (top level) have been replicated so that there are duplicates. (Inessential, DaringFireball, Michael Tsai, and ShapeOf - but not all of the others)

Underlying feeds have generally been fine and not been duplicated but some of the top level items are being replicated.

**Comment by vincode-io** [comment]
@heckj If you haven't deleted the duplicates yet, could you check the Feed URL of the duplicated feeds?  I'm wondering if they are different between the dup's.  Are you using a sync service?

**Comment by heckj** [comment]
For the duplicate of Brent's feed (inessential):

- home page: `https://inessential.com`
- feed url: `http://inessential.com/feed.json`

And in the second one:

- home page: `https://inessential.com`
- feed url: `https://inessential.com/feed.json`

In my OPML exported from NNW (Mac) the XML stanza is the version with `http`:
```
<outline text="inessential" title="inessential" description="" type="rss" version="RSS" htmlUrl="https://inessential.com/" xmlUrl="http://inessential.com/feed.json"/>
```

So I'm guessing it's getting converted/normalized, and the slight http vs https mismatch is what's accounting for the visual duplicatation

**Comment by brentsimmons** [comment]
NetNewsWire does strict matches for feed URLs. If they’re different — even just by http vs. https — then it treats them as different feeds.

**Comment by heckj** [comment]
Makes sense - I think the underlying issue (haven't tracked down the code) is that somewhere in there, the feed URLs are normalized and changed, and not preserved exactly on import, which is what's generating the duplicates for a few of these critters.

**Comment by vincode-io** [comment]
@heckj if you are using either Feedbin or Feedly, they may change the preferred feed url.

**Comment by heckj** [comment]
Doh! i’m just being stupid. i was deleting them built in default, and then seeing the duplicate because my opal has http in it, not https. i thought the normalization was happing in NNw, but it’s just my feeds.
