### ISSUE TITLE
Can’t add folders

### ISSUE THREAD

**Issue by billbennettnz** [brentsimmons/NetNewsWire#1482]
The command is there, but it doesn’t function.

**Comment by vincode-io** [comment]
Could you please provide us with some details of what you are trying to do?  Are you using the macOS or iOS app?  Are you using a sync service?  A screen shot of the exact button that you are trying to press would also be very helpful.

**Comment by billbennettnz** [comment]
Sorry, didn’t realise this wasn’t iOS specific and probably wasn’t paying enough attention when the original problem occurred.

Using iOS on an iPad. 

This was immediately after installing software. 


Hit the + button at the bottom of the left hand panel.

Choose Add Folder. Enter name. 

Now I try to replicate the problem it works just fine. As you can see from the screenshot the button is now active.

![66F10A9C-1B42-4A92-97F5-33A82DB9D9E0](https://user-images.githubusercontent.com/5514395/71550095-418ee480-2a2d-11ea-9b56-87ac4e77febf.jpeg)

Have tried to repeat the problem two or three times and it isn’t happening now. If I see it again will report back.

**Comment by vincode-io** [comment]
Thanks for the detailed write up!  Since we can't recreate the problem right now, I'm going to close this issue.  If it happens for you again, just reply to this issue.  I'll open it again and investigate.
