### ISSUE TITLE
[IOS] Add settings that Users can set how often to refresh

### ISSUE THREAD

**Issue by 97wow** [brentsimmons/NetNewsWire#1498]
Add settings
Users can set how often to refresh
For example, every 1 minute, every 10 minutes, every 20 minutes.

**Comment by brentsimmons** [comment]
The problem is that the system controls how often a background refresh happens, and we don’t know how it decides, and we have no control over it.

**Comment by 97wow** [comment]
Thanks for your answer, thanks very much.
So, will this feature be added in the future? After all, similar programs already have this feature.

**Comment by brentsimmons** [comment]
The system won’t let us control how often a background refresh happens, so we can’t add the feature.
