### ISSUE TITLE
Recommended adding features

### ISSUE THREAD

**Issue by 97wow** [brentsimmons/NetNewsWire#1499]
Recommended adding features
While browsing the article, continue to swipe up to view the next unread article without having to click "Next unread article".
Similarly, continue to scroll down to view the last read article.

**Comment by vincode-io** [comment]
The team has decided that we will most likely be adding left/right swiping gestures to navigate through articles instead of continued scrolling.  This is being implemented as issue as #1460.  I'm going to close this issue as it is similar to that one.
