### ISSUE TITLE
Delete should be at the bottom of the context menu. 

### ISSUE THREAD

**Issue by jaredrkozar** [brentsimmons/NetNewsWire#1503]
Delete should be at the bottom of the context menu, like how it is in other apps such as Safari. It’s currently in the middle. 

![D601B561-90B9-4F88-A3E5-11AE9DA79775](https://user-images.githubusercontent.com/59402943/71637168-90de3c00-2c0a-11ea-9995-b273988754d4.jpeg)

**Comment by hartlco** [comment]
Would love to take this one over!

**Comment by vincode-io** [comment]
This has been changed.  Coming soon to a release near you!
