### ISSUE TITLE
Font size 

### ISSUE THREAD

**Issue by adamprocter** [brentsimmons/NetNewsWire#1508]
Would be good if iOS had an setting to adjust font size

**Comment by vincode-io** [comment]
The app is dynamic type compliant. You can adjust the font size in the iOS accessibility settings.  We do have a feature planned in the future that will let you customize the article styling. Look for that in a future release.

**Comment by adamprocter** [comment]
Thanks.  I have bumped the text size overall up to a size I like but I find that in NNW it is still too small for me. Article styling would address that of course.
