### ISSUE TITLE
Sample AppleScript scripts

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#155]

**Comment by brentsimmons** [comment]
Where do we put these? How do users find them?

**Comment by brentsimmons** [comment]
We’re going to put these as a download on the website, which means it can be done for the beta milestone.

**Comment by olofhellman** [comment]
Any guidance on where sample scripts should go in the repo?

**Comment by brentsimmons** [comment]
I just created an AppleScript folder for these. 👍

**Comment by brentsimmons** [comment]
I think we have a nice collection now. We can always make more in the future.
