### ISSUE TITLE
Needs documentation: NetNewsWire can't update app from ~/Downloads

### ISSUE THREAD

**Issue by ttepasse** [brentsimmons/NetNewsWire#213]
![bildschirmfoto 2017-11-28 um 11 30 51](https://user-images.githubusercontent.com/118031/33315054-d64e6984-d42f-11e7-9627-c88ad7450347.png)

While one can understand not running from disk images, etc, the Downloads folder is neither read-only nor an image or optical drive. Small thing in the the grand scheme of things, of course, but confusing.

Moving Evergreen to a sub-folder of /Applications worked.

**Comment by ttepasse** [comment]
Ah. Nevermind. I updated Evergreen from 1.0 d17 to 1.0 d20 and tested again and it worked in ~/Downloads.

**Comment by clausTue** [comment]
innocent question from a beginner: how / from where would I download 1.0 d20?

**Comment by ttepasse** [comment]
@clausTue I used the builtin Updater. You could download d18 and update, I think:
https://twitter.com/evergreen_mac/status/933083660290473984

**Comment by clausTue** [comment]
thanks! I have it running now. Nice.
However, I still get the same update error as described above, even when I run it from `~/Applications` (not `/Applications`)

**Comment by ttepasse** [comment]
Aside: I just tested, and as @clausTue notices the issue is still there:

• I downloaded d18 in `~/Downloads`.
• I unzipped d18.
• I started d18 from `~/Downloads`.
• I started „Check for Update“.
• I got the same error.

Weirder:
• I quit Evergreen, restarted and checked for updates. Same error.
• I dragged the app to another Folder, `~/Movies` in this case because the window was open.
• I started Evergreen from `~/Movies`.
• Check for Updates: No Error.

Then I got creative, guessed the URL for d20 ( https://ranchero.com/downloads/Evergreen1.0d20.zip ) and repeated the same procedure:

From `~/Downloads` → Error
Copied to `~/Applications` → No Error.
Copied back to `~/Downloads` → No Error.

**Comment by brentsimmons** [comment]
This is an Apple thing — Gatekeeper Path Randomization, aka app translocation.

https://lapcatsoftware.com/articles/app-translocation.html

What should probably happen is that Evergreen detects the situation and then offers to move itself to /Applications.

**Comment by brentsimmons** [comment]
Well, Evergreen can’t move itself and thereby fix the situation. The user has to move the app.

So Evergreen should detect the situation, then explain it to the user and suggest they move the app manually.

**Comment by brentsimmons** [comment]
See <Security/SecTranslocate.h>.

**Comment by brentsimmons** [comment]
Apparently this also means (I’ve heard) not switching to the latest Sparkle, because it will just crash in this situation.

**Comment by brentsimmons** [comment]
This is a documentation issue. There isn’t anything we can do about the underlying issue.
