### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#246]
Needs design.

**Comment by venkatasg** [comment]
Does this design also include turning off the unread count badge in the dock icon? NetNewsWire does not show up in System Preferences -> Notifications. I'd really like to turn that off, like I do in so many other apps since it just gives me anxiety to check.

**Comment by simgust** [comment]
Yes, I’d also love to be able to turn off the unread badge on the dock icon!

**Comment by hjallehallin** [comment]
I would love to be able to pick what number to show in the badge, i.e only the unread count in the Today smart feed.

**Comment by vincode-io** [comment]
For Mac 5.1 we have per feed notifications available.  You will also be able to disable the badge count in notifications and via a checkbox in NNW preferences.
