### ISSUE TITLE
Character encoding issue in middle pane

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/NetNewsWire#279]
git @ 1d2d048

feed://www.vvv.gov.gr/index.php/what-we-do/news-releases?format=feed

![screen shot 2017-12-27 at 12 33 08](https://user-images.githubusercontent.com/227442/34379252-02b32fca-eb03-11e7-8d3e-ab4934589233.png)

**Comment by brentsimmons** [comment]
Can’t actually find the feed. Will reopen if we get a reproducible test case.
