### ISSUE TITLE
Make frameworks build for iOS

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#317]
We should still be able to import using the names we use on macOS. For instance, @import Data should work for both platforms.

The frameworks that should build for iOS are:

Account
Data
Database
DB5
RSCore
RSDatabase
RSFeedFinder
RSTextDrawing
RSTree
RSWeb

RSParser too, but that has its own ticket on the RSParser repo: https://github.com/brentsimmons/RSParser/issues/1

**Comment by danielpunkass** [comment]
I think we might wait until #318 is closed, since adopting the changes that make this happen will involve build setting changes that would be easier to review and track in .xcconfig files than in .pbxproj files.
