### ISSUE TITLE
Don't show utm junk in status bar URL

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#33]
But still actually use the utm junk when opening the URL in the browser.

**Comment by brentsimmons** [comment]
If a link has ?utm= junk in it, don’t show that junk in the status bar when mousing over a link. Show a clean URL instead.

**Comment by vincode-io** [comment]
I'm trying to find a test feed for this and not having any luck.  Is there one you could share with me?

**Comment by brentsimmons** [comment]
I’ll look and see if I can find one.

It’s possible we’re already doing this and I just forgot. :)

**Comment by vincode-io** [comment]
I don't see any code to handle weird query strings.

**Comment by brentsimmons** [comment]
I can’t find any feeds that do this. It may be that it’s not really a thing any more?

Dealing with feedproxy.google.com will have to be made a bug. But that’s a different issue (requires resolving the URLs and storing them in a dictionary).

**Comment by vincode-io** [comment]
Yeah, I don't think UTM is a thing anymore. https://en.wikipedia.org/wiki/Urchin_(software)  It looks like they stopped selling it in 2012.

**Comment by brentsimmons** [comment]
I haven’t seen any weird URLs in feeds, so I’m closing this. We can reopen it if we spot anything.

**Comment by pdokas** [comment]
FWIW, `utm_foo` query params are still used and recommended by Google across their analytics systems. Here’s some modern docs about their usage: https://support.google.com/analytics/answer/1033863
