### ISSUE TITLE
Feature request: images of article in notifications and feed list

### ISSUE THREAD

**Issue by matiasperaltt** [brentsimmons/NetNewsWire#3319]
hello.  I wrote this request a while ago but had no comment.  and recently I saw someone else asking for the exact same thing.  Could you tell me if there are plans to do the following?  images in the notifications (small icon, photo 1) images when long press in the notification (photo 2) and images in the news reading feed list (photo 3)

Photo1
![image](https://user-images.githubusercontent.com/17476091/137142829-39dd36b6-6893-4a35-b54e-ca7d11ade3d1.jpeg)

Photo2
![image](https://user-images.githubusercontent.com/17476091/137142860-cdc33cb8-5325-484d-b563-a0a86fe0d950.jpeg)

Photo3
![image](https://user-images.githubusercontent.com/17476091/137142891-47e2e582-ef80-4007-ba1f-8d374d6ee7bc.jpeg)

Old request 

https://github.com/Ranchero-Software/NetNewsWire/issues/3126

**Comment by melwan** [comment]
Now that article theming is nearly done, can you please take a look at this next? It helps those visual folks skim through articles 👍🏻
