### ISSUE TITLE
One of the drag images for multi-article drag is mislocated

### ISSUE THREAD

**Issue by danielpunkass** [brentsimmons/NetNewsWire#358]
When multiple items are selected and dragged from the timeline, the top-most item is drawn in a mislocated position. 

<img width="921" alt="screen shot 2018-03-05 at 2 07 10 pm" src="https://user-images.githubusercontent.com/14606/36997658-5cad4b68-2088-11e8-96f8-cee7aef22c82.png">

**Comment by danielpunkass** [comment]
I have determined so far while researching this bug that the drag items generated by NSTableView contain reasonable image locations, but after the drag leaves the table, the dragging item generated for the problematic item has  garbage "frame" origin. Notice the frame has an x offset of 5.262549580079045e-310:

 <NSDraggingItem: 0x0x606000f8fba0> item:<NSPasteboardItem: 0x6040000fdc10> draggingFrame:{{678.13671875, 253.58810763888891}, {200, 39.111111111111114}} components:(
    "<NSDraggingImageComponent: 0x0x606000f8fc00> key:icon frame:{{5.262549580079045e-310, 0}, {200, 39.111111111111114}} contents:<NSImage 0x60600008eb20 Size={450, 88} Reps=(\n    \"NSBitmapImageRep 0x6080001b8ea0 Size={450, 88} ColorSpace=Color LCD colorspace BPS=8 BPP=32 Pixels=900x176 Alpha=YES Planar=NO Format=0 CurrentBacking=<CGImageRef: 0x6110015f7ec0>\"\n)>"
)

**Comment by brentsimmons** [comment]
That’s just weird.

**Comment by brentsimmons** [comment]
This appears to have been fixed. Was probably a system bug.
