### ISSUE TITLE
[feature request] Support for RSS favicon syntax 

### ISSUE THREAD

**Issue by YangY-one** [brentsimmons/NetNewsWire#3625]
According to the [RSS 2.0 Specification](http://cyber.law.harvard.edu/rss/rss.html#optionalChannelElements), the favicon can be specified using the optional sub-element `image`. This would be useful for some websites with different RSS. 

However, it seems that NetNewsWire will ignore the favicon declaration and use the website's favicon. 

Is it possible to make a simple judgement that the website's favicon is only used by default if the `image` element missing

**Comment by brentsimmons** [comment]
These images are almost never square, and the image needs to be square.

The spec even implies as much:

>Maximum value for width is 144, default value is 88. 
>Maximum value for height is 400, default value is 31.

**Comment by haikusw** [comment]
Any reason not to just use aspect fit?

**Comment by brentsimmons** [comment]
The problem with aspect fit is that we’d get terrible results when these icons are so far from being square. They would look silly and small.

**Comment by haikusw** [comment]
Good point; the icons _are_ pretty small.  Perhaps something to revisit if a large icon size feature is added someday (Ala Finder list view (in macOS 12.x at least)).
