### ISSUE TITLE
Keyboard navigation disabled after opening the Help menu

### ISSUE THREAD

**Issue by cparnot** [brentsimmons/NetNewsWire#377]
### What I did

- Open the Help menu
- Close the Help menu

### What happened

Unable to navigate the entries with the arrow keys

### What I expected

Be able to navigate the entries with the arrow keys

### Notes

- See https://indiestack.com/2018/04/helpless-help-menu/ --> Help menu search field steals keyboard focus
- Workaround: get to a text field, e.g rename an entry in the sidebar
- Maybe it's fixed in 10.13.6, I am still running 10.13.5
- Wait for Apple to fix?

**Comment by vincode-io** [comment]
I can't recreate this bug under 10.13.6.  My guess is that Apple has corrected it.  @danielpunkass, this bug cross references to blog post of yours.  Do you have any follow up on this issue?  It looks like you filed a Radar on it.

**Comment by cparnot** [comment]
No more bug for me in 10.13.6, running NNW 5.0d4 (1259)

**Comment by danielpunkass** [comment]
Unfortunately the bug is not 100% reproduceable in my experience. It would be good to get a few more  votes of confidence. I also cannot reproduce it on Mojave beta.

**Comment by brentsimmons** [comment]
Calling this fixed. We’ll reopen it if need be.
