### ISSUE TITLE
Evergreen fails to refresh automatically

### ISSUE THREAD

**Issue by betalogue** [brentsimmons/NetNewsWire#378]
Even though Preferences is set to refresh feeds every hour, nothing happens automatically. Only manual refresh works.

2014 Mac Pro with macOS 10.13.6

Evergreen 1.0d42 (1090)

**Comment by brentsimmons** [comment]
Good catch. That feature hasn’t been written yet.

**Comment by owensd** [comment]
Hah, I was wondering why this wasn't working! Good to know it simply is NYI.

**Comment by brentsimmons** [comment]
Duplicate of #60.
