### ISSUE TITLE
B

### ISSUE THREAD

**Issue by ghost** [brentsimmons/NetNewsWire#4067]
.

**Comment by stuartbreckenridge** [comment]
Hello!

In code, we do _request_ a frequent background refresh. However, this is actioned at the behest of iOS based on your usage pattern of the app and current device conditions (e.g., low battery will likely mean reduced background refresh). 

Therefore, the best advice is that the more you use NNW the more likely iOS will perform frequent background refreshes…and it may take the iOS some time to _learn_ that behaviour.

**Comment by stuartbreckenridge** [comment]
We've explored various options outside of the BackgroundTasks framework (which is what we use).

For example, regular background push notifications which would wake the app up and perform a refresh. This does, however, incurs costs ($ for the server and time from developers to support the server). 

NetNewsWire is [free](https://netnewswire.blog/2023/02/20/on-not-taking.html), so we're not keen to pursue options than incur costs.

**Comment by stuartbreckenridge** [comment]
No, to the first question. It's [more](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns) than just a toggle and server address. 

For the second, here are a few server examples:

- Swift: [Vapor](https://docs.vapor.codes/advanced/apns/)
- Javascript: [Node](https://github.com/node-apn/node-apn)
