### ISSUE TITLE
Release source code for NetNewsWire 3.3.2

### ISSUE THREAD

**Issue by chmaynard** [brentsimmons/NetNewsWire#417]
I have been a paid NetNewsWire 3.3.2 user for several years and I love it. I prefer its classic UI and I wasn't happy with the direction Black Pixel was taking the app. I would like to continue using 3.3.2, but there are a few showstoppers. The most critical issue is support for feeds that use SSL. Of course, I'm assuming Black Pixel transferred rights to the 3.3.2 source code to the author. That  did happen, right?

**Comment by chmaynard** [comment]
@brentsimmons Thanks for making the NetNewsWireLite repo public. If you could use some help with either 3.3.2 or 4.0, I'd love to contribute.

**Comment by tungol** [comment]
Well, it looks like this isn't going to happen, so I'll share my hacky workaround here if you want it: https://github.com/tungol/flask-proxy

That's a quick flask application I'm using to let NNW 3 fetch a local URL over HTTP that returns the contents of a HTTPS URL from elsewhere.

**Comment by chmaynard** [comment]
Thanks much! I suspect I've been missing out on many posts due to the SSL bug.  I still prefer the classic UI in NNW 3, as opposed to the "modern" style influenced by iOS. I expect to switch over to NNW Lite, assuming it also offers the classic UI as an option.
