### ISSUE TITLE
Feature Request: Group by feed

### ISSUE THREAD

**Issue by garionphx** [brentsimmons/NetNewsWire#422]
Ever since NewsFire died, I've been missing a feature it had,  in virtually all RSS feed readers: Group by feed

Say you have a feed list, that has several different feeds, CNN, FOX and MSNBC. I refresh all the feeds, and end up with a list of unread items:

- CNN 1/1/19 00:00 - CNN Article 1
- FOX 1/1/19 00:00 - FOX Article 1
- CNN 1/1/19 00:05 - CNN Article 2
- MSNBC 1/1/19 00:10 - MSNBC Article 1

When  it gets displayed, I'd like to see it grouped by feed, then by date (descending or ascending as wanted):

- CNN
  - CNN 1/1/19 00:00 - CNN Article 1
  - CNN 1/1/19 00:05 - CNN Article 2
- FOX 
  - FOX 1/1/19 00:00 - FOX Article 1
- MSNBC
  - MSNBC 1/1/19 00:10 - MSNBC Article 1

Bonus if each feed is collapsable.

**Comment by vincode-io** [comment]
@philviso Implemented this and we merged in pull request #1016.  It will be part of the 5.1 NetNewsWire release.
