### ISSUE TITLE
FR poll: Which sync services to prioritize?

### ISSUE THREAD

**Issue by benfsmith** [brentsimmons/NetNewsWire#423]
I know syncing services aren't the highest priority right now, but I'm curious which services the current user base would want to prioritize when the time comes. 

+1 FeedWrangler

**Comment by clausTue** [comment]
+1 feedwrangler

https://github.com/brentsimmons/NetNewsWire/issues/272

Nice to open after a few years ‚netnewswire‘ again!

**Comment by matthewdias** [comment]
+1 Feedly (might be better to thumbsup first votes instead of making a reply for every vote)

**Comment by venkatasg** [comment]
+1 FeedBin
+1 Inoreader

**Comment by habi** [comment]
https://feedafever.com/, even if it's officially dead. Reeder supports it and it's a great piece of selfhosted software.

**Comment by core-code** [comment]
+1 Feedly 

i've never considered the 4.x version of NetNewsWire because it only supported its own sync service, so it would be great to see real syncing being added.

**Comment by HenryQW** [comment]
https://tt-rss.org/

De facto the standard for self hosted RSS solution. Has its API.

**Comment by blackketter** [comment]
+1 Feedly

**Comment by timkrueger** [comment]
+1 feedwrangler

**Comment by kevinpapst** [comment]
+1 for [FreshRSS](https://github.com/FreshRSS/FreshRSS) with Google-Reader compatible [API](https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html)
+1 for Fever API (as this API is supported by [TT-RSS](https://github.com/DigitalDJ/tinytinyrss-fever-plugin) and [FreshRSS](https://freshrss.github.io/FreshRSS/en/users/06_Fever_API.html))

**Comment by krupenja** [comment]
+1 for Inoreader

**Comment by benfsmith** [comment]
+1 FeedWrangler

**Comment by MarkLopresto** [comment]
+1 Inoreader

**Comment by nanotubing** [comment]
+1 inoreader 
+1 tt-rss

**Comment by zachyordy** [comment]
+1 TT-RSS

**Comment by alexclst** [comment]
+1 Feedly.

I’m really interested in moving (back, after years elsewhere) to NNW, but need Feedly support first as that is where my RSS feeds currently sync. I’d be happy to help test Feedly syncing.

**Comment by fuzzy76** [comment]
Sorry to be "that guy", but the way to do this on Github is to create one issue for each service and see which issue gets most thumbs up on the issue itself. :)

**Comment by jfdhuiz** [comment]
+1 nextcloud news

**Comment by brentsimmons** [comment]
@fuzzy76 True. But this is working fine. And the order of services-supported is determined more by which services people volunteer to work on.

**Comment by fuzzy76** [comment]
True, but the issue description expresses a wish to see what is the most requested service. And this thread is getting way too messy to say...

**Comment by philippec** [comment]
+1 Feedwrangler

**Comment by dakira** [comment]
Fever API would be awesome. By that several services would get support all at once (like tt-rss and miniflux).

**Comment by brentsimmons** [comment]
Closing this because we’re not making decisions on syncing systems based on votes in a thread.
