### ISSUE TITLE
Instead of open the article-link, NNW tries to open GUID as link

### ISSUE THREAD

**Issue by MatzeLoCal** [brentsimmons/NetNewsWire#433]
When I try to open articles from coding.monkeydom.de [https://coding.monkeydom.de/](url) then NNW is asking me for the Application to open the URL.
Looking into the RSS-Feed [https://coding.monkeydom.de/posts.rss](url) it reveals, that NNW tries to handle the `guid` as URL instead of `link`

**Comment by brentsimmons** [comment]
There’s a bug in the feed. The RSS spec says that a guid is a permalink, unless it’s specifically marked as not a permalink. This feed does not mark it as not a permalink.

What NetNewsWire should do, then, is work around the bug in the feed.

**Comment by brentsimmons** [comment]
I just dealt with this situation in the RSS parser. It tries to detect when a guid that’s supposed to be a permalink actually isn’t one. Added a test with this specific feed.

This won’t fix already-parsed items, but it will fix the bug for future items.
