### ISSUE TITLE
Dark mode: link preview text color may be wrong

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#453]
Reported here: 
https://social.shadowfacts.net/notice/427756

Needs checking.

**Comment by strangebirds** [comment]
I also have this behavior of the link preview in dark mode being white text on light grey popover. NNW V 5.0d5 (1267) on Mojave beta 18A371a (I believe this is beta 8 as I am currently downloading beta 9).

**Comment by brentsimmons** [comment]
Fixed in 3243c8dd4d062ac26aa715c847d185451bf1dfa1.
