### ISSUE TITLE
Make Mark Read work, and have it change to Mark Unread when appropriate

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#46]

**Comment by brentsimmons** [comment]
Mark Read command now works, as of a7464daf15fd40eb3761213e6c80a95bd6de990d.

But it still needs to toggle.

**Comment by crgmrgn** [comment]
Context menu operates correctly, but toggling read/unread status via the toolbar button only supports read->unread status still.
