### ISSUE TITLE
iOS: Design and support some set of x-callback-URL things

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#475]

**Comment by brentsimmons** [comment]
It would be good to write up a proposal for the NetNewsWire Slack. Later on that proposal will turn into documentation and go in the TechNotes folder.

**Comment by vincode-io** [comment]
Siri Shortcuts do support the x-callback-url protocol, but the new way to do this is by using either NSUserActivity or Intents.  I suggest we use new mechanisms and close this issue.

**Comment by brentsimmons** [comment]
Agreed. Let’s go with the new way. Closing this.
