### ISSUE TITLE
Beachballing when selecting "Today" smart feed

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/NetNewsWire#481]
git @ d738bff

macOS 10.13.6
Intel Core i7 2,2 GHz

Reproducibility: always

Steps:
Click on "Today" smart feed.

What happened:
Beachballing.

[Instruments.trace.zip](https://github.com/brentsimmons/NetNewsWire/files/2413943/Instruments.trace.zip)

Expected result:
Fast performance.

Notes:
I am subscribed to 113 feeds.

**Comment by brentsimmons** [comment]
How log does the beachball last? A minute? Indefinitely?

About how many articles are in the Today smart feed?

**Comment by rex4539** [comment]
Hm, I can't seem to reproduce anymore. And I could reproduce it reliably when I filed it...

Maybe it was a combination of this that caused it.

I will close the issue for now and reopen if I can reproduce reliably.
