### ISSUE TITLE
Mojave Dark Mode: code style has low contrast with background

### ISSUE THREAD

**Issue by brehaut** [brentsimmons/NetNewsWire#487]
With NNW 5.0d6 (1272) in Mojave with the dark mode, I’m finding the code style to be hard to read due to the amount of contrast with the background. 

It’s managable, if not ideal, in blocks of code, but I’m really struggling with code inline in a paragraph of text where it’s in close proximity to substantially brighter text. 

This is on a 1st gen 5k iMac (which has the 8bpc and possibly lower contrast display), and I’m using it in a room with very dim lighting. 

I can provide a screenshot this evening if that’s helpful

**Comment by danielpunkass** [comment]
I ran into this with Erica Sadun's blog. Screenshot:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/14606/52862113-607cd480-3102-11e9-8691-3382b0e17834.png">

**Comment by danielpunkass** [comment]
With my proposed fix in place: 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/14606/52863140-0d585100-3105-11e9-9aaf-8fab4088ade4.png">
