### ISSUE TITLE
HTML on article pane

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/NetNewsWire#489]
https://medium.com/feed/@hodlhodl

![screen shot 2018-09-28 at 17 45 44](https://user-images.githubusercontent.com/227442/46217531-e8786280-c34a-11e8-91c2-fb5e5dde126b.png)

**Comment by brentsimmons** [comment]
The HTML stripper doesn’t deal with text that appears between style tags. (It’s a very basic HTML stripper.)

**Comment by brentsimmons** [comment]
See NSString+RSCore.m, rs_stringByStrippingHTML:.

It should strip everything between style and script tags.

**Comment by brentsimmons** [comment]
Fixed in c5cf11e4b755735b5019cb078db5cb540cb46b65
