### ISSUE TITLE
RSS urls that launch NNW don't open the New Feed dialog

### ISSUE THREAD

**Issue by willie** [brentsimmons/NetNewsWire#496]
Open a RSS URL:

If NNW is open already, the New Feed dialog opens with the URL. (Expected Behavior)

If NNW launches, the New Feed dialog does not open. I would expect it to open the New Feed dialog after launch.

**Comment by brentsimmons** [comment]
Fixed in 6416cb6bf24c704f50710716a4147bf61ec572a4
