### ISSUE TITLE
Styled source text in feed may display wonky in Dark Mode

### ISSUE THREAD

**Issue by strangebirds** [brentsimmons/NetNewsWire#499]
This may be related to 487.

Articles from:
http://languagelog.ldc.upenn.edu/nll/?feed=rss2

sometimes have blocks of quoted text hard-styled in the source (<span style="color: #000080;">…</span>). In Dark Mode this displays as dark blue on the dark grey background.

This is the only feed I've run across with this problem and it is _definitely_ low priority. I'm not sure NNW needs to be responsible for -cleaning the world's esoteric markup.

**Comment by brentsimmons** [comment]
I don’t even know how NetNewsWire would fix this (short of stripping all styles and JavaScript, which is too big a hammer). It should be considered a bug in the feed, instead.

**Comment by vincode-io** [comment]
We have revisited this issue and have decided to resolve it.  The fix will be in the 5.0.3 release of NetNewsWire.
