### ISSUE TITLE
Emojis in title are not rendered (or title-less posts don't render emojis)

### ISSUE THREAD

**Issue by strangebirds** [brentsimmons/NetNewsWire#520]
Observed Behavior: Subscribed to a feed (http://cdevroe.com/feed) and one of the posts is a title-less text entry: TIL Mark Hamill signs his tweets Mar🐪

When NNW renders a title, which is the text of the article, for the 2nd (middle column) 
the camel emoji does not render.

I tried to find another feed with an emoji in the title but was unsuccessful

Expected Behavior: Emoji with a unicode point should render when text is displayed.

Screenshot of existing behavior: <img width="1006" alt="screen shot 2019-01-17 at 8 34 02 am" src="https://user-images.githubusercontent.com/9995188/51325533-c35f4b00-1a32-11e9-9f68-847c014b1877.png">

**Comment by brentsimmons** [comment]
That item was gone by the time I got to this. I tried to reproduce it with a test feed, and wasn’t successful.

It’s possible that some other recent bug fixes have fixed this.
