### ISSUE TITLE
Feed not refreshing

### ISSUE THREAD

**Issue by danhausman** [brentsimmons/NetNewsWire#523]
Running Version 5.0d8 (1453) and I have my feeds set to refresh every 30 minutes, but they are not automatically refreshing. A manual refresh seems to work.  Could be a bug. What debugging data can I provide?

**Comment by brentsimmons** [comment]
It just hasn’t been implemented yet. It will be in the next build.

(I actually do have this feature done — I just need to release a new build that includes it.)
