### ISSUE TITLE
Feed titles change to "Untitled" after restarting NetNewsWire (Mac)

### ISSUE THREAD

**Issue by samesimilar** [brentsimmons/NetNewsWire#527]
Version 5.0d10 (522)

**Steps to reproduce**
1. In a new install of NetNewsWire, Import and OPML file.
2. The correct titles for all feeds will appear in the sidebar after they are downloaded the first time.
3. Quit and restart NetNewsWire -> Most feed titles will be replaced with "Untitled".

**Hypothesis**
The OPML file I am using to import feeds doesn't include a 'title' element on the individual feed items. After restarting the app, it looks like NetNewsWire is replacing the downloaded feed titles with the original value from the OPML file, which is retrieved as an 'editedName', and takes precedence over the downloaded feed name. In this case, since there is no feed name in the OPML file, the feed title becomes "Untitled". 

**Expected Behaviour**
If the original OPML file doesn't include 'title' attributes, then the downloaded feed name should not be replaced with a null value.
(My OPML file was exported from "The Old Reader".)

**Comment by samesimilar** [comment]
Hmm looks like there could be a race condition: Subscriptions.opml is written out with incomplete feed data (like feed titles). Some feeds will have titles, but many others will not (I'm importing about 80 feeds). After playing around with this for a bit I would guess that the feed info is being persisted at some random point while the feeds are downloaded, and then it is never updated.

**Comment by brentsimmons** [comment]
I believe the issue was just not handling a lack of title attributes in the OPML.

**Comment by samesimilar** [comment]
I'm seeing the same problem still in 5.0d12. I suspect that what is happening is this:
1. During OPML import all the new feeds are refreshed.
2. At the same time, the import progress triggers a save operation for Subscriptions.opml
3. During the save,  Feed.OPMLString(_:) reads from nameForDisplay to get each feed name.
4. nameForDisplay defaults to "Untitled" when there is no value for .name, or .editedName. Any feeds that were refreshed already will have names; feeds that haven't been refreshed yet will be written with text="Untitled" since they weren't provided with a name from the imported file. 
5. As the remaining feeds are downloaded, the sidebar updates to show their names. But Subscriptions.opml is not updated.
6. Quit and restart the app. All the feeds that were saved after Subscriptions.opml was written will revert back to "Untitled". 

I was able to force the feed names to persist by modifying code in a couple different ways. In Account.update(_:with:_:), either force a save operation, or set feed.editedName = parsedFeed.title. (Both of these fixes would likely cause side effects though.)

(I can provide you with the OPML file I'm trying to import, but I'd rather not post it publicly. I could put it up in a private repo and give you access for testing, if that works.)

**Comment by brentsimmons** [comment]
Does the OPML file also not include a text attribute for each item? I assumed it was the title attribute that was missing.

**Comment by samesimilar** [comment]
Do you mean the original OPML I'm importing? Here is an excerpt (there are about 80 items in total). This file was exported from The Old Reader.


[sample.opml.txt](https://github.com/brentsimmons/NetNewsWire/files/2834199/sample.opml.txt)

**Comment by brentsimmons** [comment]
No text attribute either! Okay, I get it. OPML files tend to have both text and title (and they have the same value). Not having the text attribute is really weird and I never saw that happen in all my previous years. But then, The Old Reader came along when I wasn’t working on NetNewsWire.

I’ll fix this in NetNewsWire, but it’s also worth filing a bug with the Old Reader — their OPML files would be better if they included a text attribute, at least, and text and title both, preferably (for maximum compatibility with other RSS readers, which is the whole point of OPML).

**Comment by samesimilar** [comment]
Great - thank you. I will file a bug on TOR - that's a good suggestion. Sorry to cause any confusion - I should have just posted an opml clip in my first report!
