### ISSUE TITLE
ATP Feed Items Appear Empty

### ISSUE THREAD

**Issue by meissnem** [brentsimmons/NetNewsWire#529]
Items from the ATP feed (<http://atp.fm/episodes?format=RSS>) show up empty in NetNewsWire. This seems to stem from the feed item including a `<content:encoded>` element with no content. RSParser sees that element is present and uses its content (none) instead of continuing on to look for the `<description>`.

I submitted a pull request to RSParser a while ago but never got around to mentioning it here -- sorry.

<https://github.com/brentsimmons/RSParser/pull/32>

**Comment by brentsimmons** [comment]
Good catch! Thank you.
