### ISSUE TITLE
Auto refresh does not reload list

### ISSUE THREAD

**Issue by pwnell** [brentsimmons/NetNewsWire#530]
Auto refresh seems to be loading new feeds correctly, however, even with manual feed refresh, the actual list never gets updated (All Unread) unless I click off the All Unread feed, and then back on it.  Therefore, the All Unread feed does not auto update its contents, just the item count.

**Comment by brentsimmons** [comment]
Good catch! Quite right. This hasn’t been done yet.

(Closed because it’s a duplicate of #338.)
