### ISSUE TITLE
Footnote display

### ISSUE THREAD

**Issue by pyrmont** [brentsimmons/NetNewsWire#544]
As of 5.0d15 (1517), NNW does not provide any built-in support for the display of footnotes. Links to footnotes jump the user out to the browser.

I think it would improve the user experience if NNW either displayed the footnote with some kind of popover (see an example below from Feedbin's website) or rewrote the URL so that clicking on the footnote link jumped to the end of the text within NNW.

<img width="661" alt="Footnote Example from Feedbin" src="https://user-images.githubusercontent.com/41152/52659433-9bcfa580-2f40-11e9-81f4-45bbb69d1b48.png">

**Comment by vincode-io** [comment]
@brehaut I've merged your pull request, but am having trouble getting it work with the example above.  I went to Feedbin and searched for the article, then starred it.  I was then able to go to the starred article.  When I click on the footnote link, I get taken out of the application and go into a browser that takes me to the web page for the article.

Did we lose something while doing the merge?

**Comment by brehaut** [comment]
@vincode-io Looks like the merge was fine. 

Apparently I didn't have Daring Fireball in my corpus of test cases. It looks like the markup there is slightly different to the footnote markup to what the script is looking for. I'll amend this, and see if there are any other common formats I’ve missed, and make a new pull request tonight.

**Comment by vincode-io** [comment]
This works and it looks awesome.
