### ISSUE TITLE
Sidebar: Unread counts are cut-off on startup if set to minimum width

### ISSUE THREAD

**Issue by sdtransier** [brentsimmons/NetNewsWire#546]
Version 5.0d15 (1517)

Repro steps:
1. Drag the sidebar to the smallest possible width before it auto-collapses
2. Close and re-open the app
3. The unread counts appear like this: 

<img width="1112" alt="screen shot 2019-02-13 at 10 38 30 am" src="https://user-images.githubusercontent.com/17955542/52731809-dc98e000-2f7b-11e9-8584-76982170851f.png">

**Comment by brentsimmons** [comment]
I can’t reproduce this. Tried on two machines. Maybe it’s no longer a bug? We can reopen this if someone else can reproduce this.

**Comment by sdtransier** [comment]
I can still reproduce this in 5.0d16 (1592). Here's a screen recording to demonstrate what happens:

[5.0d16.1592 - Unread counts cut-off.mov.zip](https://github.com/brentsimmons/NetNewsWire/files/2926614/5.0d16.1592.-.Unread.counts.cut-off.mov.zip)

**Comment by brentsimmons** [comment]
Ah! I see. I thought you were collapsing the sidebar. Now I understand.
