### ISSUE TITLE
Search performance is poor

### ISSUE THREAD

**Issue by rex4539** [brentsimmons/NetNewsWire#554]
git @ 797c7cb

I get multiple seconds of beachballing on every attempt to search.

Attaching an Instruments Time Profiler trace.

https://www.dropbox.com/s/fy9r1i07vujnilu/Instruments.trace.zip?dl=0

**Comment by brentsimmons** [comment]
@rex4539 Now that some time has passed, is this still an issue?

I ask because it’s possible that your articles were still being indexed as you were running searches.

If it’s still an issue, can you tell me about your machine? And about how many feeds you have?

**Comment by rex4539** [comment]
No, still getting 10-12 seconds of beachballing.

**Comment by rex4539** [comment]
MacBookPro8,2
Intel Core i7 2,2 GHz
8 GB RAM
256GB SSD

205 feeds

**Comment by brentsimmons** [comment]
About how many feeds do you have? What computer are you using? Is the disk near full? Is RAM use near full?

**Comment by brentsimmons** [comment]
If you quit all other apps, and then try a search, is it any different?

**Comment by brentsimmons** [comment]
Running 10.13 or 10.14?

**Comment by rex4539** [comment]
Closing all other apps did not make any difference.

I'm on 10.13.6

**Comment by brentsimmons** [comment]
My theory: it’s either a 10.13 issue or it has to do with the age of your machine. (Or both?)

I’ve wrote the code on a 2012 iMac, tested on a 2013 Air, and tested with a 2015 MBP — and search is pretty much instantaneous in each place. But they’re all running 10.14.

**Comment by brentsimmons** [comment]
I’ll try to dig up a 10.13 machine to test with.

**Comment by danielpunkass** [comment]
@brentsimmons The trace suggests the vast majority of time is spent in -[RSDatabaseQueue fetchSync:]

**Comment by danielpunkass** [comment]
I wonder if it could be more dependent on the specific set of feeds that @rex4539 has?  Maybe worth getting an OPML export?

**Comment by brentsimmons** [comment]
What’s weird is that, on my machines (2012 iMac, 2013 Air), that fetchSync call takes about 0.03 for the searches I run.

I have no idea why this would be taking so much longer on another machine.

**Comment by brentsimmons** [comment]
Good idea. @rex4539 Would you provide us with an OPML export?

If you don’t want to publish it here, you can email it to me: brent@ranchero.com

**Comment by rex4539** [comment]
[MySubscriptions.opml.zip](https://github.com/brentsimmons/NetNewsWire/files/2916562/MySubscriptions.opml.zip)

**Comment by crgmrgn** [comment]
I observed similar beachballing on an older laptop running 10.13.6 (large corpus w. ~350 feeds), particularly after first run of b15/16. 

Anyway, some quick experimentation leads me to believe its a low memory situation more than anything. If I shutdown most/all other apps (particularly hogs like Safari w. multiple tabs) then results pop within a second of searches being initiated. With a common cohort of my apps all open and memory in short supply, searching can be so painful that mis-typing in the search field leads to a world of frustration as beachballing ties up the app.

Guess my old "browsing" laptop needs a memory hike or retiring ...

**Comment by brentsimmons** [comment]
@rex4539 Has this improved? We’ve done some work in this area.

**Comment by rex4539** [comment]
Still getting ~8secs of beachballing with 5.0d16 (1592), the last build my machine is able to run.

**Comment by crgmrgn** [comment]
Same result as @rex4539, ~12secs beachballing searching on a simple term "iMac", navigating the result set is rapid/normal. Its just the actual search that is painful. This machine is also now orphaned on 5.0d16 (1592) as well as its a 10.13.6 box :(

**Comment by vincode-io** [comment]
Were you guys able to upgrade your machines to be able to test the production release of NNW for search performance?

**Comment by rex4539** [comment]
I got a brand new machine and, naturally, everything is lightning fast...
