### ISSUE TITLE
Not noticing updates on @mjtsai’s blog

### ISSUE THREAD

**Issue by peternlewis** [brentsimmons/NetNewsWire#580]
https://mjtsai.com/blog/feed/

Previously NNW 3 had the issue with Michael’s blog which required the script as described at (https://mjtsai.com/blog/2018/04/06/reading-this-site-with-netnewswire-3/).

Currently with NNW 5.0d16, it seems it is refusing to see any updates.  For example, if I look at the “Spectre Camera 1.0” article, it is still showing only the “Previously: Halide: One Year Later.” entry, everything below that  (eg “Update (2019-03-05): Nick Heer:…”) has not been added to NNW 5’s display.

https://mjtsai.com/blog/2019/02/28/spectre-1-0/

Even if I delete and quit and re-add the feed, it still shows only the original content.

Is there a cache that can be cleaned out?

Is this an NNW5 bug or an issue with the feed?

**Comment by brentsimmons** [comment]
It looks like his feed hasn’t been updated since Monday, March 4. Most recent article in the feed is “Bringing iOS Apps to macOS Using Marzipanify.”

Checked via `curl 'https://mjtsai.com/blog/feed/' `

**Comment by peternlewis** [comment]
But the article itself (https://mjtsai.com/blog/2019/02/28/spectre-1-0/) has been - does it need meta-data changing in the feed itself so that NNW recognises that the article itself has changed?

**Comment by brentsimmons** [comment]
NetNewsWire does a string comparison of the body of the article. It doesn’t trust any metadata. :) I’ll take another look at the feed. :)

**Comment by brentsimmons** [comment]
That article in the feed does not have the updates that appear in the website version. It looks like the glitch is entirely just that Michael’s feed hasn’t been rebuilt since Monday.

**Comment by peternlewis** [comment]
OK, so now the feed has been updated and shows the article, and NNW5 shows the updated text, but NNW5 does not show it as Unread, nor does it highlight in green the updates like NNW3 did (I'm not sure if the latter is a feature request or a bug report or related to the issue).  I'm happy to put this in a new Issue if you prefer, just all the details of the feed are already here.

**Comment by brentsimmons** [comment]
It’s something I hadn’t thought about much yet. I didn’t like everything about how older versions of NetNewsWire handled updated articles. All I know is that I want to do it better — but I don’t know what that means yet. :)

**Comment by peternlewis** [comment]
OK, so first, should NNW5 be marking the changed article as unread (it seems to me it should)?
