### ISSUE TITLE
Can't add a feed because no feed was found

### ISSUE THREAD

**Issue by kach** [brentsimmons/NetNewsWire#586]
I am trying to subscribe to `https://research.swtch.com/feed.atom`, which is a valid RSS feed, but NNW gives a dialog box saying `Can't add a feed because no feed was found`.

**Comment by danielpunkass** [comment]
The feed is rejected because it lacks an "<xml" header. In NSData+RSParser.m's isProbablyAtom, the test if isProbablyXML returns NO, so the feed is reported to probably not be Atom either.

@brentsimmons Maybe parsing should be a bit more lenient to accept cases like these?
