### ISSUE TITLE
"Today" smart feed to include articles posted since going to bed the day before

### ISSUE THREAD

**Issue by sebmos** [brentsimmons/NetNewsWire#587]
Usually when I check NNW in the morning, there are a bunch of articles in the "All Unread" smart feed that aren't in "Today", but weren't in Today the previous day.
(I'm a completionist, so I will mark every article as read, whether I read them, add them to Pocket, or neither.)

This is caused by articles are coming in between the last time I check in the evening, and midnight.
While *technically*, a day goes from midnight to midnight, but "perceived yesterday" ends when going to bed.

I don't know how to easily solve this (adding a setting to decide when a day ends would be the worst kind of "nit-picky detail"; auto-detecting would be quite difficult), but perhaps somebody has some brilliant idea that would make it work?

**Comment by brentsimmons** [comment]
One possibility: the app could store the date/time when it was last in the foreground, and provide a smart feed that shows everything unread since then.

The problem is, though, that if you then click away and come back, that smart feed would update and you’d lose everything in there.

Hmmm. It’s tricky!

**Comment by sebmos** [comment]
That would be quite the confusing behaviour, I would guess.

One possible way I could see would be to track when you last use your computer during a day, and just use that time. (Probably impossible in a sandbox environment?)
But then, what if somebody only checked their computer once in the morning? The might not have a legitimate expectation of afternoon blog posts to be part of "Today" the next day.
Unless of course that's the time you check every day, perhaps?

Tricky indeed..
