### ISSUE TITLE
Type 'FeedMetadata' does not conform to protocol 'Decodable'

### ISSUE THREAD

**Issue by kansaichris** [brentsimmons/NetNewsWire#588]
I'm getting the following error when I try to compile `Frameworks/Account/FeedMetadata.swift`:

>Type 'FeedMetadata' does not conform to protocol 'Decodable'
>
>Protocol requires initializer 'init(from:)' with type 'Decodable'
>
>Cannot automatically synthesize 'Decodable' because 'HTTPConditionalGetInfo?' does not conform to 'Decodable'

Is this an issue with the project itself, or do I need to modify my local Xcode settings?

**Comment by brentsimmons** [comment]
You need to update the RSWeb submodule.

**Comment by kansaichris** [comment]
Hmm…I just ran `git submodule update`, cleaned the Build folder (⇧⌘K), and started another build (⇧B), but I keep seeing the same error. Am I missing another step?

Also, thanks—that was fast! 😄

**Comment by brentsimmons** [comment]
I think I see the problem — pull and try again!

**Comment by kansaichris** [comment]
[That](https://github.com/brentsimmons/NetNewsWire/commit/57c5854efafcf63bbb7c293fc2eba9798ecc7b5a) did the trick—thanks! ✨
