### ISSUE TITLE
Default RSS feeds dissappeared 

### ISSUE THREAD

**Issue by CygnusRK** [brentsimmons/NetNewsWire#589]
Hello,

I deleted an older version of NetNewsWire and the great RSS feeds of your version disappeared. I can't remember all. Do you have a list, or anyway to get the default RSS feeds back? Even a screenshot would be great.

**Comment by brentsimmons** [comment]
You bet — here’s the current list of default feeds:

https://github.com/brentsimmons/NetNewsWire/blob/master/Importers/DefaultFeeds.plist

**Comment by CygnusRK** [comment]
Thanks Brent! I love RSS feeds and I love NetNewsWire.

**Comment by brentsimmons** [comment]
👍
