### ISSUE TITLE
Mark All as Read doesn't complete

### ISSUE THREAD

**Issue by jklundell** [brentsimmons/NetNewsWire#591]
I've seen this once only, so very intermittent. Tapped Mark All as Read in toolbar. All articles in current feed were marked as read, and the toolbar button was dimmed (as expected), but the feed's unread count didn't change. Build 1592. (Restarting NNW cleared the count.)

**Comment by brentsimmons** [comment]
I’m pretty sure this has been fixed. Can reopen if needed.
