### ISSUE TITLE
Javascript class twiddling no longer needed

### ISSUE THREAD

**Issue by meissnem** [brentsimmons/NetNewsWire#594]
From my testing, it looks like 10.14.4 added support for `@media(prefers-color-scheme: dark)` to WKWebView. Using that obviates the need for class twiddling dark/light via javascript.

Pull Request #593

**Comment by vincode-io** [comment]
This was merged.

**Comment by meissnem** [comment]
Thanks, @brentsimmons and  @vincode-io!
