### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#602]
Use one of the GitHub-supplied services on the free tier.

**Comment by brentsimmons** [comment]
I don’t know when this will happen. It doesn’t need to be done by 5.0 alpha, though.

**Comment by heckj** [comment]
@brentsimmons I took a flyer an opened an inquiry on your/this project's behalf to see if SemaphoreCI would be willing to offer their services for the Mac and IOS CI systems for this effort. 

I put in my contact info: normally SemaphoreCI is a paid-for thing for Mac/IOS, but they had some advert/copy indicating the OSS software might be granted limited, but no cost, services. The other alternative that's immediately obvious is TravisCI. 

In either case I thought I might create a PR and at least get the command-line Mac and IOS builds operational for this project.

**Comment by brentsimmons** [comment]
Thanks! That would be awesome.

**Comment by heckj** [comment]
PRs should be all merged for the baseline bits.
