### ISSUE TITLE
Timeline: on arrow down on last visible item, do animation up (like with next-unread)

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#604]

**Comment by Thomas-U** [comment]
and also the other way: 

on arrow up on last visible item, do animation down 

I usually start with the entry furthest down and then move up using arrow.

**Comment by vincode-io** [comment]
I'm not sure what this is supposed to do.  Does the down arrow take you to the first entry of the next feed when at the last entry of a feed?  Is it supposed to animate back to the top of the current feed?

**Comment by Thomas-U** [comment]
I had described my feature request in an email to Brent:

> when I navigate the timeline of a feed or a folder in NNW4 with the arrow keys, the whole timeline scrolls 5 entries down when I have reached the topmost entry. This way I can see the next 5 entries further up.
> 
> In NNW5 the timeline scrolls down just 1 entry. It feels a bit weird to navigate into "the unknown“.
> 
> The way NNW4 handles this feels more natural. Can this be applied to NNW5 too?

**Comment by vincode-io** [comment]
Perfect @Thomas-U.  I'll take a look at this today.

**Comment by vincode-io** [comment]
This is in and will be available in the next NetNewsWire build.  I'm pretty happy with how this turned out.  Brent had some pretty cool animated scrolling code that I was able to leverage.  This gives it a very natural feel when the extra scrolling is triggered.
