### ISSUE TITLE
iOS: support dynamic type

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#608]

**Comment by brentsimmons** [comment]
Are there semantic names for font sizes? I vaguely remember something like that, where we can specify we want, for instance, a font size for a title, and it adjusts for dynamic type.

**Comment by vincode-io** [comment]
Everything now uses the "text styles".  For example the timeline uses Headline, Footnote, and Body.  Most everything in the app is Body.

Check out the timeline.  It even has a special layout for the super huge accessibility sized fonts.

**Comment by brentsimmons** [comment]
My iPhone settings are toward the large end (though not the super huge, at least not yet). So I’m super-excited for this!
