### ISSUE TITLE
iOS: Make sure feed: protocol works to send feed to NetNewsWire

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#610]
Might need some way to make NetNewsWire the default feed reader on iOS.

I actually don’t know if any of this is possible, but step one is finding out.

**Comment by vincode-io** [comment]
I saw this in the CoreInt slack a while back, so I'm not sure what we can do.

![Screen Shot 2019-04-20 at 1 55 26 PM](https://user-images.githubusercontent.com/16448027/56461179-19b29180-6374-11e9-86f1-7008c6d0dda0.png)

It looks like Apple News hijacked the feed protocol and their isn't a way to set it.  I'm not 100% sure though and will research it further.

**Comment by brentsimmons** [comment]
Tried asking on Micro.blog and on Twitter.

https://twitter.com/brentsimmons/status/1120404286482128896

**Comment by vincode-io** [comment]
I did a fair amount of reading on this last night and it wasn't sounding good.  It looks like you can register for url protocols in the info.plist, but there isn't an API like there is on the Mac.  I hope we get some good news from your post.

**Comment by brentsimmons** [comment]
I’m not optimistic — the tweet is a Hail Mary.

**Comment by brentsimmons** [comment]
Closing this for now, since it’s apparently impossible. We’ll register for the feed protocol in Info.plist, but that’s all we can do.
