### ISSUE TITLE
iOS: Detail view: add toolbar at bottom with Next Unread text button

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#612]
Button should be at far left, I think.

Key point: when going to Next Unread, that can change the timeline you’re in. So the hidden views (timeline and source list) need to be in sync with the article you’re on. This way, when you hit the back button, you’re in the correct place.

**Comment by vincode-io** [comment]
This is in the repo, but has a couple bugs I will document in other tickets.
