### ISSUE TITLE
iOS: Timeline should not have big title

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#615]
Let’s try the timeline without the big title. Just put title in the navigation bar, like the old days.

I assume this is still possible. (I could be wrong!)

The issue is that the transition from an article in the timeline to the detail view is weird because of the large title, so I want to try without it.

Be prepared to have to reverse this.

**Comment by vincode-io** [comment]
The other way to get rid of that transition is to use large titles on the Detail page.  We would want to rework the article rendering to get rid of the redundant titles.  I tried this once and it didn't work out very well, but I didn't spend much time trying to get it right.  Just putting that option out there, but I'm not endorsing it.

**Comment by brentsimmons** [comment]
Agreed. Let’s not do large titles on the Detail page.

**Comment by vincode-io** [comment]
My 2 cents is that the timeline looked better with the large title.  You still have the transition when moving from large title on the Feeds list to the timeline, it was just moved upstream.
