### ISSUE TITLE
iOS: Plan for Settings

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#616]
What settings do we need? (Aside from account settings.) Let’s make a plan and propose it on the Slack.

If the answer is that we don’t need any settings (beyond accounts), then that’s totally a-okay.

**Comment by vincode-io** [comment]
If Account management will be in settings, should it be included with the Add Feed and Add Folder functionality?

**Comment by vincode-io** [comment]
I was expecting timeline order to be in settings.  Maybe that could be a button on the timeline too.

**Comment by brentsimmons** [comment]
I’d rather not have Account management in the add-feed and add-folder UI. Let’s keep it simple and re-evaluate later if it looks like there’s a reason to.

**Comment by brentsimmons** [comment]
Let’s put timeline order in Settings.
