### ISSUE TITLE
iOS: Timeline highlight color

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#619]
I’d like to try that system blue highlight color instead of the gray one.

**Comment by vincode-io** [comment]
Highlight color?  Is this the cell background color when selected?

**Comment by brentsimmons** [comment]
Yes — background color when selected.

**Comment by vincode-io** [comment]
There isn't a system blue on iOS the way that there is on macOS now.  I'm guessing there will be in another couple months.  I hope we get accent color too.  That would be perfect for this.

In the meantime, I created an entry in the asset catalog to tweak this color.  It is as close to the blue used in the normal button tinting as possible.  You can work with it by changing the selectionBackgroundColor entry.

I also updated the Feeds selection background color to match the timeline's.  They both use selectionBackgroundColor.

**Comment by vincode-io** [comment]
I like the way this looks and think it's a keeper.
