### ISSUE TITLE
iOS: Feeds list: Plan for long press on various items

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#620]
What happens when you long press on a smart feed, account, folder, or feed?

We should propose a plan on the Slack group.

**Comment by vincode-io** [comment]
I think this question comes down to if we are going to support cross application drag and drop.  The long press is the gesture that UIKit uses to pick up an item to drag from a tableview.  If we aren't, we can use the long press for something else.

If you were thinking about something like a context menu, maybe force touch for those?

**Comment by vincode-io** [comment]
iOS 13 negates my previous comment.  It supports both context menus and drag and drop for long touches.
