### ISSUE TITLE
Today smart feed plus time passing leads to old items in timeline

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#627]
Select the Today feed. Sleep through the night. Open your computer — there are now items from yesterday in the Today feed.

I think what should happen is this: when the app is brought to front or otherwise woken up, and the Today feed is selected, if it finds that it has non-today items then it should rebuild (by querying the database) its list of articles.

**Comment by vincode-io** [comment]
It looks like Apple added the NSCalendarDayChanged notification in 10.9 that works perfect for this.
