### ISSUE TITLE
Adjust timeline avatar placement when there‘s smaller than expected size

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#643]
Bring them up vertically.

**Comment by vincode-io** [comment]
Feedbin points all avatar urls to their servers where they have prescaled everything to 32x32 px.  Should we be scaling these up to 48x48?

**Comment by brentsimmons** [comment]
Let’s leave them at 32 x 32. There’s already a bug for adjusting layout in the timeline view to handle smaller graphics.
