### ISSUE TITLE
Smart Feed Sort Order Swapping Articles Around During Refresh

### ISSUE THREAD

**Issue by philviso** [brentsimmons/NetNewsWire#644]
When doing my initial Feed import from Feedbin, I had a smart feed selected (Today). During the import, a few articles in the list kept swapping places. There's a bunch of swapping happening overall, but two articles that always swapped places over and over were...

From theverge.com:
https://www.theverge.com/interface/2019/5/16/18627096/trump-social-media-bias-reporting-scam-christchurch-call

From kotaku.com:
https://kotaku.com/the-perfect-apartment-for-an-evangelion-fan-1834805529

In their respective RSS feeds, they both have the same`logicalDatePublished` of 2019-05-16 10:00:00 +0000"

**Comment by vincode-io** [comment]
When the logical published date is equal we now also sort by article id.  This will keep articles that have the same published date in the same order in the timeline while the timeline is being refreshed.
