### ISSUE TITLE
Timeline contextual menu: mark all read in feed

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#657]
In the contextual menu for the timeline, right below Select [feedname] in Sidebar, there should be a command: Mark All as Read in [feedname].

If all items are already marked as read, just don’t include that item.

**Comment by brentsimmons** [comment]
That command should apply to the feed for the selected article.

I tried it on an article in the Today smart feed, and the menu command offered to mark all as read for “Today” — but it should mark all as read for article.feed.

**Comment by vincode-io** [comment]
That's a lot more useful than what I originally implemented.  Changed now.
