### ISSUE TITLE
400 HTTP Error on importing OPML to FeedBin

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#660]
![Screen Shot 2019-05-19 at 3 30 33 PM](https://user-images.githubusercontent.com/1297121/57989122-17af2180-7a4b-11e9-9247-6aafceac805d.png)

**Comment by brentsimmons** [comment]
This should be fixed before the next public build.

**Comment by brentsimmons** [comment]
This appears to be reproducible: happened twice in a row.

**Comment by vincode-io** [comment]
Would it be possible to include the OPML file that you are using?

**Comment by brentsimmons** [comment]
Here’s my OPML file: https://ranchero.com/downloads/OMM.opml

**Comment by benubois** [comment]
What content-type header is NNW sending with these requests? I should have included this in the API documentation, but it might cause problems to use `application/x-www-form-urlencoded` or `multipart/form-data` because it will try to deserialize that incorrectly.

Either of these should work:

```
Content-Type: text/plain
Content-Type: text/xml
```

**Comment by vincode-io** [comment]
I changed the Content-Type and it seems to have resolved the issue we were having.  Thanks @benubois.
