### ISSUE TITLE
Today smart feed should update after an account is marked as inactive

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#663]
I have the Today feed selected. I make my On My Mac account inactive. The Today feed unread count changed — the but the feed is still showing articles from my On My Mac account.

**Comment by brentsimmons** [comment]
If I go away and come back, then the feed is correct.

**Comment by philviso** [comment]
Beat ya to this one... 😆

https://github.com/brentsimmons/NetNewsWire/issues/645
