### ISSUE TITLE
Feature Request: Offline RSS feed

### ISSUE THREAD

**Issue by specter78** [brentsimmons/NetNewsWire#672]
I do not know whether this has already been implemented. However, it would be nice if RSS feeds (text content like Safari reader) are downloaded to read later offline.

**Comment by brentsimmons** [comment]
I’m not sure if I understand or not. NetNewsWire does download feeds and make the articles available offline. (The available text is whatever was in the feed.)

If that’s not what you meant, please comment and I’ll reopen this bug!
