### ISSUE TITLE
Syncing setup: pull Feedbin credentials from Keychain

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#680]
When a person is setting up FeedBin syncing, we should look for an existing keychain item — it’s likely they’ve already been to FeedBin in their browser, and would have stored credentials.

**Comment by vincode-io** [comment]
Is this possible to do?  I've tried querying the keychain for those items, but haven't had any luck.  It makes sense to me that an application wouldn't have access to the Safari web form items.

I know that iOS has autofill capabilities now for applications, but I don't think there is an equivalent yet for the Mac.

I've done quite a bit of research and can't figure it out.  If anyone knows how to do this, could you point me in the right direction?

**Comment by brentsimmons** [comment]
I think using kSecClassInternetPassword as you already are — but searching on feedbin.com instead of api.feedbin.com — should do the trick. I think. (It’s been a while since I’d done this.)

**Comment by vincode-io** [comment]
I tried that, but maybe I did something wrong. I wonder if using iCloud Keychain is tripping me up...

**Comment by vincode-io** [comment]
This one has me stumped.  I'm not sure that it is possible to get to keychain data that Safari has saved anymore.

Right now, the only data that I'm able to query is data that is in the "login" keychain.  Data in the "Local Items" or "iCloud" doesn't seem accessible.  This makes sense to me as we wouldn't be in the same Access Group as Safari and thus not able to access Safari items.

I've attached a playground that shows what I'm doing.  If anyone knows a way to get to the Safari Keychain items, please let me know.

[Keychain.playground.zip](https://github.com/brentsimmons/NetNewsWire/files/3242256/Keychain.playground.zip)

**Comment by brentsimmons** [comment]
I think we have to close this. My guess is that it’s just a thing we can’t do anymore.

If we see some hints that we’re wrong, we can reopen this.
