### ISSUE TITLE
iOS: Timeline: First Unread command should open first unread article in detail view

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#695]
Unseen by the user, the timeline should scroll to the first unread article.

**Comment by vincode-io** [comment]
I implemented this as a timeline specific feature.  The First Unread button is disabled if there are no unread articles in the current timeline.  If the button is available and selected, the first article in the timeline is selected and shown in the detail view.

This is different from the circle-arrow button in the detail view which works across all timelines.
