### ISSUE TITLE
iOS: Navigation bars should have a fill color

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#698]
NetNewsWire blue. See #691 

We might need to make the text white for it to be readable.

**Comment by vincode-io** [comment]
I'm leaving these WWDC video notes here for future reference on how to do this in iOS 13.

![Screen Shot 2019-06-26 at 3 40 36 PM](https://user-images.githubusercontent.com/16448027/60214803-da993480-982b-11e9-8a35-9c697038711a.png)

**Comment by vincode-io** [comment]
Do we need to put together a color palette or do you want me to wing it?  There are things that need to be worked out like dark mode support, what color is the progress bar, etc...  Just verifying here... the bottom toolbar turns NetNewsWire blue with white text too, right?

**Comment by brentsimmons** [comment]
Colors should be in an asset catalog, so we can change them — but, yeah, for now, just wing it with the actual color values.

I think the bottom toolbar should be NetNewsWire blue also, yes. (For now, at least. There will surely be iterations.)

**Comment by vincode-io** [comment]
I quickly knocked this together this evening.  Here is what it looks like.

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-08-22 at 18 26 26](https://user-images.githubusercontent.com/16448027/63556478-9b752000-c50a-11e9-9bcb-7e2cbeceb2a5.png)

Does this only apply to light mode or should dark mode get this look too?

**Comment by brentsimmons** [comment]
Great question. That blue is a bit over the top here, I think. (Though it might look different on a device than on a screenshot on my Mac.)

I’m going to run it by Brad and see if he has a related, but toned-down, blue that he suggests.

I’ll get advice from him about Dark Mode too.

**Comment by brentsimmons** [comment]
Brad says: let’s go white. (And dark for Dark Mode.) I agree.

**Comment by vincode-io** [comment]
White looks much nicer.  We have 3 new colors in the asset catalog to tweak this in the future if we want to: barBackgroundColor, barTintColor, and barTitleColor.  Right now barTintColor and barTitleColor are both NetNewsWireBlue, but they can be different colors to help differentiate the title from the buttons.

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-08-23 at 12 18 42](https://user-images.githubusercontent.com/16448027/63611118-c8741200-c5a0-11e9-96b0-63a28cae13dd.png)

NetNewsWireBlue is too dark for darkmode.  I'm currently using #4490E2 for tint color.  Brad might have a different shade we should be using.

![Simulator Screen Shot - iPad Pro (9 7-inch) - 2019-08-23 at 12 24 03](https://user-images.githubusercontent.com/16448027/63611248-112bcb00-c5a1-11e9-91f2-d4536a66ca1a.png)
