### ISSUE TITLE
Newly added Feed appears in folder and outside of folder - same item?

### ISSUE THREAD

**Issue by strangebirds** [brentsimmons/NetNewsWire#701]
Version 5.0d17 (2114)

I used the Safari extension to add a feed (is there a menu item to add this to Safari? Is it automatic?) and assigned it to a folder within the add feed dialogue. The feed was added, parsed, and showed up in "On My Mac" (not where I intended) and in the folder (my intention).

Deleting either copy led to the other being deleted. In the case of the folderized copy, it did not immediately disappear, but only when the folder was collapsed and reopened (or the view changed) which leads me to think it is the same item being displayed in two locations. If the folder was collapsed the unread number would decrement by the correct amount on deleting the copy in "On My Mac"

Behavior was the same whether added directly in NNW or via the Safari Extension. I did not try drag-and-dropping the feed address from Safari to NNW.

Adding the feed and restarting NNW resulted in the same behavior. Adding the feed to any other folder resulted in the same behavior.

Adding the feed to the default "On My Mac" and dragging it to a folder led to the expected behavior of the feed residing in just the one visual location.

It was an RSS feed (https://www.highcaffeinecontent.com/blog/rss.xml) and doesn't appear to have problems in the feed itself. I tested with two other feeds (both RSS) and the behavior was similar.

**Comment by vincode-io** [comment]
@strangebirds I just put a fix for the bug you are describing in the repository.  It will be in the next public build of NetNewsWire which may happen within the next week.
