### ISSUE TITLE
Article status sync bug

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#708]
I’m not sure what exactly the bug is, so I’ll describe what I see.

I’m running NetNewsWire on two Macs in my office.

On Mac #1, I refresh, then read everything. Then refresh again, and there’s nothing new. Totally fine.

On Mac #2, I refresh, and I get new articles (as expected) that match what’s on Mac #1. However — they’re marked as unread, when I have read them on Mac #1.

I refresh Mac #2 again, and they’re still unread.

Then I login to the Feedbin website — and they are properly marked as read there.

It’s just on Mac #2 where they’re still marked as unread.

**Comment by brentsimmons** [comment]
Ignore the links to issues 1 and 2. :) GitHub made those links.

**Comment by brentsimmons** [comment]
Maybe there’s a conditional GET thing misbehaving? I haven’t dived into this area of the code, so I don’t know what it could be.

When I refresh Mac 2, the Xcode console shows me this:

2019-05-26 16:39:15.336325-0700 NetNewsWire[33609:3382387] [Feedbin] Refreshing articles...
2019-05-26 16:39:15.480284-0700 NetNewsWire[33609:3363928] [Feedbin] Done refreshing articles.
2019-05-26 16:39:15.480318-0700 NetNewsWire[33609:3363928] [Feedbin] Refreshing article statuses...
2019-05-26 16:39:15.793224-0700 NetNewsWire[33609:3363928] [Feedbin] Done refreshing article statuses.
2019-05-26 16:39:15.793264-0700 NetNewsWire[33609:3363928] [Feedbin] Refreshing missing articles...
2019-05-26 16:39:15.795556-0700 NetNewsWire[33609:3363928] [Feedbin] Done refreshing missing articles.

**Comment by vincode-io** [comment]
I think I know what happened here.   We save unread statuses for articles that we don't have an article for yet, but the processing to mark a status from read to unread depends on an article being present.

Frankly, I don't know how we haven't ran into this problem yet.  I've been bouncing back and forth between my phone and desktop and should have triggered it too by now.

I'll have a fix for it in this evening or first thing tomorrow morning.

**Comment by vincode-io** [comment]
I was successfully able to recreate this bug.

Steps:

1) Set refresh feeds to manual
2) Subscribe to a new feed on the Feedbin site
3) Wait for a status sync to get the new unread article statuses into NetNewsWire
4) Mark all as read on the Feedbin site
5) Wait for a status sync to get the now read articles statuses into NetNewsWire
6) Do a full article refresh

Before you would have the new feed articles in an unread state.  After the fix, they are in the correct read state.
