### ISSUE TITLE
iOS: UI got into a crazy state when returning from a list of articles

### ISSUE THREAD

**Issue by philviso** [brentsimmons/NetNewsWire#713]
I haven't been able to reproduce this, but here's what I was doing in current session before the UI got into this state...

- Using the default local account, I was playing around with creating folders, using drag and drop to move feeds in and out of folders, and expanding / collapsing folders.
- Most of the feeds I ended up moving into a newly created folder named "Tech"
- I tapped on the "Tech" folder to view all of the articles in that folder.
- I tapped the back button to return to the feeds list
- When I returned to the feeds list it looked like this...

![Simulator Screen Shot - iPhone 8 - 2019-05-27 at 14 43 53](https://user-images.githubusercontent.com/347423/58437783-27ed7f00-8091-11e9-8d97-e52acda1765a.png)

This was done with an iPhone 8 simulator running iOS 12.2.

**Comment by vincode-io** [comment]
I haven't been able to recreate this since removing the cell layout caching.  I'm going to assume that this issue had been resolved.  We can reopen if it shows up again.
