### ISSUE TITLE
FreshRSS (Google Reader compatible) Syncing

### ISSUE THREAD

**Issue by jbeker** [brentsimmons/NetNewsWire#716]
Add support for syncing with [FreshRSS](https://freshrss.github.io/FreshRSS/) as a backend. FreshRSS supports two now-defunct syncing APIs, Fever & Google Reader.

**Comment by jbeker** [comment]
I am starting to tackle this. Using the Google Reader API.

**Comment by WanderingStar** [comment]
I'm happy to test against baxqux.com, which also supports Fever & Google Reader. https://bazqux.com/faq

**Comment by vincode-io** [comment]
@WanderingStar I have created a separate issue #777 to track BazQux syncing.  If you would volunteer to test on that ticket, it would be much appreciated.

**Comment by vincode-io** [comment]
Closing this as it is implemented and we are tracking its progress as individual issues.
