### ISSUE TITLE
Add a placeholder while images are loading

### ISSUE THREAD

**Issue by aaronraimist** [brentsimmons/NetNewsWire#717]
Currently images just pop in. It would be nice if there was some kind of placeholder to let you know that an image was loading. I often read Twitter through RSS and if I have a slow connection I often read the tweet and tap the arrow key to move on and then an image loads in and I have to go back.

**Comment by brentsimmons** [comment]
Do you mean in the article view or in the timeline?

**Comment by aaronraimist** [comment]
In the article view, assuming the timeline means the list of articles. I didn't realize the timeline had images other than favicons?

**Comment by brentsimmons** [comment]
Gotcha. (Yes, the timeline is the list of articles.)

**Comment by brentsimmons** [comment]
The article view is managed by WebKit, and we don’t have a way to get in there and do placeholder images.
