### ISSUE TITLE
Adding an already-added feed leaves the UI locked up

### ISSUE THREAD

**Issue by NickFitz** [brentsimmons/NetNewsWire#720]
Click the + button and attempt to add a site whose feed is already subscribed to. The "Finding feed…" thingy appears, and then an alert appears saying the feed cannot be added as it is already subscribed to. But it isn't possible to click the button to dismiss this alert as the "Finding feed…" thingy blocks it.

For some reason, the "Finding feed…" thingy still hadn't gone after a couple of minutes, and I had to Force Quit.

(The site in question is http://www.atpm.com/ and its feed URL is http://www.atpm.com/rss/index.xml though NNW isn't showing any articles from it, hence the attempt to re-add in case the feed URL had changed.)

**Comment by vincode-io** [comment]
@NickFitz could you let me know which version of NetNewsWire you are on?  Also were you using a Feedbin account or an On My Mac account?

**Comment by NickFitz** [comment]
Sorry, should have remembered to include that info! Version 5.0a1 (2185) and On My Mac account.

**Comment by vincode-io** [comment]
Thanks @NickFitz.  I'm able to recreate the problem now and it will be resolved in the next release.
