### ISSUE TITLE
Unable to import newsfeed (atom) from github's home page

### ISSUE THREAD

**Issue by yubozhao** [brentsimmons/NetNewsWire#721]
Issue:
In github's homepage, there is a link `Subscribe to your news feed` below the All activity section.  It creates a `USER_NAME.private.atom` file.  NetNewsWire can't import the atom file.

Expectation:
Click the button, it opens up NetNewsWire and your newsfeed will be imported into the app and appear as a feed inside.

**Comment by vincode-io** [comment]
I just tried this and it worked for me.  Are you making sure to include the token parameter when subscribing?

**Comment by yubozhao** [comment]
@vincode-io Thanks! You are right about the token parameter.

I was downloading it as atom file, instead of copy/paste the atom feed link.
