### ISSUE TITLE
Read articles turn back to unread on Refresh

### ISSUE THREAD

**Issue by arkadyan** [brentsimmons/NetNewsWire#723]
I've only seen this sporadically, I assume it is related to syncing with Feedbin.

Steps:

1. Navigate through a number of articles. These articles are marked as Read.
2. Click Refresh
3. The articles that were recently read revert to being marked as Unread.

**Comment by vincode-io** [comment]
This issue is resolved and will be in the next release of NetNewsWire.  Thanks go out to @tgt for this bugfix.
