### ISSUE TITLE
Don’t stack up refresh error messages

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#730]
I opened my Mac for the first time in a couple days. NetNewsWire was running. It showed a no-internet-connection error to Feedbin. I clicked it away. Then it showed another one. Then another one. I ended up force-quitting the app.

My guess is that these were all stacked up. I don’t know how many there might have been.

Instead, we should show just one error. If a sync/refresh error is already pending, drop it in favor of the new error.

**Comment by vincode-io** [comment]
Does moving the refresh errors to the log instead of a dialog handle this (#729)?  I can't think of any other way that we could stack up errors.

**Comment by brentsimmons** [comment]
Good question. Let’s move them to the log. Maybe we should add the Errors Window to 5.1.

**Comment by vincode-io** [comment]
Refresh errors got moved to the log in #729.  Should we close this issue out?
