### ISSUE TITLE
"Check for Updates..." disabled

### ISSUE THREAD

**Issue by spencertransier** [brentsimmons/NetNewsWire#736]
Version 5.0a1 (2185)

I saw this before the alpha, but it's happening again in alpha 1. I have to download the full build from the website instead of using Sparkle.

<img width="241" alt="Screen Shot 2019-06-10 at 9 08 55 AM" src="https://user-images.githubusercontent.com/17955542/59205116-65f1a500-8b5f-11e9-8792-dcfdfcac867d.png">

**Comment by spencertransier** [comment]
This might have been user-error on my part. It worked fine for updating to alpha 3 tonight. I'll open again if it happens.

**Comment by brentsimmons** [comment]
This is a bug in Sparkle, unfortunately.

**Comment by peternlewis** [comment]
What's the fix for this?  It happened to me too.

**Comment by vincode-io** [comment]
You can work around this issue by directly downloading from the NetNewsWire home page.  https://ranchero.com/netnewswire/

**Comment by peternlewis** [comment]
I quit and relaunched NNWit, and it offered me the update.
