### ISSUE TITLE
Certificate error during refresh

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#740]
![Screenshot 2019-06-01 at 12 51 08](https://user-images.githubusercontent.com/1297121/59228507-d95ddb80-8b8c-11e9-821f-3094d90b8060.png)

If we can’t provide Connect/Cancel buttons — and I’m not sure we can — then we should suppress this and just log it.

**Comment by vincode-io** [comment]
I'm not able to recreate this on the latest release of NetNewsWire.  

I get the "Feed Not Found" message when trying to add it.  I recently changed how FeedFinder errors were reported for the local account, so this dialog may have been produced on an older version of NetNewsWire.  I also manually added it to the Subscriptions.opml and didn't get an error message from tying to refresh it.

Do we have anymore information to go off of?  What task was being performed and what version of NetNewsWire this is?

**Comment by brentsimmons** [comment]
Sorry -- good question. This was while trying to add a feed. (I don’t have more details than that.)

The report is from June 1. I assume the person was using alpha 1, but I don’t know that for sure.

If you think this is likely no longer an issue, since you were in that code most recently, please do close this. We can always open a new one if it comes up again.

**Comment by vincode-io** [comment]
I'm pretty sure this one is gone now.  I turned the app every which way trying to make it happen and can't.
