### ISSUE TITLE
Entities appearing in title in Article view

### ISSUE THREAD

**Issue by rtvenge** [brentsimmons/NetNewsWire#743]
It looks like this #288 bug has crept up again. Entities are being shown in the main article view but not the list view.

I'm seeing it in the [Talking Points Memo Feed](http://talkingpointsmemo.com/feed/all).

This bug started started in alpha 2 (I think that was when some work on titles was done?).

This article was pulled in via Feedbin on the Alpha 2 build, so if this was fixed in Alpha 3 and the title is just cached locally, let me know.

Here's a screenshot:

<img width="1578" alt="Screen Shot 2019-06-11 at 8 44 48 AM" src="https://user-images.githubusercontent.com/303836/59287168-f98da900-8c25-11e9-9796-eaccc5a554c0.png">

**Comment by brentsimmons** [comment]
We need to revert the recent change with titles in the detail view. And then figure out how to fix the previous bug that that was supposed to fix.

**Comment by vincode-io** [comment]
This has been reverted in mac-candidate and will be in the next release.  I've also reopened #722 to track the issue that broke this.
