### ISSUE TITLE
AppleScript: Make read/starred read/write

### ISSUE THREAD

**Issue by Wevah** [brentsimmons/NetNewsWire#744]
Someone mentioned in the Slack that they'd find being able to set the read/starred status on articles from AppleScript useful, so they could ignore articles (by preemptively marking as read) that matched certain criteria.

**Comment by brentsimmons** [comment]
This should be in 5.0. I hadn’t realized that these attributes weren’t read/write from AppleScript.

**Comment by olofhellman** [comment]
I recommend the #749 PR be accepted.
