### ISSUE TITLE
feed icon sizes

### ISSUE THREAD

**Issue by zarqman** [brentsimmons/NetNewsWire#745]
Certain feed icons show up super small (I'm guessing old school favicon.ico dimensions).

I'm seeing it on several feeds. Here's an example for xkcd.com (dilbert is the expected size, for reference):

![comics (76)](https://user-images.githubusercontent.com/22556/59310695-763f7800-8c64-11e9-8926-d5ff125d3a41.png)

Would it be appropriate to scale these up, even if a bit pixelated?

**Comment by brentsimmons** [comment]
We tried — it ended up way to pixelated. Leaving those at their original size was better. :)

**Comment by zarqman** [comment]
Fair enough. Thanks much! 

(And thanks for the many years of a useful app--super nice to see NNW live on in v5).
