### ISSUE TITLE
NNW takes a few moments to quit

### ISSUE THREAD

**Issue by kach** [brentsimmons/NetNewsWire#750]
First: I've been using NNW as my main RSS reader for months now and it's amazing, thank you so much for creating this. :-)

Recently I saw the announcement that Version 5.0a1 (2185) was available to download, so I installed it. The update process was really smooth, but now NNW takes a couple of seconds to quit, rather than quitting instantaneously on cmd-Q as it used to (for comparison, Mail.app quits instantaneously). It's just long enough to feel concerning, and I'm wondering whether NNW started doing some cleanup task that could be optimized.

I'm not a Mac developer so I'm not sure what other information I could give you to help investigate, but let me know and I'm happy to provide what I can.

**Comment by brentsimmons** [comment]
Are you using Feedbin syncing?

If so, then it’s probably that NetNewsWire is sending changes to Feedbin during quit.

**Comment by kach** [comment]
No, it's not syncing to anything.

**Comment by brentsimmons** [comment]
Let’s see if we can reproduce this. There shouldn’t be anything slowing down a quit operation outside of syncing.

**Comment by kach** [comment]
Apologies for the really horrid GIF (I undoubtedly gave ffmpeg the wrong flags) but here's a real-time screen recording of me quitting NNW. Notice the couple moments of lag between clicking "quit" and the application actually quitting, which didn't happen before and also doesn't happen for, e.g. Mail.app or Calendar.app.

![nnw](https://user-images.githubusercontent.com/5202416/59385343-f8897400-8d18-11e9-92c5-fdd5b5dc3c91.gif)

**Comment by vincode-io** [comment]
Right now we do a 1 second delay on app quit to get any syncing done.  I think we decided that we would give the response a second to come back to clean up the syncing database.  In practice this never happens and we just resend the statuses next time that NNW runs.  

(The delay is there for all account types since we don't know when we make the call to AccountManager how many and what types of Accounts the system has.)

I think we should pull out the 1 second delay and see if we still get the statuses sent to Feedbin.

**Comment by brentsimmons** [comment]
Sounds reasonable to me.

**Comment by vincode-io** [comment]
This was actually a bug that caused us to always hit our 1 second timeout delay regardless of the work done by the delegate on exit.  "On My Mac" exits are instantaneous now and "Feedbin" exits seem a little faster now too.  I've made the fix and pushed it to mac-candidate.

@kach Thanks for the bug report.  You will notice faster quits in the next release.

**Comment by kach** [comment]
Thanks Maurice, thanks Brent! :-)
