### ISSUE TITLE
Drag and drop between accounts doesn't update UI

### ISSUE THREAD

**Issue by IainDelaney** [brentsimmons/NetNewsWire#752]
Create a new account named 'Jobs'. Have a folder called 'Jobs' in the default 'On My Mac' account. Drag a feed from the 'Jobs' folder to the 'Jobs' account. It looks like nothing happened.
Quit the program and restart. The folder and the account now look correct.

**Comment by vincode-io** [comment]
@IainDelaney, we weren't correctly recovering from errors while moving or copying between accounts.  That's why you saw the Feeds list become unresponsive after trying to copy a dead feed.

It is now fixed and will be part of the next NetNewsWire release.
