### ISSUE TITLE
iOS: About Options on Settings View should open in app

### ISSUE THREAD

**Issue by stuartbreckenridge** [brentsimmons/NetNewsWire#756]
Currently, when selecting one of the About options, e.g. Website, the application switches out to Safari. To keep the user's focus to NetNewsWire, external websites should be opened in the app.

**Comment by vincode-io** [comment]
This is a good idea.  My only feedback it that maybe we should use SFSafariViewController instead of WKWebView.  Most of those About options have links to other resources.  Having more complete browser controls will probably be useful.

**Comment by stuartbreckenridge** [comment]
Agreed. I'll put something together for a PR tomorrow.

**Comment by vincode-io** [comment]
Want to do #754 while you are in there tinkering around?

**Comment by stuartbreckenridge** [comment]
Sure.
