### ISSUE TITLE
Ability to hide/remove/not page through Smart Feeds

### ISSUE THREAD

**Issue by WanderingStar** [brentsimmons/NetNewsWire#761]
I like to read my feeds in a particular order. It works well to page through the list, but when I go past the end of the list, it moves me up to the Smart Feeds (Today, All Unread, Starred), which don't maintain my desired order. I then need to switch back to the first of my folders. (See also #760)

I'd like the option to not hit those Smart Feeds as I page through, but instead to jump back to the start of my ordered feeds.

I imagine that this might also be accomplished by the ability to hide or remove the Smart Feeds from the list, which would work for me.

**Comment by brentsimmons** [comment]
You can hide the Smart Feeds. Mouse over the “Smart Feeds” row on the right. You should see a Hide button.
