### ISSUE TITLE
iOS: Duplicates in Today View

### ISSUE THREAD

**Issue by stuartbreckenridge** [brentsimmons/NetNewsWire#763]
If a user is subscribed to the same feed on both the device and Feedbin, the Today view will show feed entries as duplicates. 

![1CCCC5C9-13AA-4037-8AA2-E815CDCA1F7C](https://user-images.githubusercontent.com/7046652/59649324-d9756100-91b4-11e9-846f-33c6bcba35a6.png)

**Comment by brentsimmons** [comment]
This is okay. It’s honest — if you’ve got the same feed in two accounts, this will remind you.

**Comment by stuartbreckenridge** [comment]
That’s fair. I’m wondering if the smart feeds should have some visual indicator to show which account the entry has come from?

**Comment by brentsimmons** [comment]
My concern there is too much information to display. Knowing the account won’t matter almost all the time.
