### ISSUE TITLE
Suggestion: Center Preferences window on first open

### ISSUE THREAD

**Issue by jsavin** [brentsimmons/NetNewsWire#769]
On first run, when opening the Preferences window, it appears at the upper-right corner of the screen. This looks a little odd, especially on a very large display.

Preconditions: First run of the app, Preferences never opened
What I did: Hit Command-comma to open the Preferences window
What I expected: The Preferences window opens up, centered in the same screen as the NNW main window
What happened: The Preferences window opens up at the very top-left corner of the display

Note: I have only one display connected to this machine, so I don't know if it would open on the same display as the NNW main window or not. Might be worth checking that too if you decide to make changes in this area.

**Comment by brentsimmons** [comment]
Decided to punt till 5.0.1.
