### ISSUE TITLE
FreshRSS: Subscribe to feed always gives "Already Subscribed" error

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#774]

**Comment by jbeker** [comment]
ok, well I know that worked at some point. Sorry :/

**Comment by jbeker** [comment]
Do you remember what URL you used? I think I know what is going on here, but I would like to test some more. (I don't believe that FreshRSS has the ability to detect an RSS feed from the metadata of a base domain, so you have to give the direct link to the feed)

**Comment by vincode-io** [comment]
Try this one: https://vincode.io/blog/feed

If FreshRSS doesn't support finding a feed from a page, we might want to look at using our Feed Finder to supplement FreshRSS in the account delegate.
