### ISSUE TITLE
Occasionally missing articles in the middle pane for the 'All Unread' view

### ISSUE THREAD

**Issue by cparnot** [brentsimmons/NetNewsWire#783]
Occasionally, when coming back to NNW, I find that the 'All Unread' view is not showing all the articles it should:

- The badge in the side is correct (e.g. '7')
- The middle pane only has the articles that were already there before the refresh, missing all the new ones (e.g. only 6)

See screenshot below. It's happened to me several times over the past 2-3 betas, with varying number of articles (the missing articles are always the recently fetched).

The good news is that it's fairly rare, and easily missed as the only inconsistency is with the badge. It fixes itself at the next fetch (triggered manually or automatically, both work) **if** the number of unread articles changes (which I suppose trigger an actual UI refresh), or by unselecting 'All Unread' in the sidebar and then selecting it again.

But this is also bad news, because I don't know how to reproduce consistently, and it's hard to catch "in the wild".

<img width="1540" alt="Screenshot 2019-06-21 13 05 43" src="https://user-images.githubusercontent.com/4797/59918577-658dbf80-9425-11e9-9814-7d29d864ccd5.png">

**Comment by brentsimmons** [comment]
Closing this issue because we made a change where the unread count in the sidebar, for the selected item, is generated by counting unread articles in the timeline. This should mean that this can’t happen.
