### ISSUE TITLE
right arrow does not open a selected article in browser

### ISSUE THREAD

**Issue by Thomas-U** [brentsimmons/NetNewsWire#785]
I really miss this feature as I am used to it from previous NNW versions.

**Quote from Slack channel general on March 25th 2019:**
Thomas_U [18:43]
In NNW4 I can open an entry in the browser by just pressing the right arrow key. In NNW5 I have to press CMD-right arrow. Is there a reason for that?

brentsimmons [18:47]
Sounds like a bug. In the meantime, you can use the b key.

**Comment by brentsimmons** [comment]
We decided that the right arrow key should move focus to the article view. This is consistent with how the right arrow key moves focus from sidebar to the timeline view.

The b, Return, and Enter keys are single-key shortcuts for open in browser.

**Comment by Thomas-U** [comment]
What I don't understand: When the focus is on an article already, why not open this article in the browser on next right arrow press like in previous NNW versions?

**Comment by voorth** [comment]
Please reconsider. I find the right-arrow quite strongly embedded in my muscle memory.
Also, being able to go to the list and open pages with one hand is convenient.
