### ISSUE TITLE
iOS: Youtube embeds negatively impact article rendering 

### ISSUE THREAD

**Issue by stuartbreckenridge** [brentsimmons/NetNewsWire#790]
![iVBORw0KGgoAAAANSUhEUgAABaMAAAszCAYAAACIWkB7AAABgmlDQ1BzUkdCIElFQzYxOTY2LTIu-2](https://user-images.githubusercontent.com/7046652/60270725-8e312000-9923-11e9-89c6-45568fb3616f.PNG)

**Comment by evamedia** [comment]
It’s fairly trivial to pull the thumbnails instead

**Comment by vincode-io** [comment]
I updated the CSS to fix this issue.
