### ISSUE TITLE
HTML table not rendered correctly

### ISSUE THREAD

**Issue by chmaynard** [brentsimmons/NetNewsWire#793]
On my website, I use tables defined using HTML and CSS (no javascript). The tables look something like this in Safari:

<img width="774" alt="Screen Shot 2019-06-28 at 11 32 27 AM" src="https://user-images.githubusercontent.com/13698964/60353623-747df000-9998-11e9-97e5-5ade1ed32b91.png">

When I view the webpage in NetNewsWire Version 5.0a4 (2237), it looks like this:

<img width="626" alt="Screen Shot 2019-06-28 at 11 34 28 AM" src="https://user-images.githubusercontent.com/13698964/60353824-dcccd180-9998-11e9-86df-960d3ad62734.png">

Assuming that both Safari and NetNewsWire use the same WebKit-based rendering engine, is there anything that can be done to improve this? 

Edit: To view this webpage, visit https://www.corememory.io/sophiko-simsive.html

**Comment by brentsimmons** [comment]
You would have to include the CSS for that table in that <item> in your RSS feed. It would have to be inline or somehow referenced in the HTML.

**Comment by chmaynard** [comment]
@brentsimmons Cool, thanks.

**Comment by Wevah** [comment]
The default styles for tables in the article view could maybe have some borders/padding.
