### ISSUE TITLE
feature: pressing "v" should open an article in a browser

### ISSUE THREAD

**Issue by abrin** [brentsimmons/NetNewsWire#794]
somehow my brain is still programmed in NetNewsWire to hit "v" to view the full text of a message... it'd be fun if this keyboard shortcut legacy still existed.

**Comment by brentsimmons** [comment]
What app used the v key?

**Comment by abrin** [comment]
Hmm, I could have sworn this was an old NetNewsWire keybinding, but clear, you would know. Perhaps it was something I've used in the interim.  sorry. As an aside, I started using NetNewsWire since 2003-4 (or maybe earlier).  It's so nice to have it running on my Mac again.
