### ISSUE TITLE
Broken Links In Tested.com atom feed.

### ISSUE THREAD

**Issue by ctriv** [brentsimmons/NetNewsWire#797]
The links in http://www.tested.com/feeds/ don't seem to be complete within netnewswire.  Ends at the first hyphen.  For example https://www.tested.com/881372 is opened in the browser instead of https://www.tested.com/science/space/881372-offworld-frances-poppy-northcutt/

**Comment by brentsimmons** [comment]
There’s a bug in the feed — it supplies permalinks that are just item IDs (such as 881372). NetNewsWire treats that as a relative URL, as it should.

It would be nice to come up with a reliable way of detecting this situation and working around the bug in the feed.

**Comment by ctriv** [comment]
Thanks for replying back with the root cause.  I'll reach out to the site to see if they can fix their feed.
