### ISSUE TITLE
Account.removeFeed() doesn't handle the case where nil is passed as the container

### ISSUE THREAD

**Issue by olofhellman** [brentsimmons/NetNewsWire#802]
Account.swift has this function:

	public func removeFeed(_ feed: Feed, from container: Container?, completion: .... )

container is clearly marked as an optional, so one should be able to pass nil as the container, but in the LocalAccountDelegate.removeFeed code, there's this:

         container?.removeFeed(feed)

which clearly doesn't do any feed removal for nil containers.

To repro this error, run this script:

tell application "NetNewsWire"
	tell account id "OnMyMac"		
		make new feed with data "https://boingboing.net/feed"
	end tell
end tell

(which will error, but will create a new feed in the "OnMyMac" account), followed by this script:

tell application "NetNewsWire"
	tell account id "OnMyMac"
		delete feed id "https://boingboing.net/feed"
	end tell
end tell

**Comment by olofhellman** [comment]
I believe this is a regression introduced with change commit #5e3fcfd95546a04197bc61b13205e3a70a18f580 on May 29, 2019 by @vincode-io

**Comment by vincode-io** [comment]
I changed the Account interface to require the container on removeFeed to be more consistent with the other functions.  It was required in all the other ones.

I update the necessary places to handle the API change and now the scripts you referenced work and the testIterativeCreateAndDeleteScript test case no longer fails.

Currently this fix is only on the mac-candidate branch, but will be moved to master in the near future.
