### ISSUE TITLE
Slow/unresponsive on refresh (~30s, Feedbin sync)

### ISSUE THREAD

**Issue by tullyhansen** [brentsimmons/NetNewsWire#804]
Posting at @vincode-io's suggestion from the [Slack](https://netnewswire.slack.com/archives/CC4LQ2D8R/p1563302125414600) – I was last night seeing beachballing/unresponsiveness during NNW refreshes (after not using the app in weeks). Seems to have settled now, maybe to do with my 17,000+ unread items? 😎

`Version 5.0a4 (2237)`, (zipped) OPML attached as requested, further info/diagnostics on request: 
[Tully-H-Subscriptions-Feedbin.opml.zip](https://github.com/brentsimmons/NetNewsWire/files/3401691/Tully-H-Subscriptions-Feedbin.opml.zip)

EDIT: Ah, it's almost certainly when switching to 'All Unread' in sidebar…

**Comment by vincode-io** [comment]
I’m going to close this issue as it should already be fixed in the next release.  We can reopen this ticket if it is still an issue on the next release.
