### ISSUE TITLE
Visual oddity

### ISSUE THREAD

**Issue by chrisbulow** [brentsimmons/NetNewsWire#805]
Sidebar has 'placeholders' for two emoji that the reading pane renders just fine

![2019-07-17 at 14 03](https://user-images.githubusercontent.com/7009135/61377839-e8c2f980-a89b-11e9-99a0-d48f219a90d8.jpg)

**Comment by jsit** [comment]
Can you please modify the title of this Issue so that it's a bit clearer? Thanks.

**Comment by chrisbulow** [comment]
I'll delete the ticket.
