### ISSUE TITLE
AppleScript: Account Identification for Scripting is Unfriendly

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#807]
We need a user-friendly way of identifying which account we wish to work with in an AppleScript.

Prior to implementing multiple account support, there was only the "On My Mac" account which had an Account.id of "OnMyMac".  This is a reasonable identifier for utilizing in an AppleScript.

After implementing multiple account support, we have Account.id's that are actually UUID's that are hidden from the user.  Currently the only way to get an Account.id other than OnMyMac, is to go rooting around in the Accounts folder and trying to figure it out.

One option is to use the Name of the Account, but currently there is no guarantee of uniqueness on Account Names.  Another option is to display the UUID in the Account in the Preferences window and expect the user to cut and paste that into the script.

**Comment by brentsimmons** [comment]
It’s okay that there’s no guarantee of uniqueness on account names.

We should be able to say things like:

every account whose name is “Jane’s Feedbin account” (returns array)

first account whose name “Jane’s Feedbin account” (returns Account)

first account whose type is “Feedbin” (returns Account)

etc.

That leaves it to the scripter to figure out what to do.

Note: I might have the AppleScript syntax wrong for the above, but I think it gets the idea across.

**Comment by brentsimmons** [comment]
This is probably all working as it should be, but I want to verify that first before closing this.

**Comment by brentsimmons** [comment]
I’m trying to get the following script to work:

tell application "NetNewsWire"
	set myAccount to first account whose type is feedbin
end tell

But I get an error: 

"NetNewsWire got an error: Can’t make type into type specifier." number -1700 from type to specifier

If I can get this working — picking an account by type — then I’ll close this.

**Comment by brentsimmons** [comment]
Also — the following needs to work:

set myAccount to first account whose name is "Feedbin"

(Where “Feedbin” is the actual name of an account.)

**Comment by brentsimmons** [comment]
Got the above working.
