### ISSUE TITLE
Doesn't show content for feed

### ISSUE THREAD

**Issue by bamse16** [brentsimmons/NetNewsWire#810]
Hello,

When adding the feed https://thenib.com/feeds/rss, the content embedded in <description><![CDATA[ does not show.

I'm note sure if that's a feed issue or a news reader/parser issue.

Thank you,
Marius

**Comment by brentsimmons** [comment]
It’s a bug in the feed — that content is essentially empty.

      <content:encoded><![CDATA[
      <div>
        
      </div>
      ]]></content:encoded>
