### ISSUE TITLE
Image appearing pixelated

### ISSUE THREAD

**Issue by rtvenge** [brentsimmons/NetNewsWire#811]
It appears that this image is being rendered larger than its resolution:

<img width="2337" alt="Screen Shot 2019-07-22 at 10 20 55 AM" src="https://user-images.githubusercontent.com/303836/61651287-6c992f00-ac6a-11e9-9237-ee3424627137.png">

## Feed URL

`https://thewirecutter.com/feed/`

## Article Link

`https://thewirecutter.com/blog/its-no-secret-were-big-fans-of-costco/`

## Image Tag

`<img class="image" src="https://cdn.thewirecutter.com/wp-content/uploads/2019/07/Costco-lowres-14-570x380.jpg" alt="It’s No Secret: We’re Big Fans of Costco" srcset="https://cdn.thewirecutter.com/wp-content/uploads/2019/07/Costco-lowres-14-630x420.jpg 630w, https://cdn.thewirecutter.com/wp-content/uploads/2019/07/Costco-lowres-14-570x380.jpg 570w, https://cdn.thewirecutter.com/wp-content/uploads/2019/07/Costco-lowres-14-330x220.jpg 330w, https://cdn.thewirecutter.com/wp-content/uploads/2019/07/Costco-lowres-14-200x134.jpg 200w, https://cdn.thewirecutter.com/wp-content/uploads/2019/07/Costco-lowres-14-120x80.jpg 120w" />`

## Expected Result

Rendering should respect the `srcset` attribute and either render the largest `w` or render the appropriate size based on the user's viewport. If `srcset` is not available, it should render the `src` attribute.

In this particular case, the width should be max out at `570px`.

I am a web developer and am not a Mac/Swift developer so if any of the assumptions I've made above are wrong, please set me straight. 😄

**Comment by brentsimmons** [comment]
We’re using a standard web view here, so the decision about which image to use is up to WebKit code.

However, we might have CSS that causes the image to resize-to-fit. Not sure. It should be investigated.

**Comment by rtvenge** [comment]
Let me look into this a little more. I found the css file and got it compiled in Xcode so I’ll test it out and see if I can’t come up with a fix. It might also be that Wirecutter is doing something weird but it appears that they are just using the `srcset` function built into WordPress.

I’ll update here when I find out more.

Thanks @brentsimmons!

**Comment by rtvenge** [comment]
After researching this pretty extensively, the issue is on the publisher's side. They aren't using the `sizes` attribute on the `<img>` tag, and according to [this article](https://medium.com/@MRWwebDesign/responsive-images-the-sizes-attribute-and-unexpected-image-sizes-882a2eadb6db), 100vw is assumed on the tag:

> Importantly, if you specify srcset but not sizes, “100vw” is the assumed default of the sizes attribute.

I'll close this issue as there isn't really any action on the app's part.
