### ISSUE TITLE
Crashing Bug: Context Menu "Mark All as Read" on feed nested under folder

### ISSUE THREAD

**Issue by strangebirds** [brentsimmons/NetNewsWire#828]
Version 5.0b1 (2298) (newest)

I don't know if this is a new bug - I usually "Mark All as Read" at the folder level (right click on left pane item). I added a new feed and after skimming titles, attempted to mark as read and crashed.

After restart of NNW, I tried again and app crash reoccured.

Subsequent attempts with other feeds reproduced 100% of time.

NNW does not crash (or I couldn't make it crash) doing this action on the folder level, only on the feed level inside a folder (I have no feeds that are not in folders so didn't test that case).

Attached is the info from the crash dialog to send to Apple - I'm not sure if these get passed along to the developers.

[NNW beta crashing bug report - 12 Aug 2019.txt](https://github.com/brentsimmons/NetNewsWire/files/3491922/NNW.beta.crashing.bug.report.-.12.Aug.2019.txt)

**Comment by brentsimmons** [comment]
Thanks!

Fixed in 5.0b2.
