### ISSUE TITLE
Unread count not showing in feeds list

### ISSUE THREAD

**Issue by IainDelaney** [brentsimmons/NetNewsWire#829]
This is with b2.
In the first screenshot, there is no count beside blogs, but there is one article in the article list.
![Screen Shot 2019-08-12 at 3 52 29 PM](https://user-images.githubusercontent.com/221685/62893958-b8933d00-bd19-11e9-9c29-9773f5830495.png)

In the second screenshot, the blogs folder is expanded, and the count of 1 shows.
![Screen Shot 2019-08-12 at 3 54 05 PM](https://user-images.githubusercontent.com/221685/62893974-c1840e80-bd19-11e9-9391-0685e0eec7d4.png)

**Comment by mkrus** [comment]
I see this, and also folder total being wrong as in (5 instead of 6):
<img width="627" alt="Apple__6_" src="https://user-images.githubusercontent.com/1125269/62949723-a0392600-bdde-11e9-94f8-73806f692f45.png">
