### ISSUE TITLE
Multi-Line UI Listing error

### ISSUE THREAD

**Issue by ErniePC12** [brentsimmons/NetNewsWire#837]
I just imported my feeds list form NNW 3 into NNW 5.  

When viewing the following feed, the listing for the entries is overlapping at the bottom of only the unread items.

If you mark hem as read, then they will appear normal.  You can also make them as unread and they will appear normal but without the icon.

<img width="452" alt="image" src="https://user-images.githubusercontent.com/187422/62903438-a40e6f00-bd30-11e9-9c25-871cd3912b50.png">

**Comment by brentsimmons** [comment]
What’s the feed URL?

Do have just that feed selected in the sidebar?

Which OS version?

**Comment by ErniePC12** [comment]
Sorry for forgetting that.

http://apple.stackexchange.com/feeds 

I had the feed selected on the left side when the list showed up with the icons and the UI issue.

I'm running the macOS Catalina Beta (19A526h) on a MacBook Pro (Early 2013)

Let me know if I can help in any way.

**Comment by brentsimmons** [comment]
One more question, which I should have remembered to ask — are you using Feedbin with this feed or On My Mac?

**Comment by ErniePC12** [comment]
On My Mac.

**Comment by brentsimmons** [comment]
Does this happen every time? Or did it just happen once? Or…?

**Comment by brentsimmons** [comment]
I suspect this a glitch (just this one report, and I can’t reproduce it), so I’m moving it to the 5.0.1 beta milestone so we can look at it more after shipping.

**Comment by ErniePC12** [comment]
I just updated to 5.0b4 and I notice that the issue is no longer there.  You can probably close this, I can't seem to make it happen again.
