### ISSUE TITLE
Bug with 'All Unread' smart feed and deleting a feed with unread items

### ISSUE THREAD

**Issue by tt-tsquared** [brentsimmons/NetNewsWire#838]
I just downloaded 5.0b2 (2299).
I was going through the feeds and deleting a few that didn't interest me. I deleted the Seattle Xcoders feed but when I finished there were 25 unread items in 'All Unread'.. all from Seattle Xcoders that had been deleted.

<img width="638" alt="image" src="https://user-images.githubusercontent.com/5551330/62905508-13339580-bd28-11e9-9704-7babdd0bc987.png">

**Comment by tt-embodied** [comment]
Also still getting new items from NSCoder Seattle today..

![image](https://user-images.githubusercontent.com/48922851/62982769-87cf0880-bdea-11e9-87a9-11ff7c0d8cbb.png)
