### ISSUE TITLE
Today smartfeed shows last 24 hours

### ISSUE THREAD

**Issue by portenkirchner** [brentsimmons/NetNewsWire#840]
The today smartfeed does not only show today's feed items (since midnight), but all feed items within the last 24 hours.

**Comment by brentsimmons** [comment]
This is by design. It’s so that if you’re reading your feeds at midnight the Today feed doesn’t suddenly empty out. :)

**Comment by portenkirchner** [comment]
Wasn't this different before? So it is more like a 24 hour feed than a Today feed?

**Comment by brentsimmons** [comment]
Yes, this was different before, but people wanted it to be more like a 24 hour feed rather than clearing out at midnight.

We’re stretching the meaning of “Today,” I realize, but it’s okay. :)
