### ISSUE TITLE
icons and text not showing in toolbar, no option to add

### ISSUE THREAD

**Issue by ih8quark** [brentsimmons/NetNewsWire#845]
10.4.6 Mojave, under customize toolbar, there is no option to add icons with text, only use small size.
<img width="949" alt="Screen Shot 2019-08-14 at 7 57 05 PM" src="https://user-images.githubusercontent.com/54124689/63064115-b96cd000-becd-11e9-827c-3981cb5b1047.png">

**Comment by brentsimmons** [comment]
We’re using a Safari-style toolbar, which means no text.

We do have a hidden pref for this, though:

https://github.com/brentsimmons/NetNewsWire/blob/master/Technotes/HiddenPrefs.md
