### ISSUE TITLE
Feature Request: "Open in Browser" not create duplicates

### ISSUE THREAD

**Issue by strangebirds** [brentsimmons/NetNewsWire#860]
I am unsure if this is a NNW-controlled behavior or a Safari-controlled behavior.

If I "Open in Browser" (click on feed title, right arrow, context menu) the article opens in the browser. If I do this again, the article opens again, so now two tabs (in my case) with the same article. To my eye everything looks the same including the URL - no unique identifier.

Is it possible to scan open tabs and switch to that one instead of opening a new one? Although then that raises the question of if this is desirable behavior for all users? Or possibly could create a bottleneck in checking if there are many open tabs?

**Comment by brentsimmons** [comment]
This is Safari-controlled behavior. The API we have available to us is pretty simple — we can just ask Safari to open a URL. Then Safari does whatever it wants with the request.

There might be some way to scan tabs using AppleScript, though. My concern is that this would be a potential performance hit every time you send a URL to Safari.

**Comment by strangebirds** [comment]
Ah, I thought as much.
