### ISSUE TITLE
Feature Request: Render LaTeX in articles

### ISSUE THREAD

**Issue by jvonfricken** [brentsimmons/NetNewsWire#864]

**Comment by cmconnelly** [comment]
Example article:  https://blog.plover.com/math/freyd-theory.html

**Comment by brentsimmons** [comment]
The article pane is rendered entirely by WebKit, and there’s not much we can do to make WebKit render LaTeX. (Well, we could, but it would probably take six months while we stop work on NetNewsWire itself, and even then there’s no guarantee it would be accepted into WebKit).

I recommend submitting a feature request to the WebKit folks that they add LaTeX rendering.

**Comment by schiegl** [comment]
Is there a way to inject [KaTeX](https://katex.org) or [MathJax](https://www.mathjax.org)? This would probably cover most of the use cases of LaTeX i.e. mainly mathematical expressions in articles.
