### ISSUE TITLE
not syncing/refreshing

### ISSUE THREAD

**Issue by seaphotog** [brentsimmons/NetNewsWire#867]
Yesterday I had feeds, today - Netnewswire thought it wasn't connected to the inter-webs (when all was fine). I exported my feeds -- have the OPML. I was on NNW 4, so I upgraded and trashed the old and launched the new - still no feeds filled. These are "on my mac" and the version is updated. It looks like it's updating (I see a short progress bar) but can't see anything - thoughts? 
![AppleTimeMachineExtra_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_Item-0_and_UAMenu_and_Item-0_and_Item-0](https://user-images.githubusercontent.com/7770507/63400650-6db49d80-c389-11e9-8009-6f4c5961dd5e.jpg)
![A-Nadia_Bolz-Weber](https://user-images.githubusercontent.com/7770507/63400661-786f3280-c389-11e9-91eb-23f10893218f.jpg)
![About_This_Mac_and_A-Nadia_Bolz-Weber](https://user-images.githubusercontent.com/7770507/63400665-7c02b980-c389-11e9-9f80-5033f4f422c3.jpg)

**Comment by brentsimmons** [comment]
I assume you clicked the refresh button, and also tried quitting and restarting the app.

It really looks like it’s not connected to the internet. Could it be something like Little Snitch blocking connections?

**Comment by seaphotog** [comment]
yes tried all of those things. I'm connected - (sending to you for instance) - NNW just doesn't think so. I can see the refresh bar getting things on the refresh, but then they are not showing up on either the preview or read pane - so app knows it's connected. just not opening the feeds. And - it's not just my feeds - I tried adding and it won't add:
![Today](https://user-images.githubusercontent.com/7770507/63449517-2a901400-c3f5-11e9-864d-e67a46df133c.jpg)
- and when I did a refresh (took me a few times to get a snap) -- there were feeds coming in on this...but not showing up.
![Today_and_Breaking_down_silos_and_disrupting_tradition__with_fight_posters__](https://user-images.githubusercontent.com/7770507/63449593-45628880-c3f5-11e9-95e0-0a01494dcad0.jpg)
Thanks for the quick response - I love NNW - don't want to stop using it, but there is something strange going on. I'll trash and reinstall again though

**Comment by vincode-io** [comment]
It definitely looks like something is preventing NetNewsWire from connecting to the internet.

Are you running any antivirus or firewall software?  Is this a work computer where someone may have changed some firewall settings on it without you knowing?

**Comment by seaphotog** [comment]
took all of it offline to check and still no go

**Comment by seaphotog** [comment]
Ok - resolved with a full restart.

**Comment by brentsimmons** [comment]
Whew! Thanks for letting us know.
