### ISSUE TITLE
Undo Delete Feed Doesn't Restore the Feed Immediately

### ISSUE THREAD

**Issue by mikehay** [brentsimmons/NetNewsWire#872]
Undo delete feed doesn't restore the feed until you quit and relaunch the app.

**Steps**
1. select a feed by clicking on it in the sidebar
1. hit the 'delete' key
1. be a bit surprised that the feed disappeared, and there was no dialog
1. click on the 'Edit' menu in the menubar and notice that you can undo a delete
1. select 'Undo Delete Feed'
1. notice that the feed has not reappeared in the sidebar

**Version**
NetNewsWire Version 5.0b5 (2607)

**Environment**
macOS 10.14.6
MacBook 12" Early 2016

**Comment by brentsimmons** [comment]
Excellent catch.
