### ISSUE TITLE
unread counts in Smart Feeds inconsistent with rest of sidebar

### ISSUE THREAD

**Issue by mikehay** [brentsimmons/NetNewsWire#873]
Please see attached screenshot.

Unread counts in the Smart Feeds indicate that there are unread articles, but ... looking down the sidebar, there are no feeds with unread articles showing.

<img width="1440" alt="Screen Shot 2019-08-23 at 5 59 56 PM" src="https://user-images.githubusercontent.com/5312092/63626259-59aead00-c5d0-11e9-8e7f-b2f9442396d1.png">

**Version**
NetNewsWire Version 5.0b5 (2607)

**Environment**
macOS 10.14.6
MacBook 12" Early 2016

**Comment by brentsimmons** [comment]
If you select the smart feeds, are there unread items? In other words — who has it wrong, the smart feeds or the feeds/folders?

**Comment by mikehay** [comment]
Great question. The unreads were in The Omni Group feed, which was not shown because of #872
