### ISSUE TITLE
Feature request: Open items URLs directly in right view instead of RSS content

### ISSUE THREAD

**Issue by skylex** [brentsimmons/NetNewsWire#879]
On most websites we don't have the full content of the articles in the RSS feeds. So it means that for every article we read, we have to open it in a browser tab, close it and go back to NetNewsWire.

It might be cool to implement a WebView where we could open articles directly in NetNewsWire. Even cooler would be a "reader" mode where only the article's title, text content and images are displayed instead of the full website.

NetNewsWire should remember which mode (RSS, Web, Reader) was lastly used for each feed, so usage is straightforward.

**Comment by vincode-io** [comment]
This has been implemented under issue #1013.
