### ISSUE TITLE
Large feed images can cause slow article rendering

### ISSUE THREAD

**Issue by adiabatic** [brentsimmons/NetNewsWire#892]
First off, thanks for helping keep feed reading great!

My site's feed at <https://www.frogorbits.com/atom.xml> is slow to display in NNW. That is, when I select an item in the leftmost non-sidebar pane, it takes about two seconds for that item to render in the rightmost pane. By contrast:

- The Daring Fireball feed at <https://www.daringfireball.net/feeds/json> gives me near-instantaneous renders.
- Gus's feed at <https://shapeof.com/feed.json> gives me near-instantaneous renders.
- <https://www.greaterwrong.com/?format=rss>, which is not JSON Feed, gives me near-instantaneous renders.

I changed the `id` elements from UUIDs to URLs, deleted `~/Library/Application Support/NetNewsWire/Accounts/OnMyMac/`, re-launched NNW, and re-added my site's feed. Still just as slow to render.

The W3C feed-validation service [says my atom.xml is valid Atom 1.0](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.frogorbits.com%2Fatom.xml).

This happens on both my iMac and MacBook Pro. Both are running Mojave at 10.14.6 (the latest as of today).

Any ideas why this might be happening on my site feed only?

**Comment by sashkab** [comment]
Is this related to displaying the image, or downloading it? If later, did you consider pre-caching images for unread articles?

**Comment by brentsimmons** [comment]
It’s related to encoding the image for use in the web page as inline data, and then including a huge amount of inline data in a page. (The image is cached.)

**Comment by brentsimmons** [comment]
Fixed in c3e26ea307248b5ed0b8638098a17b2abfd94f2e
