### ISSUE TITLE
Unable to find bioRxiv feed

### ISSUE THREAD

**Issue by enricoscarpella** [brentsimmons/NetNewsWire#893]
Hello,

I have just downloaded NetNewsWire 5.0, and I love the interface. Unfortunately, however, I cannot add feeds from bioRxiv (http://connect.biorxiv.org/biorxiv_xml.php?subject=plant_biology) because NetNewsWire 5.0 is unable to find the feed. The feed works perfectly in Vienna. Could anyone please be so kind to help me or at least point me in the right direction? Thank you for your consideration.

Best regards,
Enrico

**Comment by brentsimmons** [comment]
The feed was missing an xml header at the top. Fix done in RSParser.framework.

**Comment by enricoscarpella** [comment]
Thank you very much!
