### ISSUE TITLE
Feature Request: restore selection in sidebar when app is restarted

### ISSUE THREAD

**Issue by schriftgestalt** [brentsimmons/NetNewsWire#900]

**Comment by ned21** [comment]
+1 to this: I keep all my feeds in folders. Whenever I start NNW, all folders are collapsed and I have to go through and expand my favourites before I start reading. Retaining the open/closed state of folders in the sidebar across restarts would be a big time-saver for me.

**Comment by brentsimmons** [comment]
Duplicate of #300.
