### ISSUE TITLE
particular feed has black text, making it hard to read

### ISSUE THREAD

**Issue by will** [brentsimmons/NetNewsWire#910]
I just added the google project zero feed ( https://googleprojectzero.blogspot.com/feeds/posts/default?alt=rss ) and noticed that the posts are not really readable in NNW. 

![image](https://user-images.githubusercontent.com/1973/63985646-6118ff00-ca85-11e9-8b97-cc4b7ddb8edb.png)

My guess is the markup in the post is specifying a black color for the font, rather than leaving that agnostic (but I haven't verified this), so I'm not sure if this is something NNW should handle.

NNW Version 5.0 (2609)
mac os 10.14.6 (18G87)

**Comment by brentsimmons** [comment]
Looks like you’re right. I recommend reporting it to them as a bug. (I agree that NetNewsWire shouldn't try to parse the HTML and override their styles.)

**Comment by will** [comment]
Ok. I've tried to contact them. I'll close this.

**Comment by will** [comment]
Maybe if they never do fix it, a way to force a particular feed to have the light-mode background manually would be a stop-gap solution?

**Comment by brentsimmons** [comment]
If this is a thing that keeps coming up, then we’d consider it. But it would have to be a frequent-enough problem to warrant adding a per-feed setting for this.
