### ISSUE TITLE
Blocked main thread when changing selection

### ISSUE THREAD

**Issue by dkocher** [brentsimmons/NetNewsWire#913]
Maybe related to #758. This can best be reproduced while refresh is in progress and change the selection to a feed with many articles. Attached two samples.

 * [Sample of NetNewsWire 0x10f9e9000.txt](https://github.com/brentsimmons/NetNewsWire/files/3558664/Sample.of.NetNewsWire.0x10f9e9000.txt)
 * [Sample of NetNewsWire 0x106818000.txt](https://github.com/brentsimmons/NetNewsWire/files/3558665/Sample.of.NetNewsWire.0x106818000.txt)

**Comment by sgoodwin** [comment]
I have the same issue, here's my feed list (I think it needs to be a relatively long list to notice)


[Subscriptions-Local.opml.zip](https://github.com/brentsimmons/NetNewsWire/files/3574564/Subscriptions-Local.opml.zip)

**Comment by brentsimmons** [comment]
It does a synchronous fetch when changing selection, by design. Normally this is so fast you don’t notice it. But it is a main-thread-blocker, and if it’s not fast — well, then you notice it.

**Comment by dkocher** [comment]
Attached a sample with 5.0.1d1. The user interface freezed prior and while the sample was taken.
[Sample of NetNewsWire 5.0.1d1.txt](https://github.com/brentsimmons/NetNewsWire/files/3584542/Sample.of.NetNewsWire.5.0.1d1.txt)

**Comment by brentsimmons** [comment]
Moving this out of the milestone. With recent performance fixes, let’s see if this is still a problem.

**Comment by dkocher** [comment]
I consider this issue resolved with 5.0.3.

**Comment by sgoodwin** [comment]
Thank you Brent or whomever fixed this!

**Comment by brentsimmons** [comment]
Team effort, as always. 👍
