### ISSUE TITLE
JSON Feed icon/logo missing from Feedbin account

### ISSUE THREAD

**Issue by livid** [brentsimmons/NetNewsWire#917]
Our website starts to support JSON Feed recently. It is an online community like Reddit, and it has a lot of subforums, so each subforum's feed has its own icon/logo like this:

https://www.v2ex.com/feed/create.json
https://www.v2ex.com/feed/vscode.json

Now I encountered two issues relating to the icon/logo:

1. If I added the feeds on Feedbin website, NNW could not get the customized icon/logo in the JSON Feed.

2. If I added the feeds from NNW to Feedbin account, it could show icon/logo correctly, but reverted to the domain's /favicon.ico after NNW app restarted.

JSON Feed icon/logo works flawlessly in local account.

**Comment by livid** [comment]
Feedbin website can show the feed logos properly, and I noticed that there is an extended parameter in Feedbin API.

**Comment by livid** [comment]
Here is a screenshot. Feedbin website can support Icon/Logo in JSONFeed perfectly, but after configured the Feedbin account in NNW, it cannot get those Icon/Logo:

<img width="501" alt="Screen Shot 2019-09-30 at 2 13 52 PM" src="https://user-images.githubusercontent.com/11427/65917775-02e58180-e38d-11e9-91cd-b6640e139389.png">

**Comment by vincode-io** [comment]
Feedbin doesn't currently support multiple multiple feed icons per domain.  They would have to enhance their subscriptions.json feed to provide that or add some other service.  The service they currently provide is this one.  https://github.com/feedbin/feedbin-api/blob/master/content/icons.md

It looks like our own Favicon lookup logic works the same as the Feedbin webapp does.  One option we have would be to remove support for the Feedbin icons.json service and fallback to our own Favicon logic.  We could then have multiple Favicons per domain name on Feedbin accounts.

**Comment by livid** [comment]
If `mode=extended` is used for `subscriptions.json`, then those icons can be found in each item's `json_feed` field.

```
/v2/subscriptions.json?mode=extended
```

**Comment by vincode-io** [comment]
Thanks for pointing that out @livid.  We'll add support for this in the 5.0.4 release of NetNewsWire.
