### ISSUE TITLE
Toolbar "Icon and Text" and "Text Only" options

### ISSUE THREAD

**Issue by InternetEnzyme** [brentsimmons/NetNewsWire#919]
I believe that "Icon and Text" is a fundamental usability option that all Mac apps must include for their Toolbars. It would also be nice if monochrome versions fir of all the glyphs were provided.

**Comment by brentsimmons** [comment]
On this page you’ll find instructions for using the hidden pref that turns on “Icon and Text.”

https://ranchero.com/netnewswire/help/mac/5.0/en/hidden-preferences

**Comment by InternetEnzyme** [comment]
Thank you. It is interesting that "Icon and Text" is an option only available to the older appkit window toolbar style.
