### ISSUE TITLE
Feature request: sort articles by date in folder view

### ISSUE THREAD

**Issue by stewf** [brentsimmons/NetNewsWire#940]
When selecting a folder the middle column lists articles grouped by feed. I’d love the option to see articles mixed from all feeds in chronological order.

**Comment by brentsimmons** [comment]
Are you sure you’re using NetNewsWire 5.0? Because it does sort by date instead of by feed. Maybe NetNewsWire 4 grouped by feed?

**Comment by stewf** [comment]
Whoops! I have the right version. I was just looking at a folder in which all the articles in each feed happened to be of similar dates. Very sorry.

**Comment by brentsimmons** [comment]
Got it. All good!
