### ISSUE TITLE
Get Permission denied error on launch

### ISSUE THREAD

**Issue by gullevek** [brentsimmons/NetNewsWire#942]
macOS 10.14.6
NetNewsWire 5.0

1) Went to the homepage and downloaded the zip file
2) Extracted the zip file with the standard zip extractor
3) Moved the .app file to the Global Applications folder
4) Launch it

I get a window with the following error message
"The application “NetNewsWire.app” can’t be opened."

and in the system.log I see the following entries:

Sep  2 14:12:37 COMPUTERMAC com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000003d.NetNewsWire[74379]): Could not find and/or execute program specified by service: 13: Permission denied: /Applications/NetNewsWire.app/Contents/MacOS/NetNewsWire
Sep  2 14:12:37 COMPUTERMAC com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000003d.NetNewsWire[74379]): Service exited with abnormal code: 78

The file in the folder there has rw-rw-r rights. Changing that to something else (+x) just gives a warning that the app is corrupted and it moves itself into the trash.

**Comment by brentsimmons** [comment]
To unzip it, did you just double-click the .zip file? That should work.

**Comment by gullevek** [comment]
Yes, I just double clicked on the zip file. Uses the default Archive Utility from macOS

**Comment by brentsimmons** [comment]
Have you tried re-downloading it? I know it’s the obvious thing, but I figured I should ask. :)

**Comment by gullevek** [comment]
I actually tried that yesterday already. I get exactly the same ZIP file, but the md5 hash differ. But the app file I got out of it are all exactly the same (run a find on files and created md5 for each file)

**Comment by gullevek** [comment]
I found the problem to be our corporate firewall that seems to open .zip files from github and meddle with them and remove the executable bits.

**Comment by brentsimmons** [comment]
That’s incredible. I’ve never heard of that before. Wow.

**Comment by gullevek** [comment]
haha, yeah. corporate security can make your head explode. Don't even want to talk about the SSL injections that prevent me from direct download from github until I turn of the "security" software on my computer.
