### ISSUE TITLE
Parsing error: It is using Author Title as a Title

### ISSUE THREAD

**Issue by ogun** [brentsimmons/NetNewsWire#943]
Today when I tried to add Google Cloud Blog RSS, I've realized that the titles are a little bit different. When I check the RSS, I understand that it is using "item > author > title" instead of "item > title".

Version: 5.0 (2609)
Source: https://cloudblog.withgoogle.com/rss/

Expected:
Title: Beyond the Map: Solving problems and powering location-based services with imagery

Observed:
Title: Product Director

**Comment by brentsimmons** [comment]
Fixed in RSParser.
