### ISSUE TITLE
LLVM blog not rendering right in dark mode

### ISSUE THREAD

**Issue by mvcoile** [brentsimmons/NetNewsWire#947]
I noticed that the llvm blog does not render right with dark mode on. Might be the case for more Blogger feeds.

![screenshot](https://cl.ly/b104464dce23/Image%2525202019-09-03%252520at%25252012.11.14%252520AM.png)

url: http://blog.llvm.org/
feed: http://blog.llvm.org/feeds/posts/default

**Comment by brentsimmons** [comment]
They must be including some kind of inline styling. Parsing that and stripping it out is not a thing we’re eager to do, since it would be so prone to failure. But maybe there’s an 80% (or Blogger-specific) thing we can do.

**Comment by vincode-io** [comment]
We have resolved this issue.  The fix will be in the 5.0.3 release.
