### ISSUE TITLE
Feature Request: Only show feeds with unread articles

### ISSUE THREAD

**Issue by bviefhues** [brentsimmons/NetNewsWire#950]
Would be great if NNW had an option to only show feeds with unread articles in the sidebar. Feedbin can do this in its web UI. Note: this is not NNW's "Unread" article list. It rather filters the Folder/Feed tree, i.e. preserves the structure.

**Comment by brentsimmons** [comment]
I hear you.

Duplicate of https://github.com/brentsimmons/NetNewsWire/issues/129
