### ISSUE TITLE
Feature request: Inline browser with Sticky Full Content

### ISSUE THREAD

**Issue by bviefhues** [brentsimmons/NetNewsWire#951]
Would be great if NNW could be configured to:

1) Use an inline browser instead of opening article pages in Safari et al. The inline browser would render an article page in NNWs article UI container. That would avoid constantly switching between apps.

2) Always attempt to load the full content from the original site for a feed. I.e. have a per-feed setting which always displays the full content instead of the feed summary.

Feedbin can do both of this in its web UI and it's very practical.

**Comment by vincode-io** [comment]
This has been implemented under issue #1013.
