### ISSUE TITLE
River of News?

### ISSUE THREAD

**Issue by richb-hanover** [brentsimmons/NetNewsWire#955]
Hi folks - I'm excited to see NetNewsWire 5.0 hit the streets. But your web page doesn't answer my biggest question - can it display the items as a [River of News?](http://scripting.com/2014/06/02/whatIsARiverOfNewsAggregator.html)

*[I think so, but I can't check just now - I'm not on 10.14. But I'm guessing that the "Today" view would show all the recent stuff, sorted by date, and that would do exactly what I want.]*

And if I'm correct, you might include "river" or "river of news" as a hint in your "Smart feeds" bullet point for the home page. Thanks, and congratulations on shipping!

**Comment by brentsimmons** [comment]
Thanks!

I asked Dave Winer about earlier versions of NetNewsWire that had this same feature, and he did not consider it a proper River of News.

But, even if it did qualify, the app is not really a River-style RSS reader, so it feels like it would be misleading to claim it.
