### ISSUE TITLE
Dwell RSS feed is valid, but doesn't show up

### ISSUE THREAD

**Issue by willie** [brentsimmons/NetNewsWire#956]
https://www.dwell.com/@dwell/rss posts don't show up in NNW5, but feed shows up fine in NNW 3.3.2.

Here are the feed validator results. https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.dwell.com%2F%40dwell%2Frss

**Comment by brentsimmons** [comment]
The feed is empty for some reason:

<?xml version="1.0" encoding="UTF-8"?><rss xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:content="http://purl.org/rss/1.0/modules/content/" xmlns:atom="http://www.w3.org/2005/Atom" version="2.0" xmlns:webfeeds="http://webfeeds.org/rss/1.0" xmlns:media="http://search.yahoo.com/mrss/"><channel><title><![CDATA[Dwell.com]]></title><description><![CDATA[Dwell.com]]></description><link>https://www.dwell.com</link><generator>RSS for Node</generator><lastBuildDate>Tue, 03 Sep 2019 20:07:12 GMT</lastBuildDate><atom:link href="https://www.dwell.com/@dwell/rss" rel="self" type="application/rss+xml"/><webfeeds:icon>https://assets.dwell.com/images/dwell-logo.svg</webfeeds:icon><webfeeds:logo>https://assets.dwell.com/images/dwell-logo.svg</webfeeds:logo><webfeeds:accentColor>211533</webfeeds:accentColor><webfeeds:cover image="https://assets.dwell.com/images/share.jpg"/><webfeeds:analytics id="UA-75111024-1" engine="GoogleAnalytics"/><webfeeds:related layout="card" target="browser"/></channel></rss>

**Comment by brentsimmons** [comment]
I recommend contacting someone there and letting them know that the feed is empty.

**Comment by willie** [comment]
My apologies. I had no problems viewing it in NNW 3.3.2 this morning, but it appears those were unread stories and not newly fetched stories. Weird. I will contact them. Sorry for the false bug report.

**Comment by brentsimmons** [comment]
All good! 😃
