### ISSUE TITLE
iOS: Tapped images should display in fullscreen and be zoomable

### ISSUE THREAD

**Issue by vincode-io** [brentsimmons/NetNewsWire#957]

**Comment by philviso** [comment]
Once this feature is added, it will this feature request from a few months ago trivial to implement...

https://github.com/brentsimmons/NetNewsWire/issues/647

(Tapping an image _link_ should display the image full-screen, similar to how most twitter clients work)

**Comment by vincode-io** [comment]
Joseph Chekanoff is currently working on this feature.

**Comment by vincode-io** [comment]
I ended up implementing this myself.
