### ISSUE TITLE
Bug: Spacebar doesn't respond after scrolling on reading pane

### ISSUE THREAD

**Issue by ErniePC12** [brentsimmons/NetNewsWire#960]
I hit `spacebar` to move from one feed entry to the next.  If I have an entry that displays a lot of content, I will move the mouse over to the far right reading pane and scroll.

After this action, the `spacebar` will no longer allow me to move onto the next feed entry. Hitting `command-/` will move to the next unread entry, and now the `spacebar` will work again.

I am running NNW 5.0 (2609) on a MacBook Pro 2013 running  10.15 Beta (19A546d).

**Comment by brentsimmons** [comment]
It works on my 10.14.6 machine — there’s a good chance this is a 10.15 beta bug.

**Comment by ErniePC12** [comment]
It probably could be.  I don't have my computer running 10.14 to test this.

I will say that I am getting this error on Version 5.0.1d2 (2612) under 10.15 Beta (19A546d)
