### ISSUE TITLE
Make cmd-arrow expand/collapse in sidebar

### ISSUE THREAD

**Issue by brentsimmons** [brentsimmons/NetNewsWire#967]
Option-arrow should also continue to work. But NNW 3.3.2 used cmd-arrow, and we should respect people’s muscle memory when we can.

**Comment by hisaac** [comment]
Looking at this now. Is the option-arrow shortcut something given to us by `NSOutlineView`, or is that hard coded somewhere in the app's code right now?

**Comment by brentsimmons** [comment]
I think it may be provided by NSOutlineView.

The first place to look is SidebarKeyboardShortcuts.plist — it may be that you can do this with no code. Just add two entries for expanding and collapsing via cmd-rightArrow and cmd-leftArrow.

**Comment by hisaac** [comment]
Nice, that does indeed work to add it into the plist file. I'll get a PR filed ASAP.

I noticed a small related issue, and I'm wondering if I should include it in this ticket or if it's out of scope:

When collapsing/expanding using this method, there is no collapse/expand animation. You can see the difference in the current production build by trying <kbd>Option</kbd> + <kbd>→</kbd> or <kbd>←</kbd> (`NSOutlineView`'s provided keyboard shortcut), and compare that to the existing custom keyboard shortcut of <kbd>.</kbd> (period) and <kbd>,</kbd> (comma). The built-in one animates, and the custom one does not.

The custom shortcut calls `collapseSelectedRows:` and `expandSelectedRows:` in the RSCore submodule. I assume this is some of @danielpunkass's code that we're using in the project? Can we make edits to that?

If we wanted to add the animation to expanding and collapsing, adding `animator()` ahead of the `collapseItem()` and `expandItem()` calls on lines 83 and 92 of the `NSOutlineView+Extensions.swift` file in RSCore fixes it, like so:

```swift
animator().collapseItem(item)
```

That uses the `NSOutlineView`'s built in animator to perform the animation, so it should respect any user/OS settings around animation and the like.

**Comment by brentsimmons** [comment]
RSCore is actually ours, not Daniel’s. RS == Ranchero Software in this case. :)

If you would include that animation in the PR, that would be great!

**Comment by brentsimmons** [comment]
Here’s the RSCore repo:

https://github.com/brentsimmons/RSCore

**Comment by hisaac** [comment]
Ah yes, I saw "RS" and thought "Red Sweater". I forgot about Ranchero.

Alrighty, I might not get to it until this weekend, but I'll do a PR for both of these. 👍
