### ISSUE TITLE
Title not shown in the article view

### ISSUE THREAD

**Issue by sashkab** [brentsimmons/NetNewsWire#976]
While browsing my rss subscription, noticed that some articles are missing titles in the article view, while proper title shown in the list of articles, see screenshot below) 

* Version: 5.0 (2609)
* RSS link: http://feeds.feedblitz.com/feedburner/moneysavingmom
* Expected title: Groupon: FREE 3-Month Pandora Premium Subscription!
* Observed title: missing

<img width="1197" alt="screenshot_2019 09 05_093822" src="https://user-images.githubusercontent.com/868842/64346998-2e10c700-cfc1-11e9-983e-167c164ebd2e.png">

Digging further, shows that title is present in the rss:

```xml
<item>
<feedburner:origLink>https://moneysavingmom.com/groupon-free-three-month-pandora-premium-subscription/</feedburner:origLink>
                <title>Groupon: FREE 3-Month Pandora Premium Subscription!</title>
...
</item>
```

**Comment by brentsimmons** [comment]
I don’t even know how that’s possible. Super-weird.

**Comment by sashkab** [comment]
I should probably add that I'm using Feedbin sync.

**Comment by brentsimmons** [comment]
Same thing happens with using On My Mac. I don’t know what’s going on yet.

**Comment by brentsimmons** [comment]
Figured it out.

The style sheet in NetNewsWire blocked all links containing the string “feedburner.” Well, it turns out there are legitimate cases, such as in this case.

(The title is actually a link, so that’s why the title didn’t display.)
