### ISSUE TITLE
Open in Browser provides a broken link

### ISSUE THREAD

**Issue by gpurrenhage** [brentsimmons/NetNewsWire#987]
Big fan of your work, congrats on 1.0, er 5.0!

I subscribe to https://www.tested.com/feeds/, and when I attempt to 'Open in Browser' any of their articles, the rendered URL is malformed.

For an example item:
```<item><title>Adam Savage's One Day Builds: Star-Lord's Walkman!</title><link>https://www.tested.com/art/makers/886840-adam-savages-one-day-builds-star-lords-walkman/</link><description>&lt;div data-video-id="vqqEFEgx-ZI" class="youtube-video"&gt;&lt;/div&gt;</description><dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Gunther Kirsch</dc:creator><pubDate>Thu, 05 Sep 2019 14:00:00 +0000</pubDate><guid>886840</guid></item>```

Expected:
Browser opens to URL `https://www.tested.com/art/makers/886840-adam-savages-one-day-builds-star-lords-walkman/`

Actual:
Browser opens to URL `https://www.tested.com/art/makers/886840`
`Copy Link` returns the same.

Version 5.0 (2609)

**Comment by gpurrenhage** [comment]
I use Chrome, if that's significant

**Comment by brentsimmons** [comment]
It’s a bug in the feed. The feed includes guids which should be treated as permalinks. But they just contain a number, like 886840.

NetNewsWire assumes this is a relative URL, and so it comes up with https://www.tested.com/art/makers/886840 as the absolute URL.

I recommend contacting the feed creator and letting them know to change their XML from…

`<guid>886953</guid>`

…to…

`<guid isPermaLink="false">886953</guid>`
