### ISSUE TITLE
Inline styling risks messing up readability in dark mode

### ISSUE THREAD

**Issue by frippz** [brentsimmons/NetNewsWire#999]
I found a similar issue related to #910 and #499, but this time for a feed from a blog for the Swedish UN peace keeping force in Mali ([feed URL for the curious ones](https://blogg.forsvarsmakten.se/malibloggen/feed/)).

Looking at the code, there are inline style attributes that forces black background. I saw that @brentsimmons noted it being too big of a hammer to strip JavaScript and inline styles, but I think these occurrences will likely turn up often enough that we might have to consider doing something about it. Just not sure what, which is why I wanted to raise the issue again.

([I'm sure no one would go insane if we tried stripping them out with regex this time](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags#1732454)…😉)

**Comment by brentsimmons** [comment]
Love that regex link!

I would, in fact, actually use an XML parser to strip stuff out. :)

**Comment by vincode-io** [comment]
This is resolved and will be in the 5.0.3 release.
